/*
This file is automatically generated
Ft_Esd_SpinBox
C Source
*/

#include "Ft_Esd_SpinBox.h"

#include "FT_Esd_CoPro_Cmds.h"
#include "FT_Esd_Dl.h"
#include "Ft_Esd_Elements.h"

extern void Ft_Esd_Noop(void *context);
Ft_Esd_Theme * Ft_Esd_SpinBox_Theme__Default(void *context) { return Ft_Esd_Theme_GetCurrent(); }
ft_int16_t Ft_Esd_SpinBox_X__Default(void *context) { return 50; }
ft_int16_t Ft_Esd_SpinBox_Y__Default(void *context) { return 50; }
ft_int16_t Ft_Esd_SpinBox_Width__Default(void *context) { return 240; }
ft_int16_t Ft_Esd_SpinBox_Height__Default(void *context) { return 72; }
int Ft_Esd_SpinBox_Step__Default(void *context) { return 1L; }
void Ft_Esd_SpinBox_Changed__Noop(void *context, int value) { }

Ft_Esd_Theme * Ft_Esd_Theme_GetCurrent();
Ft_Gpu_Hal_Context_t * Ft_Esd_GetHost();
static int Ft_Esd_SpinBox_LayoutSplit_Pos__Property(void *context);
static int Ft_Esd_SpinBox_LayoutSplit_Length__Property(void *context);
static int Ft_Esd_SpinBox_LayoutSplit_Numerator__Property(void *context) { return 64L; }
static int Ft_Esd_SpinBox_LayoutSplit_Denominator__Property(void *context) { return 128L; }
static int Ft_Esd_SpinBox_LayoutSplit_Margin__Property(void *context) { return 2L; }
static int Ft_Esd_SpinBox_LayoutMargin_X__Property(void *context);
static int Ft_Esd_SpinBox_LayoutMargin_Y__Property(void *context);
static int Ft_Esd_SpinBox_LayoutMargin_Width__Property(void *context);
static int Ft_Esd_SpinBox_LayoutMargin_Height__Property(void *context);
static int Ft_Esd_SpinBox_LayoutMargin_Margin__Property(void *context) { return 3L; }
static int Ft_Esd_SpinBox_LayoutSplit_1_Pos__Property(void *context);
static int Ft_Esd_SpinBox_LayoutSplit_1_Length__Property(void *context);
static int Ft_Esd_SpinBox_LayoutSplit_1_Numerator__Property(void *context) { return 6L; }
static int Ft_Esd_SpinBox_LayoutSplit_1_Denominator__Property(void *context) { return 7L; }
static int Ft_Esd_SpinBox_LayoutSplit_1_Margin__Property(void *context) { return 2L; }
static ft_int16_t Ft_Esd_SpinBox_Push_Up_X__Property(void *context);
static ft_int16_t Ft_Esd_SpinBox_Push_Up_Y__Property(void *context);
static ft_int16_t Ft_Esd_SpinBox_Push_Up_Width__Property(void *context);
static ft_int16_t Ft_Esd_SpinBox_Push_Up_Height__Property(void *context);
static ft_int16_t Ft_Esd_SpinBox_Push_Up_Font__Property(void *context) { return 18; }
static const char * Ft_Esd_SpinBox_Push_Up_Text__Property(void *context);
static ft_int16_t Ft_Esd_SpinBox_Push_Down_X__Property(void *context);
static ft_int16_t Ft_Esd_SpinBox_Push_Down_Y__Property(void *context);
static ft_int16_t Ft_Esd_SpinBox_Push_Down_Width__Property(void *context);
static ft_int16_t Ft_Esd_SpinBox_Push_Down_Height__Property(void *context);
static ft_int16_t Ft_Esd_SpinBox_Push_Down_Font__Property(void *context) { return 18; }
static const char * Ft_Esd_SpinBox_Push_Down_Text__Property(void *context);

static void Ft_Esd_SpinBox_Push_Up_Down__Signal(void *context);
static void Ft_Esd_SpinBox_Push_Down_Down__Signal(void *context);

void Ft_Esd_SpinBox__Initializer(Ft_Esd_SpinBox *context)
{
	context->Parent = 0;
	context->Theme = Ft_Esd_SpinBox_Theme__Default;
	Ft_Esd_TouchTag__Initializer(&context->Touch_Tag);
	context->Touch_Tag.Parent = context;
	context->X = Ft_Esd_SpinBox_X__Default;
	context->Y = Ft_Esd_SpinBox_Y__Default;
	context->Width = Ft_Esd_SpinBox_Width__Default;
	context->Height = Ft_Esd_SpinBox_Height__Default;
	context->Step = Ft_Esd_SpinBox_Step__Default;
	context->Increased = Ft_Esd_Noop;
	context->Value = 0L;
	context->Changed = Ft_Esd_SpinBox_Changed__Noop;
	LayoutSplit__Initializer(&context->LayoutSplit);
	context->LayoutSplit.Parent = context;
	context->LayoutSplit.Pos = Ft_Esd_SpinBox_LayoutSplit_Pos__Property;
	context->LayoutSplit.Length = Ft_Esd_SpinBox_LayoutSplit_Length__Property;
	context->LayoutSplit.Numerator = Ft_Esd_SpinBox_LayoutSplit_Numerator__Property;
	context->LayoutSplit.Denominator = Ft_Esd_SpinBox_LayoutSplit_Denominator__Property;
	context->LayoutSplit.Margin = Ft_Esd_SpinBox_LayoutSplit_Margin__Property;
	context->Decreased = Ft_Esd_Noop;
	LayoutMargin__Initializer(&context->LayoutMargin);
	context->LayoutMargin.Parent = context;
	context->LayoutMargin.X = Ft_Esd_SpinBox_LayoutMargin_X__Property;
	context->LayoutMargin.Y = Ft_Esd_SpinBox_LayoutMargin_Y__Property;
	context->LayoutMargin.Width = Ft_Esd_SpinBox_LayoutMargin_Width__Property;
	context->LayoutMargin.Height = Ft_Esd_SpinBox_LayoutMargin_Height__Property;
	context->LayoutMargin.Margin = Ft_Esd_SpinBox_LayoutMargin_Margin__Property;
	LayoutSplit__Initializer(&context->LayoutSplit_1);
	context->LayoutSplit_1.Parent = context;
	context->LayoutSplit_1.Pos = Ft_Esd_SpinBox_LayoutSplit_1_Pos__Property;
	context->LayoutSplit_1.Length = Ft_Esd_SpinBox_LayoutSplit_1_Length__Property;
	context->LayoutSplit_1.Numerator = Ft_Esd_SpinBox_LayoutSplit_1_Numerator__Property;
	context->LayoutSplit_1.Denominator = Ft_Esd_SpinBox_LayoutSplit_1_Denominator__Property;
	context->LayoutSplit_1.Margin = Ft_Esd_SpinBox_LayoutSplit_1_Margin__Property;
	context->SideButtons = 0;
	Ft_Esd_PushButton__Initializer(&context->Push_Up);
	context->Push_Up.Parent = context;
	context->Push_Up.X = Ft_Esd_SpinBox_Push_Up_X__Property;
	context->Push_Up.Y = Ft_Esd_SpinBox_Push_Up_Y__Property;
	context->Push_Up.Width = Ft_Esd_SpinBox_Push_Up_Width__Property;
	context->Push_Up.Height = Ft_Esd_SpinBox_Push_Up_Height__Property;
	context->Push_Up.Font = Ft_Esd_SpinBox_Push_Up_Font__Property;
	context->Push_Up.Text = Ft_Esd_SpinBox_Push_Up_Text__Property;
	context->Push_Up.Down = Ft_Esd_SpinBox_Push_Up_Down__Signal;
	Ft_Esd_PushButton__Initializer(&context->Push_Down);
	context->Push_Down.Parent = context;
	context->Push_Down.X = Ft_Esd_SpinBox_Push_Down_X__Property;
	context->Push_Down.Y = Ft_Esd_SpinBox_Push_Down_Y__Property;
	context->Push_Down.Width = Ft_Esd_SpinBox_Push_Down_Width__Property;
	context->Push_Down.Height = Ft_Esd_SpinBox_Push_Down_Height__Property;
	context->Push_Down.Font = Ft_Esd_SpinBox_Push_Down_Font__Property;
	context->Push_Down.Text = Ft_Esd_SpinBox_Push_Down_Text__Property;
	context->Push_Down.Down = Ft_Esd_SpinBox_Push_Down_Down__Signal;
}

void Ft_Esd_Elements_Panel(Ft_Esd_Theme *, ft_int16_t, ft_int16_t, ft_int16_t, ft_int16_t, ft_int16_t, ft_bool_t);
ft_void_t Ft_Gpu_CoCmd_Number(Ft_Gpu_Hal_Context_t *, ft_int16_t, ft_int16_t, ft_int16_t, ft_uint16_t, ft_int32_t);

void Ft_Esd_SpinBox_Start(Ft_Esd_SpinBox *context)
{
	void *parent = context->Parent;
	Ft_Esd_TouchTag_Start(&context->Touch_Tag);
	Ft_Esd_PushButton_Start(&context->Push_Up);
	Ft_Esd_PushButton_Start(&context->Push_Down);
}

void Ft_Esd_SpinBox_Render(Ft_Esd_SpinBox *context)
{
	void *parent = context->Parent;
	ft_uint8_t s = Ft_Esd_TouchTag_Tag(&context->Touch_Tag);
	Ft_Esd_Dl_TAG(s);
	ft_uint8_t alpha = 255;
	Ft_Esd_Dl_COLOR_A(alpha);
	Ft_Esd_Theme * theme = context->Theme(parent);
	ft_int16_t x = context->X(parent);
	ft_int16_t y = context->Y(parent);
	ft_int16_t width = context->Width(parent);
	ft_int16_t height = context->Height(parent);
	ft_int16_t radius = 4;
	ft_bool_t raised = 0;
	Ft_Esd_Elements_Panel(theme, x, y, width, height, radius, raised);
	ft_bool_t if_1 = Ft_Esd_TouchTag_Touching(&context->Touch_Tag);
	ft_rgb32_t c;
	if (if_1)
	{
		Ft_Esd_Theme * theme_1 = context->Theme(parent);
		c = Ft_Esd_Theme_GetPrimaryColor(theme_1);
	}
	else
	{
		Ft_Esd_Theme * theme_2 = context->Theme(parent);
		c = Ft_Esd_Theme_GetTextColor(theme_2);
	}
	Ft_Esd_Dl_COLOR_RGB(c);
	Ft_Gpu_Hal_Context_t * phost = Ft_Esd_GetHost();
	int left_1 = LayoutSplit_FirstLength(&context->LayoutSplit_1);
	int right = LayoutSplit_FirstPos(&context->LayoutSplit_1);
	int left = left_1 + right;
	int right_1 = 8L;
	int x_1 = left - right_1;
	ft_int16_t left_2 = context->Y(parent);
	ft_int16_t left_3 = context->Height(parent);
	int right_3 = 2L;
	int right_2 = left_3 / right_3;
	int y_1 = left_2 + right_2;
	ft_int16_t font = 31;
	ft_uint16_t left_5 = OPT_CENTERY;
	ft_uint16_t right_4 = OPT_RIGHTX;
	ft_uint16_t left_4 = left_5 | right_4;
	ft_uint16_t right_5 = OPT_SIGNED;
	ft_uint16_t options = left_4 | right_5;
	int n = context->Value;
	Ft_Gpu_CoCmd_Number(phost, x_1, y_1, font, options, n);
	Ft_Esd_PushButton_Render(&context->Push_Up);
	Ft_Esd_PushButton_Render(&context->Push_Down);
}

void Ft_Esd_SpinBox_Update(Ft_Esd_SpinBox *context)
{
	void *parent = context->Parent;
	Ft_Esd_TouchTag_Update(&context->Touch_Tag);
	Ft_Esd_PushButton_Update(&context->Push_Up);
	Ft_Esd_PushButton_Update(&context->Push_Down);
}

void Ft_Esd_SpinBox_End(Ft_Esd_SpinBox *context)
{
	void *parent = context->Parent;
	Ft_Esd_TouchTag_End(&context->Touch_Tag);
	Ft_Esd_PushButton_End(&context->Push_Up);
	Ft_Esd_PushButton_End(&context->Push_Down);
}

int Ft_Esd_SpinBox_LayoutSplit_Pos__Property(void *c)
{
	Ft_Esd_SpinBox *context = (Ft_Esd_SpinBox *)c;
	void *parent = context->Parent;
	return LayoutMargin_OutY(&context->LayoutMargin);
}

int Ft_Esd_SpinBox_LayoutSplit_Length__Property(void *c)
{
	Ft_Esd_SpinBox *context = (Ft_Esd_SpinBox *)c;
	void *parent = context->Parent;
	return LayoutMargin_OutHeight(&context->LayoutMargin);
}

int Ft_Esd_SpinBox_LayoutMargin_X__Property(void *c)
{
	Ft_Esd_SpinBox *context = (Ft_Esd_SpinBox *)c;
	void *parent = context->Parent;
	return context->X(parent);
}

int Ft_Esd_SpinBox_LayoutMargin_Y__Property(void *c)
{
	Ft_Esd_SpinBox *context = (Ft_Esd_SpinBox *)c;
	void *parent = context->Parent;
	return context->Y(parent);
}

int Ft_Esd_SpinBox_LayoutMargin_Width__Property(void *c)
{
	Ft_Esd_SpinBox *context = (Ft_Esd_SpinBox *)c;
	void *parent = context->Parent;
	ft_int16_t left_6 = context->Width(parent);
	ft_int16_t right_6 = 1;
	return left_6 - right_6;
}

int Ft_Esd_SpinBox_LayoutMargin_Height__Property(void *c)
{
	Ft_Esd_SpinBox *context = (Ft_Esd_SpinBox *)c;
	void *parent = context->Parent;
	ft_int16_t left_7 = context->Height(parent);
	ft_int16_t right_7 = 1;
	return left_7 - right_7;
}

void Ft_Esd_SpinBox_Increase(Ft_Esd_SpinBox *context)
{
	void *parent = context->Parent;
	int left_8 = context->Value;
	int right_8 = context->Step(parent);
	int increase_value = left_8 + right_8;
	context->Value = increase_value;
	context->Changed(parent, increase_value);
	context->Increased(parent);
}

int Ft_Esd_SpinBox_LayoutSplit_1_Pos__Property(void *c)
{
	Ft_Esd_SpinBox *context = (Ft_Esd_SpinBox *)c;
	void *parent = context->Parent;
	return LayoutMargin_OutX(&context->LayoutMargin);
}

int Ft_Esd_SpinBox_LayoutSplit_1_Length__Property(void *c)
{
	Ft_Esd_SpinBox *context = (Ft_Esd_SpinBox *)c;
	void *parent = context->Parent;
	return LayoutMargin_OutWidth(&context->LayoutMargin);
}

void Ft_Esd_SpinBox_Decrease(Ft_Esd_SpinBox *context)
{
	void *parent = context->Parent;
	int left_9 = context->Value;
	int right_9 = context->Step(parent);
	int decrease_value = left_9 - right_9;
	context->Value = decrease_value;
	context->Changed(parent, decrease_value);
	context->Decreased(parent);
}

ft_int16_t Ft_Esd_SpinBox_Push_Up_X__Property(void *c)
{
	Ft_Esd_SpinBox *context = (Ft_Esd_SpinBox *)c;
	void *parent = context->Parent;
	return LayoutSplit_SecondPos(&context->LayoutSplit_1);
}

ft_int16_t Ft_Esd_SpinBox_Push_Up_Y__Property(void *c)
{
	Ft_Esd_SpinBox *context = (Ft_Esd_SpinBox *)c;
	void *parent = context->Parent;
	return LayoutSplit_FirstPos(&context->LayoutSplit);
}

ft_int16_t Ft_Esd_SpinBox_Push_Up_Width__Property(void *c)
{
	Ft_Esd_SpinBox *context = (Ft_Esd_SpinBox *)c;
	void *parent = context->Parent;
	return LayoutSplit_SecondLength(&context->LayoutSplit_1);
}

ft_int16_t Ft_Esd_SpinBox_Push_Up_Height__Property(void *c)
{
	Ft_Esd_SpinBox *context = (Ft_Esd_SpinBox *)c;
	void *parent = context->Parent;
	ft_bool_t if_2 = context->SideButtons;
	if (if_2)
	{
		int left_10 = LayoutMargin_OutHeight(&context->LayoutMargin);
		int right_10 = 1L;
		return left_10 + right_10;
	}
	else
	{
		return LayoutSplit_FirstLength(&context->LayoutSplit);
	}
}

const char * Ft_Esd_SpinBox_Push_Up_Text__Property(void *c)
{
	Ft_Esd_SpinBox *context = (Ft_Esd_SpinBox *)c;
	void *parent = context->Parent;
	return Ft_Esd_Char_UpTriangle();
}

void Ft_Esd_SpinBox_Push_Up_Down__Signal(void *c)
{
	Ft_Esd_SpinBox *context = (Ft_Esd_SpinBox *)c;
	void *parent = context->Parent;
	int left_11 = context->Value;
	int right_11 = context->Step(parent);
	int increase_value_1 = left_11 + right_11;
	context->Value = increase_value_1;
	context->Changed(parent, increase_value_1);
	context->Increased(parent);
}

ft_int16_t Ft_Esd_SpinBox_Push_Down_X__Property(void *c)
{
	Ft_Esd_SpinBox *context = (Ft_Esd_SpinBox *)c;
	void *parent = context->Parent;
	ft_bool_t if_3 = context->SideButtons;
	if (if_3)
	{
		return LayoutMargin_OutX(&context->LayoutMargin);
	}
	else
	{
		return LayoutSplit_SecondPos(&context->LayoutSplit_1);
	}
}

ft_int16_t Ft_Esd_SpinBox_Push_Down_Y__Property(void *c)
{
	Ft_Esd_SpinBox *context = (Ft_Esd_SpinBox *)c;
	void *parent = context->Parent;
	ft_bool_t if_4 = context->SideButtons;
	if (if_4)
	{
		return LayoutSplit_FirstPos(&context->LayoutSplit);
	}
	else
	{
		return LayoutSplit_SecondPos(&context->LayoutSplit);
	}
}

ft_int16_t Ft_Esd_SpinBox_Push_Down_Width__Property(void *c)
{
	Ft_Esd_SpinBox *context = (Ft_Esd_SpinBox *)c;
	void *parent = context->Parent;
	return LayoutSplit_SecondLength(&context->LayoutSplit_1);
}

ft_int16_t Ft_Esd_SpinBox_Push_Down_Height__Property(void *c)
{
	Ft_Esd_SpinBox *context = (Ft_Esd_SpinBox *)c;
	void *parent = context->Parent;
	ft_bool_t if_5 = context->SideButtons;
	if (if_5)
	{
		int left_12 = LayoutMargin_OutHeight(&context->LayoutMargin);
		int right_12 = 1L;
		return left_12 + right_12;
	}
	else
	{
		return LayoutSplit_SecondLength(&context->LayoutSplit);
	}
}

const char * Ft_Esd_SpinBox_Push_Down_Text__Property(void *c)
{
	Ft_Esd_SpinBox *context = (Ft_Esd_SpinBox *)c;
	void *parent = context->Parent;
	return Ft_Esd_Char_DownTriangle();
}

void Ft_Esd_SpinBox_Push_Down_Down__Signal(void *c)
{
	Ft_Esd_SpinBox *context = (Ft_Esd_SpinBox *)c;
	void *parent = context->Parent;
	int left_13 = context->Value;
	int right_13 = context->Step(parent);
	int decrease_value_1 = left_13 - right_13;
	context->Value = decrease_value_1;
	context->Changed(parent, decrease_value_1);
	context->Decreased(parent);
}

#ifdef ESD_SIMULATION
#include <stdlib.h>

typedef struct
{
	Ft_Esd_SpinBox Instance;
	Ft_Esd_Theme * Theme;
	ft_int16_t X;
	ft_int16_t Y;
	ft_int16_t Width;
	ft_int16_t Height;
	int Step;
} Ft_Esd_SpinBox__ESD;

Ft_Esd_Theme * Ft_Esd_SpinBox__Get_Theme__ESD(void *context) { return ((Ft_Esd_SpinBox__ESD *)context)->Theme; }
void Ft_Esd_SpinBox__Set_Theme__ESD(void *context, Ft_Esd_Theme * value) { ((Ft_Esd_SpinBox__ESD *)context)->Theme = value; }
ft_int16_t Ft_Esd_SpinBox__Get_X__ESD(void *context) { return ((Ft_Esd_SpinBox__ESD *)context)->X; }
void Ft_Esd_SpinBox__Set_X__ESD(void *context, ft_int16_t value) { ((Ft_Esd_SpinBox__ESD *)context)->X = value; }
ft_int16_t Ft_Esd_SpinBox__Get_Y__ESD(void *context) { return ((Ft_Esd_SpinBox__ESD *)context)->Y; }
void Ft_Esd_SpinBox__Set_Y__ESD(void *context, ft_int16_t value) { ((Ft_Esd_SpinBox__ESD *)context)->Y = value; }
ft_int16_t Ft_Esd_SpinBox__Get_Width__ESD(void *context) { return ((Ft_Esd_SpinBox__ESD *)context)->Width; }
void Ft_Esd_SpinBox__Set_Width__ESD(void *context, ft_int16_t value) { ((Ft_Esd_SpinBox__ESD *)context)->Width = value; }
ft_int16_t Ft_Esd_SpinBox__Get_Height__ESD(void *context) { return ((Ft_Esd_SpinBox__ESD *)context)->Height; }
void Ft_Esd_SpinBox__Set_Height__ESD(void *context, ft_int16_t value) { ((Ft_Esd_SpinBox__ESD *)context)->Height = value; }
int Ft_Esd_SpinBox__Get_Step__ESD(void *context) { return ((Ft_Esd_SpinBox__ESD *)context)->Step; }
void Ft_Esd_SpinBox__Set_Step__ESD(void *context, int value) { ((Ft_Esd_SpinBox__ESD *)context)->Step = value; }

void *Ft_Esd_SpinBox__Create__ESD()
{
	Ft_Esd_SpinBox__ESD *context = (Ft_Esd_SpinBox__ESD *)malloc(sizeof(Ft_Esd_SpinBox__ESD));
	Ft_Esd_SpinBox__Initializer(&context->Instance);
	context->Instance.Parent = context;
	context->Theme = Ft_Esd_Theme_GetCurrent();
	context->Instance.Theme = Ft_Esd_SpinBox__Get_Theme__ESD;
	context->X = 50;
	context->Instance.X = Ft_Esd_SpinBox__Get_X__ESD;
	context->Y = 50;
	context->Instance.Y = Ft_Esd_SpinBox__Get_Y__ESD;
	context->Width = 240;
	context->Instance.Width = Ft_Esd_SpinBox__Get_Width__ESD;
	context->Height = 72;
	context->Instance.Height = Ft_Esd_SpinBox__Get_Height__ESD;
	context->Step = 1L;
	context->Instance.Step = Ft_Esd_SpinBox__Get_Step__ESD;
	return context;
}

void Ft_Esd_SpinBox__Destroy__ESD(void *context)
{
	free(context);
}

void Ft_Esd_SpinBox__Set_Value__ESD(void *context, int value) { ((Ft_Esd_SpinBox__ESD *)context)->Instance.Value = value; }
void Ft_Esd_SpinBox__Set_SideButtons__ESD(void *context, ft_bool_t value) { ((Ft_Esd_SpinBox__ESD *)context)->Instance.SideButtons = value; }

#endif /* ESD_SIMULATION */

/* end of file */
