/*
This file is automatically generated
App
C Source
*/

#include "App.h"

#include "stdlib.h"

extern void Ft_Esd_Noop(void *context);
extern void Ft_Esd_Spinner_Popup();



#define YesPage__ID 1
#define Main_Page__ID 2
#define NoPage__ID 3

void App__Initializer(App *context)
{
	context->Parent = 0;
	context->_ActivePage = 0;
	context->YesPage = 0;
	context->YesPage__Active = 0;
	context->Main_Page = 0;
	context->Main_Page__Active = 0;
	context->NoPage = 0;
	context->NoPage__Active = 0;
}

static void App__YesPage__Validate(App *context)
{
	void *parent = context->Parent;
	if (!context->YesPage)
	{
		context->YesPage = (YesPage *)malloc(sizeof(YesPage));
		YesPage__Initializer(context->YesPage);
		context->YesPage->Parent = context;
		YesPage_Start(context->YesPage);
	}
}

static void App__YesPage__Create(App *context)
{
	App__YesPage__Validate(context);
	context->YesPage__Active = 1;
}

static void App__YesPage__Destroy(App *context, int final)
{
	if (context->YesPage__Active)
	{
		context->YesPage__Active = 0;
	}
	if (final && context->YesPage)
	{
		YesPage_End(context->YesPage);
		free(context->YesPage);
		context->YesPage = 0;
	}
}

static void App__Main_Page__Validate(App *context)
{
	void *parent = context->Parent;
	if (!context->Main_Page)
	{
		context->Main_Page = (MainPage *)malloc(sizeof(MainPage));
		MainPage__Initializer(context->Main_Page);
		context->Main_Page->Parent = context;
		MainPage_Start(context->Main_Page);
	}
}

static void App__Main_Page__Create(App *context)
{
	App__Main_Page__Validate(context);
	context->Main_Page__Active = 1;
}

static void App__Main_Page__Destroy(App *context, int final)
{
	if (context->Main_Page__Active)
	{
		context->Main_Page__Active = 0;
	}
	if (context->Main_Page)
	{
		MainPage_End(context->Main_Page);
		free(context->Main_Page);
		context->Main_Page = 0;
	}
}

static void App__NoPage__Validate(App *context)
{
	void *parent = context->Parent;
	if (!context->NoPage)
	{
		context->NoPage = (NoPage *)malloc(sizeof(NoPage));
		NoPage__Initializer(context->NoPage);
		context->NoPage->Parent = context;
		NoPage_Start(context->NoPage);
	}
}

static void App__NoPage__Create(App *context)
{
	App__NoPage__Validate(context);
	context->NoPage__Active = 1;
}

static void App__NoPage__Destroy(App *context, int final)
{
	if (context->NoPage__Active)
	{
		context->NoPage__Active = 0;
	}
	if (final && context->NoPage)
	{
		NoPage_End(context->NoPage);
		free(context->NoPage);
		context->NoPage = 0;
	}
}

static int App_YesPage__active(App *context);
static int App_NoPage__active(App *context);

void App_Start(App *context)
{
	void *parent = context->Parent;
	if ((!!App_YesPage__active(context)))
		App__YesPage__Create(context);
	App__Main_Page__Create(context);
	if ((!!App_NoPage__active(context)))
		App__NoPage__Create(context);
}

void App_Update(App *context)
{
	void *parent = context->Parent;
	if ((!!context->YesPage__Active) != ((!!App_YesPage__active(context))))
	{
		if (!context->YesPage__Active)
			App__YesPage__Create(context);
		else
			App__YesPage__Destroy(context, 0);
	}
	if ((!!context->NoPage__Active) != ((!!App_NoPage__active(context))))
	{
		if (!context->NoPage__Active)
			App__NoPage__Create(context);
		else
			App__NoPage__Destroy(context, 0);
	}
	if (context->YesPage__Active)
		YesPage_Update(context->YesPage);
	MainPage_Update(context->Main_Page);
	if (context->NoPage__Active)
		NoPage_Update(context->NoPage);
	if (!context->YesPage__Active && (((!!App_YesPage__active(context)))))
	{
		Ft_Esd_Spinner_Popup();
	}
	if (!context->NoPage__Active && (((!!App_NoPage__active(context)))))
	{
		Ft_Esd_Spinner_Popup();
	}
}

void App_Render(App *context)
{
	void *parent = context->Parent;
	if (context->YesPage__Active)
		YesPage_Render(context->YesPage);
	MainPage_Render(context->Main_Page);
	if (context->NoPage__Active)
		NoPage_Render(context->NoPage);
}

void App_Idle(App *context)
{
	void *parent = context->Parent;
	if (context->YesPage__Active)
		YesPage_Idle(context->YesPage);
	MainPage_Idle(context->Main_Page);
	if (context->NoPage__Active)
		NoPage_Idle(context->NoPage);
}

void App_End(App *context)
{
	void *parent = context->Parent;
	if (context->YesPage__Active)
		App__YesPage__Destroy(context, 1);
	App__Main_Page__Destroy(context, 1);
	if (context->NoPage__Active)
		App__NoPage__Destroy(context, 1);
}

int App_YesPage__active(App *context)
{
	void *parent = context->Parent;
	return (context->Main_Page ? (context->Main_Page->YesPushed) : (0));
}

int App_NoPage__active(App *context)
{
	void *parent = context->Parent;
	return (context->Main_Page ? (context->Main_Page->NoPushed) : (0));
}

static App application;

void Ft_Main__Start()
{
	App__Initializer(&application);
	App_Start(&application);
}

void Ft_Main__Update()
{
	App_Update(&application);
}

void Ft_Main__Render()
{
	App_Render(&application);
}

void Ft_Main__Idle()
{
	App_Idle(&application);
}

void Ft_Main__End()
{
	App_End(&application);
}

#ifdef ESD_SIMULATION
#include <stdlib.h>

typedef struct
{
	App Instance;
} App__ESD;


void *App__Create__ESD()
{
	App__ESD *context = (App__ESD *)malloc(sizeof(App__ESD));
	App__Initializer(&context->Instance);
	context->Instance.Parent = context;
	return context;
}

void App__Destroy__ESD(void *context)
{
	free(context);
}


#endif /* ESD_SIMULATION */

/* end of file */
