/*
This file is automatically generated
NoPage
C Source
*/

#include "NoPage.h"

extern void Ft_Esd_Noop(void *context);

Ft_Esd_Theme * Ft_Esd_Theme_GetCurrent();
static ft_int16_t NoPage_Parking_Spot_Finder_Font__Property(void *context) { return 31; }
static const char * NoPage_Parking_Spot_Finder_Text__Property(void *context) { return "Parking Spot Finder"; }
static ft_int16_t NoPage_Parking_Spot_Finder_X__Property(void *context) { return 6; }
static ft_int16_t NoPage_Parking_Spot_Finder_Width__Property(void *context) { return 297; }
static const char * NoPage_ESD_Label_Text__Property(void *context) { return "Parking ID:"; }
static ft_int16_t NoPage_ESD_Label_X__Property(void *context) { return 196; }
static ft_int16_t NoPage_ESD_Label_Y__Property(void *context) { return 214; }
static ft_uint16_t NoPage_ESD_Label_AlignX__Property(void *context) { return OPT_ALIGN_CENTER; }
static ft_uint16_t NoPage_ESD_Label_AlignY__Property(void *context) { return OPT_ALIGN_CENTER; }
static ft_int16_t NoPage_ESD_Numeric_Label_X__Property(void *context) { return 492; }
static ft_int16_t NoPage_ESD_Numeric_Label_Y__Property(void *context) { return 214; }
static ft_int32_t NoPage_ESD_Numeric_Label_Value__Property(void *context) { return 45L; }


void NoPage__Initializer(NoPage *context)
{
	context->Parent = 0;
	Ft_Esd_Label__Initializer(&context->Parking_Spot_Finder);
	context->Parking_Spot_Finder.Parent = context;
	context->Parking_Spot_Finder.Font = NoPage_Parking_Spot_Finder_Font__Property;
	context->Parking_Spot_Finder.Text = NoPage_Parking_Spot_Finder_Text__Property;
	context->Parking_Spot_Finder.X = NoPage_Parking_Spot_Finder_X__Property;
	context->Parking_Spot_Finder.Width = NoPage_Parking_Spot_Finder_Width__Property;
	Ft_Esd_Label__Initializer(&context->ESD_Label);
	context->ESD_Label.Parent = context;
	context->ESD_Label.Text = NoPage_ESD_Label_Text__Property;
	context->ESD_Label.X = NoPage_ESD_Label_X__Property;
	context->ESD_Label.Y = NoPage_ESD_Label_Y__Property;
	context->ESD_Label.AlignX = NoPage_ESD_Label_AlignX__Property;
	context->ESD_Label.AlignY = NoPage_ESD_Label_AlignY__Property;
	Ft_Esd_NumericLabel__Initializer(&context->ESD_Numeric_Label);
	context->ESD_Numeric_Label.Parent = context;
	context->ESD_Numeric_Label.X = NoPage_ESD_Numeric_Label_X__Property;
	context->ESD_Numeric_Label.Y = NoPage_ESD_Numeric_Label_Y__Property;
	context->ESD_Numeric_Label.Value = NoPage_ESD_Numeric_Label_Value__Property;
}

void NoPage_Start(NoPage *context)
{
	void *parent = context->Parent;
}

void NoPage_Update(NoPage *context)
{
	void *parent = context->Parent;
}

void NoPage_Render(NoPage *context)
{
	void *parent = context->Parent;
	Ft_Esd_Label_Render(&context->Parking_Spot_Finder);
	Ft_Esd_Label_Render(&context->ESD_Label);
	Ft_Esd_NumericLabel_Render(&context->ESD_Numeric_Label);
}

void NoPage_Idle(NoPage *context)
{
	void *parent = context->Parent;
}

void NoPage_End(NoPage *context)
{
	void *parent = context->Parent;
}

#ifdef ESD_SIMULATION
#include <stdlib.h>

typedef struct
{
	NoPage Instance;
} NoPage__ESD;


void *NoPage__Create__ESD()
{
	NoPage__ESD *context = (NoPage__ESD *)malloc(sizeof(NoPage__ESD));
	NoPage__Initializer(&context->Instance);
	context->Instance.Parent = context;
	return context;
}

void NoPage__Destroy__ESD(void *context)
{
	free(context);
}


#endif /* ESD_SIMULATION */

/* end of file */
