/*
This file is automatically generated
YesPage
Header
*/

#ifndef YesPage__H
#define YesPage__H

#include "Ft_Esd.h"
#include "Ft_Esd_Label.h"
#include "Ft_Esd_Theme.h"

#ifndef ESD_LOGIC
#define ESD_LOGIC(name, ...)
#define ESD_ACTOR(name, ...)
#define ESD_WIDGET(name, ...)
#define ESD_PAGE(name, ...)
#define ESD_APPLICATION(name, ...)
#define ESD_INPUT(name, ...)
#define ESD_OUTPUT(name, ...)
#define ESD_SLOT(name, ...)
#define ESD_SIGNAL(name, ...)
#define ESD_VARIABLE(name, ...)
#define ESD_WRITER(name, ...)
#endif

ESD_PAGE(YesPage, Include = "YesPage.h", Callback)
typedef struct
{
	void *Parent;
	ESD_SIGNAL(OkClicked)
	void(* OkClicked)(void *context);
	Ft_Esd_Label Parking_Spot_Finder;
	Ft_Esd_Label ESD_Label;
} YesPage;

void YesPage__Initializer(YesPage *context);

ESD_SLOT(Start)
void YesPage_Start(YesPage *context);

ESD_SLOT(Update)
void YesPage_Update(YesPage *context);

ESD_SLOT(Render)
void YesPage_Render(YesPage *context);

ESD_SLOT(Idle)
void YesPage_Idle(YesPage *context);

ESD_SLOT(End)
void YesPage_End(YesPage *context);

#endif /* YesPage__H */

/* end of file */
