/*
This file is automatically generated
YesPage
C Source
*/

#include "YesPage.h"

extern void Ft_Esd_Noop(void *context);

Ft_Esd_Theme * Ft_Esd_Theme_GetCurrent();
static ft_int16_t YesPage_Parking_Spot_Finder_Font__Property(void *context) { return 31; }
static const char * YesPage_Parking_Spot_Finder_Text__Property(void *context) { return "Parking Spot Finder"; }
static ft_int16_t YesPage_Parking_Spot_Finder_X__Property(void *context) { return 6; }
static ft_int16_t YesPage_Parking_Spot_Finder_Width__Property(void *context) { return 297; }
static ft_int16_t YesPage_ESD_Label_Font__Property(void *context) { return 30; }
static const char * YesPage_ESD_Label_Text__Property(void *context) { return "Enjoy Parking!"; }
static ft_int16_t YesPage_ESD_Label_X__Property(void *context) { return 297; }
static ft_int16_t YesPage_ESD_Label_Y__Property(void *context) { return 182; }
static ft_int16_t YesPage_ESD_Label_Width__Property(void *context) { return 199; }
static ft_int16_t YesPage_ESD_Label_Height__Property(void *context) { return 43; }


void YesPage__Initializer(YesPage *context)
{
	context->Parent = 0;
	context->OkClicked = Ft_Esd_Noop;
	Ft_Esd_Label__Initializer(&context->Parking_Spot_Finder);
	context->Parking_Spot_Finder.Parent = context;
	context->Parking_Spot_Finder.Font = YesPage_Parking_Spot_Finder_Font__Property;
	context->Parking_Spot_Finder.Text = YesPage_Parking_Spot_Finder_Text__Property;
	context->Parking_Spot_Finder.X = YesPage_Parking_Spot_Finder_X__Property;
	context->Parking_Spot_Finder.Width = YesPage_Parking_Spot_Finder_Width__Property;
	Ft_Esd_Label__Initializer(&context->ESD_Label);
	context->ESD_Label.Parent = context;
	context->ESD_Label.Font = YesPage_ESD_Label_Font__Property;
	context->ESD_Label.Text = YesPage_ESD_Label_Text__Property;
	context->ESD_Label.X = YesPage_ESD_Label_X__Property;
	context->ESD_Label.Y = YesPage_ESD_Label_Y__Property;
	context->ESD_Label.Width = YesPage_ESD_Label_Width__Property;
	context->ESD_Label.Height = YesPage_ESD_Label_Height__Property;
}

void YesPage_Start(YesPage *context)
{
	void *parent = context->Parent;
}

void YesPage_Update(YesPage *context)
{
	void *parent = context->Parent;
}

void YesPage_Render(YesPage *context)
{
	void *parent = context->Parent;
	Ft_Esd_Label_Render(&context->Parking_Spot_Finder);
	Ft_Esd_Label_Render(&context->ESD_Label);
}

void YesPage_Idle(YesPage *context)
{
	void *parent = context->Parent;
}

void YesPage_End(YesPage *context)
{
	void *parent = context->Parent;
}

#ifdef ESD_SIMULATION
#include <stdlib.h>

typedef struct
{
	YesPage Instance;
} YesPage__ESD;


void *YesPage__Create__ESD()
{
	YesPage__ESD *context = (YesPage__ESD *)malloc(sizeof(YesPage__ESD));
	YesPage__Initializer(&context->Instance);
	context->Instance.Parent = context;
	return context;
}

void YesPage__Destroy__ESD(void *context)
{
	free(context);
}


#endif /* ESD_SIMULATION */

/* end of file */
