/*
This file is automatically generated
DO NOT MODIFY BY HAND
Ft_Esd_FixedPointNumericLabel
C Source
*/

#include "Ft_Esd_FixedPointNumericLabel.h"

#include "FT_Esd_Dl.h"
#include "Ft_Esd_CoCmd.h"

extern void Ft_Esd_Noop(void *context);
Ft_Esd_Theme * Ft_Esd_FixedPointNumericLabel_Theme__Default(void *context) { return Ft_Esd_Theme_GetCurrent(); }
ft_int16_t Ft_Esd_FixedPointNumericLabel_Font__Default(void *context) { return 27; }
ft_uint16_t Ft_Esd_FixedPointNumericLabel_AlignX__Default(void *context) { return OPT_ALIGN_LEFT; }
ft_uint16_t Ft_Esd_FixedPointNumericLabel_AlignY__Default(void *context) { return OPT_ALIGN_CENTER; }
ft_uint8_t Ft_Esd_FixedPointNumericLabel_AutoResize__Default(void *context) { return ESD_AUTORESIZE_HEIGHT; }
float Ft_Esd_FixedPointNumericLabel_Value__Default(void *context) { return 0.0f; }
ft_bool_t Ft_Esd_FixedPointNumericLabel_EnablePadding__Default(void *context) { return 0; }
ft_int32_t Ft_Esd_FixedPointNumericLabel_NoOfDigits__Default(void *context) { return 7L; }
int Ft_Esd_FixedPointNumericLabel_NoOfDigitsAfterDot__Default(void *context) { return 6L; }
ft_bool_t Ft_Esd_FixedPointNumericLabel_IsZeroLeading__Default(void *context) { return 0; }


static Ft_Esd_WidgetSlots s_Ft_Esd_FixedPointNumericLabel__Slots = {
	(void(*)(void *))Ft_Esd_Widget_Initialize,
	(void(*)(void *))Ft_Esd_FixedPointNumericLabel_Start,
	(void(*)(void *))Ft_Esd_Widget_Enable,
	(void(*)(void *))Ft_Esd_FixedPointNumericLabel_Update,
	(void(*)(void *))Ft_Esd_FixedPointNumericLabel_Render,
	(void(*)(void *))Ft_Esd_Widget_Idle,
	(void(*)(void *))Ft_Esd_Widget_Disable,
	(void(*)(void *))Ft_Esd_FixedPointNumericLabel_End,
};


void Ft_Esd_FixedPointNumericLabel__Initializer(Ft_Esd_FixedPointNumericLabel *context)
{
	Ft_Esd_Widget__Initializer((Ft_Esd_Widget *)context);
	context->Widget.ClassId = Ft_Esd_FixedPointNumericLabel_CLASSID;
	context->Widget.Slots = &s_Ft_Esd_FixedPointNumericLabel__Slots;
	context->Widget.LocalX = 0;
	context->Widget.LocalY = 0;
	context->Widget.LocalWidth = 120;
	context->Widget.LocalHeight = 36;
	context->Theme = Ft_Esd_FixedPointNumericLabel_Theme__Default;
	context->X = 0;
	context->Y = 0;
	context->Option = OPT_SIGNED;
	context->Number = "";
	context->Font = Ft_Esd_FixedPointNumericLabel_Font__Default;
	context->FontHeight = 0;
	context->AlignX = Ft_Esd_FixedPointNumericLabel_AlignX__Default;
	context->AlignY = Ft_Esd_FixedPointNumericLabel_AlignY__Default;
	context->AutoResize = Ft_Esd_FixedPointNumericLabel_AutoResize__Default;
	context->NDigit = 0L;
	context->Value = Ft_Esd_FixedPointNumericLabel_Value__Default;
	context->NDigitAfterDot = 0L;
	context->EnablePadding = Ft_Esd_FixedPointNumericLabel_EnablePadding__Default;
	context->NoOfDigits = Ft_Esd_FixedPointNumericLabel_NoOfDigits__Default;
	context->NoOfDigitsAfterDot = Ft_Esd_FixedPointNumericLabel_NoOfDigitsAfterDot__Default;
	context->IsZeroLeading = Ft_Esd_FixedPointNumericLabel_IsZeroLeading__Default;
}

static ft_uint16_t Ft_Esd_FixedPointNumericLabel_Get_Font_Height__return(Ft_Esd_FixedPointNumericLabel *context);

void Ft_Esd_FixedPointNumericLabel_Start_Signal(Ft_Esd_FixedPointNumericLabel *context);
void Ft_Esd_FixedPointNumericLabel_End_Signal(Ft_Esd_FixedPointNumericLabel *context);
ft_void_t Ft_Gpu_CoCmd_Text(Ft_Gpu_Hal_Context_t *, ft_int16_t, ft_int16_t, ft_int16_t, ft_uint16_t, const ft_char8_t *);
ft_uint8_t Ft_Esd_Dl_RomFont_Setup(ft_uint8_t);
void Ft_Esd_FixedPointNumericLabel_UpdateNumberString(Ft_Esd_FixedPointNumericLabel *context);
void Ft_Esd_FixedPointNumericLabel_ComputePosition(Ft_Esd_FixedPointNumericLabel *context);

void Ft_Esd_FixedPointNumericLabel_Start(Ft_Esd_FixedPointNumericLabel *context)
{
	void *owner = context->Owner;
	Ft_Esd_Widget_Start((Ft_Esd_Widget *)context); 
	Ft_Esd_FixedPointNumericLabel_Start_Signal(context);
	ft_uint16_t set_variable = Ft_Esd_FixedPointNumericLabel_Get_Font_Height__return(context);
	context->FontHeight = (int)set_variable;
}

void Ft_Esd_FixedPointNumericLabel_End(Ft_Esd_FixedPointNumericLabel *context)
{
	void *owner = context->Owner;
	Ft_Esd_FixedPointNumericLabel_End_Signal(context);
	Ft_Esd_Widget_End((Ft_Esd_Widget *)context); 
}

void Ft_Esd_FixedPointNumericLabel_Render(Ft_Esd_FixedPointNumericLabel *context)
{
	void *owner = context->Owner;
	ft_uint8_t alpha = 255;
	Ft_Esd_Dl_COLOR_A(alpha);
	Ft_Esd_Theme * theme = context->Theme(owner);
	ft_rgb32_t c_1 = Ft_Esd_Theme_GetTextColor(theme);
	Ft_Esd_Dl_COLOR_RGB(c_1);
	Ft_Gpu_Hal_Context_t * phost = Ft_Esd_GetHost();
	ft_int16_t x = context->X;
	ft_int16_t y = context->Y;
	ft_int16_t font_1 = context->Font(owner);
	ft_uint8_t font = Ft_Esd_Dl_RomFont_Setup(font_1);
	ft_uint16_t options = context->Option;
	char * s = context->Number;
	Ft_Gpu_CoCmd_Text(phost, x, y, font, options, s);
	Ft_Esd_Widget_Render((Ft_Esd_Widget *)context); 
}

void Ft_Esd_FixedPointNumericLabel_Update(Ft_Esd_FixedPointNumericLabel *context)
{
	void *owner = context->Owner;
	ft_uint8_t left = context->AutoResize(owner);
	ft_uint8_t right = ESD_AUTORESIZE_HEIGHT;
	int if_1 = left == right;
	if (if_1)
	{
		ft_uint16_t set_local_height = Ft_Esd_FixedPointNumericLabel_Get_Font_Height__return(context);
		Ft_Esd_Widget_SetHeight((Ft_Esd_Widget *)context, (int)set_local_height);
	}
	else
	{
	}
	ft_int32_t set_ndigit = context->NoOfDigits(owner);
	context->NDigit = set_ndigit;
	int set_variable_2 = context->NoOfDigitsAfterDot(owner);
	context->NDigitAfterDot = set_variable_2;
	Ft_Esd_FixedPointNumericLabel_UpdateNumberString(context);
	Ft_Esd_FixedPointNumericLabel_ComputePosition(context);
	Ft_Esd_Widget_Update((Ft_Esd_Widget *)context); 
}

ft_uint16_t Ft_Esd_FixedPointNumericLabel_Get_Font_Height__return(Ft_Esd_FixedPointNumericLabel *context)
{
	void *owner = context->Owner;
	ft_int16_t i = context->Font(owner);
	return Ft_Esd_GetFontHeight(i);
}

#ifdef ESD_SIMULATION
#include <stdlib.h>

typedef struct
{
	Ft_Esd_FixedPointNumericLabel Instance;
	Ft_Esd_Theme * Theme;
	ft_int16_t Font;
	ft_uint16_t AlignX;
	ft_uint16_t AlignY;
	ft_uint8_t AutoResize;
	float Value;
	ft_bool_t EnablePadding;
	ft_int32_t NoOfDigits;
	int NoOfDigitsAfterDot;
	ft_bool_t IsZeroLeading;
} Ft_Esd_FixedPointNumericLabel__ESD;

Ft_Esd_Theme * Ft_Esd_FixedPointNumericLabel__Get_Theme__ESD(void *context) { return ((Ft_Esd_FixedPointNumericLabel__ESD *)context)->Theme; }
void Ft_Esd_FixedPointNumericLabel__Set_Theme__ESD(void *context, Ft_Esd_Theme * value) { ((Ft_Esd_FixedPointNumericLabel__ESD *)context)->Theme = value; }
ft_int16_t Ft_Esd_FixedPointNumericLabel__Get_Font__ESD(void *context) { return ((Ft_Esd_FixedPointNumericLabel__ESD *)context)->Font; }
void Ft_Esd_FixedPointNumericLabel__Set_Font__ESD(void *context, ft_int16_t value) { ((Ft_Esd_FixedPointNumericLabel__ESD *)context)->Font = value; }
ft_uint16_t Ft_Esd_FixedPointNumericLabel__Get_AlignX__ESD(void *context) { return ((Ft_Esd_FixedPointNumericLabel__ESD *)context)->AlignX; }
void Ft_Esd_FixedPointNumericLabel__Set_AlignX__ESD(void *context, ft_uint16_t value) { ((Ft_Esd_FixedPointNumericLabel__ESD *)context)->AlignX = value; }
ft_uint16_t Ft_Esd_FixedPointNumericLabel__Get_AlignY__ESD(void *context) { return ((Ft_Esd_FixedPointNumericLabel__ESD *)context)->AlignY; }
void Ft_Esd_FixedPointNumericLabel__Set_AlignY__ESD(void *context, ft_uint16_t value) { ((Ft_Esd_FixedPointNumericLabel__ESD *)context)->AlignY = value; }
ft_uint8_t Ft_Esd_FixedPointNumericLabel__Get_AutoResize__ESD(void *context) { return ((Ft_Esd_FixedPointNumericLabel__ESD *)context)->AutoResize; }
void Ft_Esd_FixedPointNumericLabel__Set_AutoResize__ESD(void *context, ft_uint8_t value) { ((Ft_Esd_FixedPointNumericLabel__ESD *)context)->AutoResize = value; }
float Ft_Esd_FixedPointNumericLabel__Get_Value__ESD(void *context) { return ((Ft_Esd_FixedPointNumericLabel__ESD *)context)->Value; }
void Ft_Esd_FixedPointNumericLabel__Set_Value__ESD(void *context, float value) { ((Ft_Esd_FixedPointNumericLabel__ESD *)context)->Value = value; }
ft_bool_t Ft_Esd_FixedPointNumericLabel__Get_EnablePadding__ESD(void *context) { return ((Ft_Esd_FixedPointNumericLabel__ESD *)context)->EnablePadding; }
void Ft_Esd_FixedPointNumericLabel__Set_EnablePadding__ESD(void *context, ft_bool_t value) { ((Ft_Esd_FixedPointNumericLabel__ESD *)context)->EnablePadding = value; }
ft_int32_t Ft_Esd_FixedPointNumericLabel__Get_NoOfDigits__ESD(void *context) { return ((Ft_Esd_FixedPointNumericLabel__ESD *)context)->NoOfDigits; }
void Ft_Esd_FixedPointNumericLabel__Set_NoOfDigits__ESD(void *context, ft_int32_t value) { ((Ft_Esd_FixedPointNumericLabel__ESD *)context)->NoOfDigits = value; }
int Ft_Esd_FixedPointNumericLabel__Get_NoOfDigitsAfterDot__ESD(void *context) { return ((Ft_Esd_FixedPointNumericLabel__ESD *)context)->NoOfDigitsAfterDot; }
void Ft_Esd_FixedPointNumericLabel__Set_NoOfDigitsAfterDot__ESD(void *context, int value) { ((Ft_Esd_FixedPointNumericLabel__ESD *)context)->NoOfDigitsAfterDot = value; }
ft_bool_t Ft_Esd_FixedPointNumericLabel__Get_IsZeroLeading__ESD(void *context) { return ((Ft_Esd_FixedPointNumericLabel__ESD *)context)->IsZeroLeading; }
void Ft_Esd_FixedPointNumericLabel__Set_IsZeroLeading__ESD(void *context, ft_bool_t value) { ((Ft_Esd_FixedPointNumericLabel__ESD *)context)->IsZeroLeading = value; }

void *Ft_Esd_FixedPointNumericLabel__Create__ESD()
{
	Ft_Esd_FixedPointNumericLabel__ESD *context = (Ft_Esd_FixedPointNumericLabel__ESD *)malloc(sizeof(Ft_Esd_FixedPointNumericLabel__ESD));
	Ft_Esd_FixedPointNumericLabel__Initializer(&context->Instance);
	context->Instance.Owner = context;
	context->Theme = Ft_Esd_Theme_GetCurrent();
	context->Instance.Theme = Ft_Esd_FixedPointNumericLabel__Get_Theme__ESD;
	context->Font = 27;
	context->Instance.Font = Ft_Esd_FixedPointNumericLabel__Get_Font__ESD;
	context->AlignX = OPT_ALIGN_LEFT;
	context->Instance.AlignX = Ft_Esd_FixedPointNumericLabel__Get_AlignX__ESD;
	context->AlignY = OPT_ALIGN_CENTER;
	context->Instance.AlignY = Ft_Esd_FixedPointNumericLabel__Get_AlignY__ESD;
	context->AutoResize = ESD_AUTORESIZE_HEIGHT;
	context->Instance.AutoResize = Ft_Esd_FixedPointNumericLabel__Get_AutoResize__ESD;
	context->Value = 0.0f;
	context->Instance.Value = Ft_Esd_FixedPointNumericLabel__Get_Value__ESD;
	context->EnablePadding = 0;
	context->Instance.EnablePadding = Ft_Esd_FixedPointNumericLabel__Get_EnablePadding__ESD;
	context->NoOfDigits = 7L;
	context->Instance.NoOfDigits = Ft_Esd_FixedPointNumericLabel__Get_NoOfDigits__ESD;
	context->NoOfDigitsAfterDot = 6L;
	context->Instance.NoOfDigitsAfterDot = Ft_Esd_FixedPointNumericLabel__Get_NoOfDigitsAfterDot__ESD;
	context->IsZeroLeading = 0;
	context->Instance.IsZeroLeading = Ft_Esd_FixedPointNumericLabel__Get_IsZeroLeading__ESD;
	return context;
}

void Ft_Esd_FixedPointNumericLabel__Destroy__ESD(void *context)
{
	free(context);
}

void Ft_Esd_FixedPointNumericLabel__Set_X__ESD(void *context, ft_int16_t value) { ((Ft_Esd_FixedPointNumericLabel__ESD *)context)->Instance.X = value; }
void Ft_Esd_FixedPointNumericLabel__Set_Y__ESD(void *context, ft_int16_t value) { ((Ft_Esd_FixedPointNumericLabel__ESD *)context)->Instance.Y = value; }
void Ft_Esd_FixedPointNumericLabel__Set_Option__ESD(void *context, ft_uint16_t value) { ((Ft_Esd_FixedPointNumericLabel__ESD *)context)->Instance.Option = value; }
void Ft_Esd_FixedPointNumericLabel__Set_Number__ESD(void *context, char * value) { ((Ft_Esd_FixedPointNumericLabel__ESD *)context)->Instance.Number = value; }
void Ft_Esd_FixedPointNumericLabel__Set_FontHeight__ESD(void *context, ft_int16_t value) { ((Ft_Esd_FixedPointNumericLabel__ESD *)context)->Instance.FontHeight = value; }
void Ft_Esd_FixedPointNumericLabel__Set_NDigit__ESD(void *context, int value) { ((Ft_Esd_FixedPointNumericLabel__ESD *)context)->Instance.NDigit = value; }
void Ft_Esd_FixedPointNumericLabel__Set_NDigitAfterDot__ESD(void *context, int value) { ((Ft_Esd_FixedPointNumericLabel__ESD *)context)->Instance.NDigitAfterDot = value; }

#endif /* ESD_SIMULATION */

/* end of file */
