/*
This file is automatically generated
App
C Source
*/

#include "App.h"

#include "stdlib.h"

extern void Ft_Esd_Noop(void *context);
extern void Ft_Esd_Spinner_Popup();



#define Main_Page__ID 1

void App__Initializer(App *context)
{
	context->Parent = 0;
	context->_ActivePage = 0;
	context->Main_Page = 0;
	context->Main_Page__Active = 0;
}

static void App__Main_Page__Validate(App *context)
{
	void *parent = context->Parent;
	if (!context->Main_Page)
	{
		my_printf("Context is correct in App__Main_Page__Validate\r\n");

		context->Main_Page = (MainPage *)malloc(sizeof(MainPage));
		MainPage__Initializer(context->Main_Page);
		context->Main_Page->Parent = context;
		MainPage_Start(context->Main_Page);
	}
}

static void App__Main_Page__Create(App *context)
{
	App__Main_Page__Validate(context);
	context->Main_Page__Active = 1;
}

static void App__Main_Page__Destroy(App *context, int final)
{
	if (context->Main_Page__Active)
	{
		context->Main_Page__Active = 0;
	}
	if (context->Main_Page)
	{
		MainPage_End(context->Main_Page);
		free(context->Main_Page);
		context->Main_Page = 0;
	}
}

void App_Start(App *context)
{
	void *parent = context->Parent;
	App__Main_Page__Create(context);
}

void App_Update(App *context)
{
	void *parent = context->Parent;
	MainPage_Update(context->Main_Page);
}

void App_Render(App *context)
{
	void *parent = context->Parent;
	MainPage_Render(context->Main_Page);
}

void App_Idle(App *context)
{
	void *parent = context->Parent;
	MainPage_Idle(context->Main_Page);
}

void App_End(App *context)
{
	void *parent = context->Parent;
	App__Main_Page__Destroy(context, 1);
}

static App application;

void Ft_Main__Start()
{
	App__Initializer(&application);
	App_Start(&application);
}

void Ft_Main__Update()
{
	App_Update(&application);
}

void Ft_Main__Render()
{
	App_Render(&application);
}

void Ft_Main__Idle()
{
	App_Idle(&application);
}

void Ft_Main__End()
{
	App_End(&application);
}

#ifdef ESD_SIMULATION
#include <stdlib.h>

typedef struct
{
	App Instance;
} App__ESD;


void *App__Create__ESD()
{
	App__ESD *context = (App__ESD *)malloc(sizeof(App__ESD));
	App__Initializer(&context->Instance);
	context->Instance.Parent = context;
	return context;
}

void App__Destroy__ESD(void *context)
{
	free(context);
}


#endif /* ESD_SIMULATION */

/* end of file */
