/*
This file is automatically generated
purdue
Header
*/

#ifndef purdue__H
#define purdue__H

#ifndef ESD_FUNCTION
#define ESD_FUNCTION(name, ...)
#endif

#include "FT_DataTypes.h"
#include "Ft_Esd_Theme.h"

ESD_FUNCTION(purdue, Type = Ft_Esd_Theme *, Include = "purdue.h", Category = _GroupUserResources, Icon = ":/icons/palette.png")
Ft_Esd_Theme *purdue();

#endif /* purdue__H */

/* end of file */
