/*
This file is automatically generated
DO NOT MODIFY BY HAND
Ft_Esd_PushButton
C Source
*/

#include "Ft_Esd_PushButton.h"

#include "FT_Esd_Dl.h"
#include "Ft_Esd_CoCmd.h"

extern void Ft_Esd_Noop(void *context);
Ft_Esd_Theme * Ft_Esd_PushButton_Theme__Default(void *context) { return Ft_Esd_Theme_GetCurrent(); }
ft_int16_t Ft_Esd_PushButton_Font__Default(void *context) { return 27; }
const char * Ft_Esd_PushButton_Text__Default(void *context) { return "Button"; }
ft_bool_t Ft_Esd_PushButton_Primary__Default(void *context) { return 1; }


static Ft_Esd_WidgetSlots s_Ft_Esd_PushButton__Slots = {
	(void(*)(void *))Ft_Esd_Widget_Initialize,
	(void(*)(void *))Ft_Esd_PushButton_Start,
	(void(*)(void *))Ft_Esd_Widget_Enable,
	(void(*)(void *))Ft_Esd_PushButton_Update,
	(void(*)(void *))Ft_Esd_PushButton_Render,
	(void(*)(void *))Ft_Esd_Widget_Idle,
	(void(*)(void *))Ft_Esd_Widget_Disable,
	(void(*)(void *))Ft_Esd_PushButton_End,
};

static void Ft_Esd_PushButton_Touch_Tag_Down__Signal(void *context);
static void Ft_Esd_PushButton_Touch_Tag_Up__Signal(void *context);
static void Ft_Esd_PushButton_Touch_Tag_Tap__Signal(void *context);

void Ft_Esd_PushButton__Touch_Tag__Initializer(Ft_Esd_PushButton *context)
{
	Ft_Esd_TouchTag *object = &context->Touch_Tag;
	Ft_Esd_TouchTag__Initializer(object);
	object->Owner = context;
	object->Down = Ft_Esd_PushButton_Touch_Tag_Down__Signal;
	object->Up = Ft_Esd_PushButton_Touch_Tag_Up__Signal;
	object->Tap = Ft_Esd_PushButton_Touch_Tag_Tap__Signal;
}

void Ft_Esd_PushButton__Initializer(Ft_Esd_PushButton *context)
{
	Ft_Esd_Widget__Initializer((Ft_Esd_Widget *)context);
	context->Widget.ClassId = Ft_Esd_PushButton_CLASSID;
	context->Widget.Slots = &s_Ft_Esd_PushButton__Slots;
	context->Widget.LocalX = 0;
	context->Widget.LocalY = 0;
	context->Widget.LocalWidth = 120;
	context->Widget.LocalHeight = 36;
	context->Theme = Ft_Esd_PushButton_Theme__Default;
	context->Font = Ft_Esd_PushButton_Font__Default;
	context->Text = Ft_Esd_PushButton_Text__Default;
	context->Down = Ft_Esd_Noop;
	context->Primary = Ft_Esd_PushButton_Primary__Default;
	context->Up = Ft_Esd_Noop;
	context->Pushed = Ft_Esd_Noop;
	Ft_Esd_PushButton__Touch_Tag__Initializer(context);
}

ft_void_t Ft_Gpu_CoCmd_FgColor(Ft_Gpu_Hal_Context_t *, ft_rgb32_t);
ft_void_t Ft_Gpu_CoCmd_Button(Ft_Gpu_Hal_Context_t *, ft_int16_t, ft_int16_t, ft_int16_t, ft_int16_t, ft_int16_t, ft_uint16_t, const ft_char8_t *);
ft_uint8_t Ft_Esd_Dl_RomFont_Setup(ft_uint8_t);
ft_void_t Ft_Gpu_CoCmd_Number(Ft_Gpu_Hal_Context_t *, ft_int16_t, ft_int16_t, ft_int16_t, ft_uint16_t, ft_int32_t);

void Ft_Esd_PushButton_Start(Ft_Esd_PushButton *context)
{
	void *owner = context->Owner;
	Ft_Esd_Widget_Start((Ft_Esd_Widget *)context);
	Ft_Esd_TouchTag_Start(&context->Touch_Tag);
}

void Ft_Esd_PushButton_Update(Ft_Esd_PushButton *context)
{
	void *owner = context->Owner;
	Ft_Esd_TouchTag_Update(&context->Touch_Tag);
	Ft_Esd_Widget_Update((Ft_Esd_Widget *)context);
}

void Ft_Esd_PushButton_End(Ft_Esd_PushButton *context)
{
	void *owner = context->Owner;
	Ft_Esd_TouchTag_End(&context->Touch_Tag);
	Ft_Esd_Widget_End((Ft_Esd_Widget *)context);
}

void Ft_Esd_PushButton_Render(Ft_Esd_PushButton *context)
{
	void *owner = context->Owner;
	ft_uint8_t alpha = 255;
	Ft_Esd_Dl_COLOR_A(alpha);
	ft_uint8_t s = Ft_Esd_TouchTag_Tag(&context->Touch_Tag);
	Ft_Esd_Dl_TAG(s);
	Ft_Gpu_Hal_Context_t * phost = Ft_Esd_GetHost();
	ft_bool_t if_1 = context->Primary(owner);
	ft_rgb32_t c_1;
	if (if_1)
	{
		Ft_Esd_Theme * theme = context->Theme(owner);
		c_1 = Ft_Esd_Theme_GetPrimaryColor(theme);
	}
	else
	{
		Ft_Esd_Theme * theme_1 = context->Theme(owner);
		c_1 = Ft_Esd_Theme_GetCurrentColor(theme_1);
	}
	Ft_Gpu_CoCmd_FgColor(phost, c_1);
	Ft_Esd_Theme * theme_2 = context->Theme(owner);
	ft_rgb32_t c_2 = Ft_Esd_Theme_GetButtonTextColor(theme_2);
	Ft_Esd_Dl_COLOR_RGB(c_2);
	Ft_Gpu_Hal_Context_t * phost_1 = Ft_Esd_GetHost();
	ft_int16_t x = context->Widget.GlobalX;
	ft_int16_t y = context->Widget.GlobalY;
	ft_int16_t width = context->Widget.GlobalWidth;
	ft_int16_t height = context->Widget.GlobalHeight;
	ft_int16_t font_1 = context->Font(owner);
	ft_uint8_t font = Ft_Esd_Dl_RomFont_Setup(font_1);
	ft_bool_t if_2 = Ft_Esd_TouchTag_Inside(&context->Touch_Tag);
	ft_uint16_t options;
	if (if_2)
	{
		options = OPT_FLAT;
	}
	else
	{
		options = 0;
	}
	const char * s_1 = context->Text(owner);
	Ft_Gpu_CoCmd_Button(phost_1, x, y, width, height, font, options, s_1);
	ft_uint8_t s_2 = 255;
	Ft_Esd_Dl_TAG(s_2);
	Ft_Esd_Widget_Render((Ft_Esd_Widget *)context); 
}

ft_bool_t Ft_Esd_PushButton_Pushing(Ft_Esd_PushButton *context)
{
	void *owner = context->Owner;
	return Ft_Esd_TouchTag_Inside(&context->Touch_Tag);
}

void Ft_Esd_PushButton_Touch_Tag_Down__Signal(void *c)
{
	Ft_Esd_PushButton *context = (Ft_Esd_PushButton *)c;
	void *owner = context->Owner;
	context->Down(owner);
}

void Ft_Esd_PushButton_Touch_Tag_Up__Signal(void *c)
{
	Ft_Esd_PushButton *context = (Ft_Esd_PushButton *)c;
	void *owner = context->Owner;
	context->Up(owner);
}

void Ft_Esd_PushButton_Touch_Tag_Tap__Signal(void *c)
{
	Ft_Esd_PushButton *context = (Ft_Esd_PushButton *)c;
	void *owner = context->Owner;
	context->Pushed(owner);
}

#ifdef ESD_SIMULATION
#include <stdlib.h>

typedef struct
{
	Ft_Esd_PushButton Instance;
	Ft_Esd_Theme * Theme;
	ft_int16_t Font;
	const char * Text;
	ft_bool_t Primary;
} Ft_Esd_PushButton__ESD;

Ft_Esd_Theme * Ft_Esd_PushButton__Get_Theme__ESD(void *context) { return ((Ft_Esd_PushButton__ESD *)context)->Theme; }
void Ft_Esd_PushButton__Set_Theme__ESD(void *context, Ft_Esd_Theme * value) { ((Ft_Esd_PushButton__ESD *)context)->Theme = value; }
ft_int16_t Ft_Esd_PushButton__Get_Font__ESD(void *context) { return ((Ft_Esd_PushButton__ESD *)context)->Font; }
void Ft_Esd_PushButton__Set_Font__ESD(void *context, ft_int16_t value) { ((Ft_Esd_PushButton__ESD *)context)->Font = value; }
const char * Ft_Esd_PushButton__Get_Text__ESD(void *context) { return ((Ft_Esd_PushButton__ESD *)context)->Text; }
void Ft_Esd_PushButton__Set_Text__ESD(void *context, const char * value) { ((Ft_Esd_PushButton__ESD *)context)->Text = value; }
ft_bool_t Ft_Esd_PushButton__Get_Primary__ESD(void *context) { return ((Ft_Esd_PushButton__ESD *)context)->Primary; }
void Ft_Esd_PushButton__Set_Primary__ESD(void *context, ft_bool_t value) { ((Ft_Esd_PushButton__ESD *)context)->Primary = value; }

void *Ft_Esd_PushButton__Create__ESD()
{
	Ft_Esd_PushButton__ESD *context = (Ft_Esd_PushButton__ESD *)malloc(sizeof(Ft_Esd_PushButton__ESD));
	Ft_Esd_PushButton__Initializer(&context->Instance);
	context->Instance.Owner = context;
	context->Theme = Ft_Esd_Theme_GetCurrent();
	context->Instance.Theme = Ft_Esd_PushButton__Get_Theme__ESD;
	context->Font = 27;
	context->Instance.Font = Ft_Esd_PushButton__Get_Font__ESD;
	context->Text = "Button";
	context->Instance.Text = Ft_Esd_PushButton__Get_Text__ESD;
	context->Primary = 1;
	context->Instance.Primary = Ft_Esd_PushButton__Get_Primary__ESD;
	return context;
}

void Ft_Esd_PushButton__Destroy__ESD(void *context)
{
	free(context);
}


#endif /* ESD_SIMULATION */

/* end of file */
