/*
This file is automatically generated
DO NOT MODIFY BY HAND
Ft_Esd_Label
C Source
*/

#include "Ft_Esd_Label.h"

#include "FT_Esd_Dl.h"
#include "Ft_Esd_CoCmd.h"

extern void Ft_Esd_Noop(void *context);
Ft_Esd_Theme * Ft_Esd_Label_Theme__Default(void *context) { return Ft_Esd_Theme_GetCurrent(); }
ft_int16_t Ft_Esd_Label_Font__Default(void *context) { return 27; }
const char * Ft_Esd_Label_Text__Default(void *context) { return "Label"; }
ft_uint16_t Ft_Esd_Label_AlignX__Default(void *context) { return OPT_ALIGN_LEFT; }
ft_uint16_t Ft_Esd_Label_AlignY__Default(void *context) { return OPT_ALIGN_TOP; }


static Ft_Esd_WidgetSlots s_Ft_Esd_Label__Slots = {
	(void(*)(void *))Ft_Esd_Widget_Initialize,
	(void(*)(void *))Ft_Esd_Widget_Start,
	(void(*)(void *))Ft_Esd_Widget_Enable,
	(void(*)(void *))Ft_Esd_Label_Update,
	(void(*)(void *))Ft_Esd_Label_Render,
	(void(*)(void *))Ft_Esd_Widget_Idle,
	(void(*)(void *))Ft_Esd_Widget_Disable,
	(void(*)(void *))Ft_Esd_Widget_End,
};


void Ft_Esd_Label__Initializer(Ft_Esd_Label *context)
{
	Ft_Esd_Widget__Initializer((Ft_Esd_Widget *)context);
	context->Widget.ClassId = Ft_Esd_Label_CLASSID;
	context->Widget.Slots = &s_Ft_Esd_Label__Slots;
	context->Widget.LocalX = 0;
	context->Widget.LocalY = 0;
	context->Widget.LocalWidth = 120;
	context->Widget.LocalHeight = 36;
	context->AutoResize = ESD_AUTORESIZE_HEIGHT;
	context->Theme = Ft_Esd_Label_Theme__Default;
	context->Font = Ft_Esd_Label_Font__Default;
	context->Text = Ft_Esd_Label_Text__Default;
	context->AlignX = Ft_Esd_Label_AlignX__Default;
	context->AlignY = Ft_Esd_Label_AlignY__Default;
}

static ft_uint16_t Ft_Esd_Label_Get_Font_Height__return(Ft_Esd_Label *context);

ft_uint8_t Ft_Esd_Dl_RomFont_Setup(ft_uint8_t);
ft_void_t Ft_Gpu_CoCmd_Text(Ft_Gpu_Hal_Context_t *, ft_int16_t, ft_int16_t, ft_int16_t, ft_uint16_t, const ft_char8_t *);

void Ft_Esd_Label_Update(Ft_Esd_Label *context)
{
	void *owner = context->Owner;
	ft_uint8_t left = context->AutoResize;
	ft_uint8_t right = ESD_AUTORESIZE_HEIGHT;
	ft_uint8_t if_1 = left & right;
	if (if_1)
	{
		ft_uint16_t set_variable = Ft_Esd_Label_Get_Font_Height__return(context);
		Ft_Esd_Widget_SetHeight((Ft_Esd_Widget *)context, set_variable);
	}
	else
	{
	}
	Ft_Esd_Widget_Update((Ft_Esd_Widget *)context); 
}

void Ft_Esd_Label_Render(Ft_Esd_Label *context)
{
	void *owner = context->Owner;
	ft_uint8_t alpha = 255;
	Ft_Esd_Dl_COLOR_A(alpha);
	Ft_Esd_Theme * theme = context->Theme(owner);
	ft_rgb32_t c_1 = Ft_Esd_Theme_GetTextColor(theme);
	Ft_Esd_Dl_COLOR_RGB(c_1);
	Ft_Gpu_Hal_Context_t * phost = Ft_Esd_GetHost();
	ft_uint16_t left_1 = context->AlignX(owner);
	int right_1 = 0L;
	int if_2 = left_1 == right_1;
	int x;
	if (if_2)
	{
		x = context->Widget.GlobalX;
	}
	else
	{
		ft_uint16_t left_2 = context->AlignX(owner);
		int right_2 = 2L;
		int if_3 = left_2 == right_2;
		if (if_3)
		{
			ft_int16_t left_3 = context->Widget.GlobalX;
			ft_int16_t right_3 = context->Widget.GlobalWidth;
			x = left_3 + right_3;
		}
		else
		{
			ft_int16_t left_4 = context->Widget.GlobalX;
			ft_int16_t left_5 = context->Widget.GlobalWidth;
			int right_5 = 2L;
			int right_4 = left_5 / right_5;
			x = left_4 + right_4;
		}
	}
	ft_uint16_t left_6 = context->AlignY(owner);
	int right_6 = 1L;
	int if_4 = left_6 == right_6;
	int y;
	if (if_4)
	{
		ft_int16_t left_7 = context->Widget.GlobalY;
		ft_int16_t left_8 = context->Widget.GlobalHeight;
		int right_8 = 2L;
		int right_7 = left_8 / right_8;
		y = left_7 + right_7;
	}
	else
	{
		ft_uint16_t left_9 = context->AlignY(owner);
		int right_9 = 0L;
		int if_5 = left_9 == right_9;
		if (if_5)
		{
			y = context->Widget.GlobalY;
		}
		else
		{
			ft_int16_t left_11 = context->Widget.GlobalY;
			ft_int16_t right_10 = context->Widget.GlobalHeight;
			int left_10 = left_11 + right_10;
			ft_uint16_t right_11 = Ft_Esd_Label_Get_Font_Height__return(context);
			y = left_10 - right_11;
		}
	}
	ft_int16_t font_1 = context->Font(owner);
	ft_uint8_t font = Ft_Esd_Dl_RomFont_Setup(font_1);
	ft_uint16_t left_13 = context->AlignX(owner);
	int right_12 = 0L;
	int if_6 = left_13 == right_12;
	ft_uint16_t left_12;
	if (if_6)
	{
		left_12 = 0;
	}
	else
	{
		ft_uint16_t left_14 = context->AlignX(owner);
		int right_13 = 2L;
		int if_7 = left_14 == right_13;
		if (if_7)
		{
			left_12 = OPT_RIGHTX;
		}
		else
		{
			left_12 = OPT_CENTERX;
		}
	}
	ft_uint16_t left_15 = context->AlignY(owner);
	int right_15 = 1L;
	int if_8 = left_15 == right_15;
	ft_uint16_t right_14;
	if (if_8)
	{
		right_14 = OPT_CENTERY;
	}
	else
	{
		right_14 = 0;
	}
	ft_uint16_t options = left_12 | right_14;
	const char * s = context->Text(owner);
	Ft_Gpu_CoCmd_Text(phost, x, y, font, options, s);
	Ft_Esd_Widget_Render((Ft_Esd_Widget *)context); 
}

ft_uint16_t Ft_Esd_Label_Get_Font_Height__return(Ft_Esd_Label *context)
{
	void *owner = context->Owner;
	ft_int16_t i = context->Font(owner);
	return Ft_Esd_GetFontHeight(i);
}

#ifdef ESD_SIMULATION
#include <stdlib.h>

typedef struct
{
	Ft_Esd_Label Instance;
	Ft_Esd_Theme * Theme;
	ft_int16_t Font;
	const char * Text;
	ft_uint16_t AlignX;
	ft_uint16_t AlignY;
} Ft_Esd_Label__ESD;

Ft_Esd_Theme * Ft_Esd_Label__Get_Theme__ESD(void *context) { return ((Ft_Esd_Label__ESD *)context)->Theme; }
void Ft_Esd_Label__Set_Theme__ESD(void *context, Ft_Esd_Theme * value) { ((Ft_Esd_Label__ESD *)context)->Theme = value; }
ft_int16_t Ft_Esd_Label__Get_Font__ESD(void *context) { return ((Ft_Esd_Label__ESD *)context)->Font; }
void Ft_Esd_Label__Set_Font__ESD(void *context, ft_int16_t value) { ((Ft_Esd_Label__ESD *)context)->Font = value; }
const char * Ft_Esd_Label__Get_Text__ESD(void *context) { return ((Ft_Esd_Label__ESD *)context)->Text; }
void Ft_Esd_Label__Set_Text__ESD(void *context, const char * value) { ((Ft_Esd_Label__ESD *)context)->Text = value; }
ft_uint16_t Ft_Esd_Label__Get_AlignX__ESD(void *context) { return ((Ft_Esd_Label__ESD *)context)->AlignX; }
void Ft_Esd_Label__Set_AlignX__ESD(void *context, ft_uint16_t value) { ((Ft_Esd_Label__ESD *)context)->AlignX = value; }
ft_uint16_t Ft_Esd_Label__Get_AlignY__ESD(void *context) { return ((Ft_Esd_Label__ESD *)context)->AlignY; }
void Ft_Esd_Label__Set_AlignY__ESD(void *context, ft_uint16_t value) { ((Ft_Esd_Label__ESD *)context)->AlignY = value; }

void *Ft_Esd_Label__Create__ESD()
{
	Ft_Esd_Label__ESD *context = (Ft_Esd_Label__ESD *)malloc(sizeof(Ft_Esd_Label__ESD));
	Ft_Esd_Label__Initializer(&context->Instance);
	context->Instance.Owner = context;
	context->Theme = Ft_Esd_Theme_GetCurrent();
	context->Instance.Theme = Ft_Esd_Label__Get_Theme__ESD;
	context->Font = 27;
	context->Instance.Font = Ft_Esd_Label__Get_Font__ESD;
	context->Text = "Label";
	context->Instance.Text = Ft_Esd_Label__Get_Text__ESD;
	context->AlignX = OPT_ALIGN_LEFT;
	context->Instance.AlignX = Ft_Esd_Label__Get_AlignX__ESD;
	context->AlignY = OPT_ALIGN_TOP;
	context->Instance.AlignY = Ft_Esd_Label__Get_AlignY__ESD;
	return context;
}

void Ft_Esd_Label__Destroy__ESD(void *context)
{
	free(context);
}

void Ft_Esd_Label__Set_AutoResize__ESD(void *context, ft_uint8_t value) { ((Ft_Esd_Label__ESD *)context)->Instance.AutoResize = value; }

#endif /* ESD_SIMULATION */

/* end of file */
