/*
This file is automatically generated
DO NOT MODIFY BY HAND
MainPage
C Source
*/

#include "MainPage.h"

extern void Ft_Esd_Noop(void *context);

static const char * MainPage_ESD_Push_Button_4_Text__Property(void *context) { return "Bottom Right"; }
static const char * MainPage_ESD_Push_Button_3_Text__Property(void *context) { return "Bottom Left"; }
static const char * MainPage_ESD_Push_Button_2_Text__Property(void *context) { return "Top Right"; }
static const char * MainPage_ESD_Push_Button_Text__Property(void *context) { return "Top Left"; }
static ft_int16_t MainPage_ESD_Label_Font__Property(void *context) { return 20; }
static const char * MainPage_ESD_Label_Text__Property(void *context) { return "Select 5 inch platform from \"Build Target\" list of tool bar"; }
static ft_uint16_t MainPage_ESD_Label_AlignX__Property(void *context) { return OPT_ALIGN_CENTER; }

static Ft_Esd_WidgetSlots s_MainPage__Slots = {
	(void(*)(void *))Ft_Esd_Widget_Initialize,
	(void(*)(void *))Ft_Esd_Widget_Start,
	(void(*)(void *))Ft_Esd_Widget_Enable,
	(void(*)(void *))Ft_Esd_Widget_Update,
	(void(*)(void *))Ft_Esd_Widget_Render,
	(void(*)(void *))Ft_Esd_Widget_Idle,
	(void(*)(void *))Ft_Esd_Widget_Disable,
	(void(*)(void *))MainPage_End,
};


void MainPage__Fill_Layout__Initializer(MainPage *context)
{
	Ft_Esd_Layout_Fill *object = &context->Fill_Layout;
	Ft_Esd_Layout_Fill__Initializer(object);
	object->Owner = context;
	object->Widget.Active = 1;
	object->Widget.LocalX = 0;
	object->Widget.LocalY = 0;
	object->Widget.LocalWidth = 324;
	object->Widget.LocalHeight = 479;
	Ft_Esd_Widget_InsertBottom((Ft_Esd_Widget *)object, (Ft_Esd_Widget *)context);
}

void MainPage__Fixed_Position__Initializer(MainPage *context)
{
	Ft_Esd_Layout_Fixed *object = &context->Fixed_Position;
	Ft_Esd_Layout_Fixed__Initializer(object);
	object->Owner = context;
	object->Widget.Active = 1;
	object->Widget.LocalX = 0;
	object->Widget.LocalY = 0;
	object->Widget.LocalWidth = 53;
	object->Widget.LocalHeight = 50;
	Ft_Esd_Widget_InsertBottom((Ft_Esd_Widget *)object, (Ft_Esd_Widget *)&context->Fill_Layout);
}

void MainPage__ESD_Push_Button_4__Initializer(MainPage *context)
{
	Ft_Esd_PushButton *object = &context->ESD_Push_Button_4;
	Ft_Esd_PushButton__Initializer(object);
	object->Owner = context;
	object->Widget.Active = 1;
	object->Widget.LocalX = 196;
	object->Widget.LocalY = 439;
	object->Widget.LocalWidth = 120;
	object->Widget.LocalHeight = 36;
	object->Text = MainPage_ESD_Push_Button_4_Text__Property;
	Ft_Esd_Widget_InsertBottom((Ft_Esd_Widget *)object, (Ft_Esd_Widget *)&context->Fixed_Position);
}

void MainPage__ESD_Push_Button_3__Initializer(MainPage *context)
{
	Ft_Esd_PushButton *object = &context->ESD_Push_Button_3;
	Ft_Esd_PushButton__Initializer(object);
	object->Owner = context;
	object->Widget.Active = 1;
	object->Widget.LocalX = 6;
	object->Widget.LocalY = 437;
	object->Widget.LocalWidth = 120;
	object->Widget.LocalHeight = 36;
	object->Text = MainPage_ESD_Push_Button_3_Text__Property;
	Ft_Esd_Widget_InsertBottom((Ft_Esd_Widget *)object, (Ft_Esd_Widget *)&context->Fixed_Position);
}

void MainPage__ESD_Push_Button_2__Initializer(MainPage *context)
{
	Ft_Esd_PushButton *object = &context->ESD_Push_Button_2;
	Ft_Esd_PushButton__Initializer(object);
	object->Owner = context;
	object->Widget.Active = 1;
	object->Widget.LocalX = 198;
	object->Widget.LocalY = 10;
	object->Widget.LocalWidth = 120;
	object->Widget.LocalHeight = 36;
	object->Text = MainPage_ESD_Push_Button_2_Text__Property;
	Ft_Esd_Widget_InsertBottom((Ft_Esd_Widget *)object, (Ft_Esd_Widget *)&context->Fixed_Position);
}

void MainPage__ESD_Push_Button__Initializer(MainPage *context)
{
	Ft_Esd_PushButton *object = &context->ESD_Push_Button;
	Ft_Esd_PushButton__Initializer(object);
	object->Owner = context;
	object->Widget.Active = 1;
	object->Widget.LocalX = 13;
	object->Widget.LocalY = 12;
	object->Widget.LocalWidth = 120;
	object->Widget.LocalHeight = 36;
	object->Text = MainPage_ESD_Push_Button_Text__Property;
	Ft_Esd_Widget_InsertBottom((Ft_Esd_Widget *)object, (Ft_Esd_Widget *)&context->Fixed_Position);
}

void MainPage__ESD_Label__Initializer(MainPage *context)
{
	Ft_Esd_Label *object = &context->ESD_Label;
	Ft_Esd_Label__Initializer(object);
	object->Owner = context;
	object->Widget.Active = 1;
	object->Widget.LocalX = 1;
	object->Widget.LocalY = 224;
	object->Widget.LocalWidth = 293;
	object->Widget.LocalHeight = 209;
	object->AutoResize = ESD_AUTORESIZE_BOTH;
	object->Font = MainPage_ESD_Label_Font__Property;
	object->Text = MainPage_ESD_Label_Text__Property;
	object->AlignX = MainPage_ESD_Label_AlignX__Property;
	Ft_Esd_Widget_InsertBottom((Ft_Esd_Widget *)object, (Ft_Esd_Widget *)&context->Fixed_Position);
}

void MainPage__Initializer(MainPage *context)
{
	Ft_Esd_Widget__Initializer((Ft_Esd_Widget *)context);
	context->Widget.ClassId = MainPage_CLASSID;
	context->Widget.Slots = &s_MainPage__Slots;
	context->Widget.LocalX = 0;
	context->Widget.LocalY = 0;
	context->Widget.LocalWidth = 400;
	context->Widget.LocalHeight = 300;
	MainPage__Fill_Layout__Initializer(context);
	MainPage__Fixed_Position__Initializer(context);
	MainPage__ESD_Push_Button_4__Initializer(context);
	MainPage__ESD_Push_Button_3__Initializer(context);
	MainPage__ESD_Push_Button_2__Initializer(context);
	MainPage__ESD_Push_Button__Initializer(context);
	MainPage__ESD_Label__Initializer(context);
}

void MainPage_End(MainPage *context)
{
	void *owner = context->Owner;
	Ft_Esd_Widget_End((Ft_Esd_Widget *)context);
	Ft_Esd_Widget_Detach((Ft_Esd_Widget *)&context->Fill_Layout); 
	Ft_Esd_Widget_Detach((Ft_Esd_Widget *)&context->Fixed_Position); 
	Ft_Esd_Widget_Detach((Ft_Esd_Widget *)&context->ESD_Push_Button_4); 
	Ft_Esd_Widget_Detach((Ft_Esd_Widget *)&context->ESD_Push_Button_3); 
	Ft_Esd_Widget_Detach((Ft_Esd_Widget *)&context->ESD_Push_Button_2); 
	Ft_Esd_Widget_Detach((Ft_Esd_Widget *)&context->ESD_Push_Button); 
	Ft_Esd_Widget_Detach((Ft_Esd_Widget *)&context->ESD_Label); 
}

#ifdef ESD_SIMULATION
#include <stdlib.h>

typedef struct
{
	MainPage Instance;
} MainPage__ESD;


void *MainPage__Create__ESD()
{
	MainPage__ESD *context = (MainPage__ESD *)malloc(sizeof(MainPage__ESD));
	MainPage__Initializer(&context->Instance);
	context->Instance.Owner = context;
	return context;
}

void MainPage__Destroy__ESD(void *context)
{
	free(context);
}


#endif /* ESD_SIMULATION */

/* end of file */
