/*
This file is automatically generated
Ft_Esd_ScrollPanel
C Source
*/

#include "Ft_Esd_ScrollPanel.h"

#include "FT_Esd_Dl.h"
#include "Ft_Esd_Elements.h"

extern void Ft_Esd_Noop(void *context);
Ft_Esd_Theme * Ft_Esd_ScrollPanel_Theme__Default(void *context) { return Ft_Esd_Theme_GetCurrent(); }
ft_int16_t Ft_Esd_ScrollPanel_X__Default(void *context) { return 0; }
ft_int16_t Ft_Esd_ScrollPanel_Y__Default(void *context) { return 0; }
ft_int16_t Ft_Esd_ScrollPanel_Width__Default(void *context) { return 200; }
ft_int16_t Ft_Esd_ScrollPanel_Height__Default(void *context) { return 150; }
int Ft_Esd_ScrollPanel_Columns__Default(void *context) { return 1L; }
int Ft_Esd_ScrollPanel_Margin__Default(void *context) { return 4L; }
void Ft_Esd_ScrollPanel_OffsetYChanged__Noop(void *context, ft_int16_t value) { }

Ft_Esd_Theme * Ft_Esd_Theme_GetCurrent();
static int Ft_Esd_ScrollPanel_TouchArea_X__Property(void *context);
static int Ft_Esd_ScrollPanel_TouchArea_Y__Property(void *context);
static int Ft_Esd_ScrollPanel_TouchArea_Width__Property(void *context);
static int Ft_Esd_ScrollPanel_TouchArea_Height__Property(void *context);

static void Ft_Esd_ScrollPanel_TouchArea_Down__Signal(void *context);

void Ft_Esd_ScrollPanel__Initializer(Ft_Esd_ScrollPanel *context)
{
	context->Parent = 0;
	Ft_Esd_TouchArea__Initializer(&context->TouchArea);
	context->TouchArea.Parent = context;
	context->TouchArea.X = Ft_Esd_ScrollPanel_TouchArea_X__Property;
	context->TouchArea.Y = Ft_Esd_ScrollPanel_TouchArea_Y__Property;
	context->TouchArea.Width = Ft_Esd_ScrollPanel_TouchArea_Width__Property;
	context->TouchArea.Height = Ft_Esd_ScrollPanel_TouchArea_Height__Property;
	context->TouchArea.Down = Ft_Esd_ScrollPanel_TouchArea_Down__Signal;
	context->Theme = Ft_Esd_ScrollPanel_Theme__Default;
	context->X = Ft_Esd_ScrollPanel_X__Default;
	context->Y = Ft_Esd_ScrollPanel_Y__Default;
	context->Width = Ft_Esd_ScrollPanel_Width__Default;
	context->Height = Ft_Esd_ScrollPanel_Height__Default;
	context->Columns = Ft_Esd_ScrollPanel_Columns__Default;
	context->OffsetY = 0L;
	context->Margin = Ft_Esd_ScrollPanel_Margin__Default;
	context->OffsetYRange = 0L;
	context->PreviousTouchY = 0;
	context->OffsetYChanged = Ft_Esd_ScrollPanel_OffsetYChanged__Noop;
	context->CurrentX = 0L;
	context->CurrentY = 0L;
	context->PreviousOffsetY = 0;
	context->First = 0x0;
	context->Current = 0x0;
}

void Ft_Esd_ScrollPanel_Render_Contents(Ft_Esd_ScrollPanel *context);
void Ft_Esd_ScrollPanel_Update_Scroll(Ft_Esd_ScrollPanel *context);
void Ft_Esd_ScrollPanel_Update_Contents(Ft_Esd_ScrollPanel *context);
void Ft_Esd_Elements_Panel(Ft_Esd_Theme *, ft_int16_t, ft_int16_t, ft_int16_t, ft_int16_t, ft_int16_t, ft_bool_t);

void Ft_Esd_ScrollPanel_Render(Ft_Esd_ScrollPanel *context)
{
	void *parent = context->Parent;
	ft_uint8_t alpha = 255;
	Ft_Esd_Dl_COLOR_A(alpha);
	Ft_Esd_Theme * theme = context->Theme(parent);
	ft_int16_t x = context->X(parent);
	ft_int16_t y = context->Y(parent);
	ft_int16_t width = context->Width(parent);
	ft_int16_t height = context->Height(parent);
	ft_int16_t radius = 4;
	ft_bool_t raised = 0;
	Ft_Esd_Elements_Panel(theme, x, y, width, height, radius, raised);
	Ft_Esd_ScrollPanel_Render_Contents(context);
}

void Ft_Esd_ScrollPanel_Update(Ft_Esd_ScrollPanel *context)
{
	void *parent = context->Parent;
	Ft_Esd_TouchArea_Update(&context->TouchArea);
	Ft_Esd_ScrollPanel_Update_Scroll(context);
	Ft_Esd_ScrollPanel_Update_Contents(context);
}

int Ft_Esd_ScrollPanel_TouchArea_X__Property(void *c)
{
	Ft_Esd_ScrollPanel *context = (Ft_Esd_ScrollPanel *)c;
	void *parent = context->Parent;
	return context->X(parent);
}

int Ft_Esd_ScrollPanel_TouchArea_Y__Property(void *c)
{
	Ft_Esd_ScrollPanel *context = (Ft_Esd_ScrollPanel *)c;
	void *parent = context->Parent;
	return context->Y(parent);
}

int Ft_Esd_ScrollPanel_TouchArea_Width__Property(void *c)
{
	Ft_Esd_ScrollPanel *context = (Ft_Esd_ScrollPanel *)c;
	void *parent = context->Parent;
	return context->Width(parent);
}

int Ft_Esd_ScrollPanel_TouchArea_Height__Property(void *c)
{
	Ft_Esd_ScrollPanel *context = (Ft_Esd_ScrollPanel *)c;
	void *parent = context->Parent;
	return context->Height(parent);
}

void Ft_Esd_ScrollPanel_TouchArea_Down__Signal(void *c)
{
	Ft_Esd_ScrollPanel *context = (Ft_Esd_ScrollPanel *)c;
	void *parent = context->Parent;
	ft_int16_t set_variable = Ft_Esd_TouchArea_TouchY(&context->TouchArea);
	context->PreviousTouchY = set_variable;
	int set_variable_1 = context->OffsetY;
	context->PreviousOffsetY = set_variable_1;
}

#ifdef ESD_SIMULATION
#include <stdlib.h>

typedef struct
{
	Ft_Esd_ScrollPanel Instance;
	Ft_Esd_Theme * Theme;
	ft_int16_t X;
	ft_int16_t Y;
	ft_int16_t Width;
	ft_int16_t Height;
	int Columns;
	int Margin;
} Ft_Esd_ScrollPanel__ESD;

Ft_Esd_Theme * Ft_Esd_ScrollPanel__Get_Theme__ESD(void *context) { return ((Ft_Esd_ScrollPanel__ESD *)context)->Theme; }
void Ft_Esd_ScrollPanel__Set_Theme__ESD(void *context, Ft_Esd_Theme * value) { ((Ft_Esd_ScrollPanel__ESD *)context)->Theme = value; }
ft_int16_t Ft_Esd_ScrollPanel__Get_X__ESD(void *context) { return ((Ft_Esd_ScrollPanel__ESD *)context)->X; }
void Ft_Esd_ScrollPanel__Set_X__ESD(void *context, ft_int16_t value) { ((Ft_Esd_ScrollPanel__ESD *)context)->X = value; }
ft_int16_t Ft_Esd_ScrollPanel__Get_Y__ESD(void *context) { return ((Ft_Esd_ScrollPanel__ESD *)context)->Y; }
void Ft_Esd_ScrollPanel__Set_Y__ESD(void *context, ft_int16_t value) { ((Ft_Esd_ScrollPanel__ESD *)context)->Y = value; }
ft_int16_t Ft_Esd_ScrollPanel__Get_Width__ESD(void *context) { return ((Ft_Esd_ScrollPanel__ESD *)context)->Width; }
void Ft_Esd_ScrollPanel__Set_Width__ESD(void *context, ft_int16_t value) { ((Ft_Esd_ScrollPanel__ESD *)context)->Width = value; }
ft_int16_t Ft_Esd_ScrollPanel__Get_Height__ESD(void *context) { return ((Ft_Esd_ScrollPanel__ESD *)context)->Height; }
void Ft_Esd_ScrollPanel__Set_Height__ESD(void *context, ft_int16_t value) { ((Ft_Esd_ScrollPanel__ESD *)context)->Height = value; }
int Ft_Esd_ScrollPanel__Get_Columns__ESD(void *context) { return ((Ft_Esd_ScrollPanel__ESD *)context)->Columns; }
void Ft_Esd_ScrollPanel__Set_Columns__ESD(void *context, int value) { ((Ft_Esd_ScrollPanel__ESD *)context)->Columns = value; }
int Ft_Esd_ScrollPanel__Get_Margin__ESD(void *context) { return ((Ft_Esd_ScrollPanel__ESD *)context)->Margin; }
void Ft_Esd_ScrollPanel__Set_Margin__ESD(void *context, int value) { ((Ft_Esd_ScrollPanel__ESD *)context)->Margin = value; }

void *Ft_Esd_ScrollPanel__Create__ESD()
{
	Ft_Esd_ScrollPanel__ESD *context = (Ft_Esd_ScrollPanel__ESD *)malloc(sizeof(Ft_Esd_ScrollPanel__ESD));
	Ft_Esd_ScrollPanel__Initializer(&context->Instance);
	context->Instance.Parent = context;
	context->Theme = Ft_Esd_Theme_GetCurrent();
	context->Instance.Theme = Ft_Esd_ScrollPanel__Get_Theme__ESD;
	context->X = 0;
	context->Instance.X = Ft_Esd_ScrollPanel__Get_X__ESD;
	context->Y = 0;
	context->Instance.Y = Ft_Esd_ScrollPanel__Get_Y__ESD;
	context->Width = 200;
	context->Instance.Width = Ft_Esd_ScrollPanel__Get_Width__ESD;
	context->Height = 150;
	context->Instance.Height = Ft_Esd_ScrollPanel__Get_Height__ESD;
	context->Columns = 1L;
	context->Instance.Columns = Ft_Esd_ScrollPanel__Get_Columns__ESD;
	context->Margin = 4L;
	context->Instance.Margin = Ft_Esd_ScrollPanel__Get_Margin__ESD;
	return context;
}

void Ft_Esd_ScrollPanel__Destroy__ESD(void *context)
{
	free(context);
}

void Ft_Esd_ScrollPanel__Set_OffsetY__ESD(void *context, int value) { ((Ft_Esd_ScrollPanel__ESD *)context)->Instance.OffsetY = value; }
void Ft_Esd_ScrollPanel__Set_OffsetYRange__ESD(void *context, int value) { ((Ft_Esd_ScrollPanel__ESD *)context)->Instance.OffsetYRange = value; }
void Ft_Esd_ScrollPanel__Set_PreviousTouchY__ESD(void *context, ft_int16_t value) { ((Ft_Esd_ScrollPanel__ESD *)context)->Instance.PreviousTouchY = value; }
void Ft_Esd_ScrollPanel__Set_CurrentX__ESD(void *context, int value) { ((Ft_Esd_ScrollPanel__ESD *)context)->Instance.CurrentX = value; }
void Ft_Esd_ScrollPanel__Set_CurrentY__ESD(void *context, int value) { ((Ft_Esd_ScrollPanel__ESD *)context)->Instance.CurrentY = value; }
void Ft_Esd_ScrollPanel__Set_PreviousOffsetY__ESD(void *context, ft_int16_t value) { ((Ft_Esd_ScrollPanel__ESD *)context)->Instance.PreviousOffsetY = value; }
void Ft_Esd_ScrollPanel__Set_First__ESD(void *context, Ft_Esd_LayoutChild * value) { ((Ft_Esd_ScrollPanel__ESD *)context)->Instance.First = value; }
void Ft_Esd_ScrollPanel__Set_Current__ESD(void *context, Ft_Esd_LayoutChild * value) { ((Ft_Esd_ScrollPanel__ESD *)context)->Instance.Current = value; }

#endif /* ESD_SIMULATION */

/* end of file */
