/*
This file is automatically generated
Ft_Esd_PushButton
C Source
*/

#include "Ft_Esd_PushButton.h"

#include "FT_Esd_CoPro_Cmds.h"
#include "FT_Esd_Dl.h"

extern void Ft_Esd_Noop(void *context);
Ft_Esd_Theme * Ft_Esd_PushButton_Theme__Default(void *context) { return Ft_Esd_Theme_GetCurrent(); }
ft_int16_t Ft_Esd_PushButton_X__Default(void *context) { return 0; }
ft_int16_t Ft_Esd_PushButton_Y__Default(void *context) { return 0; }
ft_int16_t Ft_Esd_PushButton_Width__Default(void *context) { return 120; }
ft_int16_t Ft_Esd_PushButton_Height__Default(void *context) { return 36; }
ft_int16_t Ft_Esd_PushButton_Font__Default(void *context) { return 27; }
const char * Ft_Esd_PushButton_Text__Default(void *context) { return "Button"; }
ft_bool_t Ft_Esd_PushButton_Primary__Default(void *context) { return 1; }

Ft_Esd_Theme * Ft_Esd_Theme_GetCurrent();
Ft_Gpu_Hal_Context_t * Ft_Esd_GetHost();

static void Ft_Esd_PushButton_Touch_Tag_Down__Signal(void *context);
static void Ft_Esd_PushButton_Touch_Tag_Up__Signal(void *context);
static void Ft_Esd_PushButton_Touch_Tag_Tap__Signal(void *context);

void Ft_Esd_PushButton__Initializer(Ft_Esd_PushButton *context)
{
	context->Parent = 0;
	context->Theme = Ft_Esd_PushButton_Theme__Default;
	context->X = Ft_Esd_PushButton_X__Default;
	context->Y = Ft_Esd_PushButton_Y__Default;
	context->Width = Ft_Esd_PushButton_Width__Default;
	context->Height = Ft_Esd_PushButton_Height__Default;
	context->Font = Ft_Esd_PushButton_Font__Default;
	context->Text = Ft_Esd_PushButton_Text__Default;
	context->Down = Ft_Esd_Noop;
	context->Primary = Ft_Esd_PushButton_Primary__Default;
	context->Up = Ft_Esd_Noop;
	Ft_Esd_TouchTag__Initializer(&context->Touch_Tag);
	context->Touch_Tag.Parent = context;
	context->Touch_Tag.Down = Ft_Esd_PushButton_Touch_Tag_Down__Signal;
	context->Touch_Tag.Up = Ft_Esd_PushButton_Touch_Tag_Up__Signal;
	context->Touch_Tag.Tap = Ft_Esd_PushButton_Touch_Tag_Tap__Signal;
	context->Pushed = Ft_Esd_Noop;
}

ft_void_t Ft_Gpu_CoCmd_FgColor(Ft_Gpu_Hal_Context_t *, ft_rgb32_t);
ft_void_t Ft_Gpu_CoCmd_Button(Ft_Gpu_Hal_Context_t *, ft_int16_t, ft_int16_t, ft_int16_t, ft_int16_t, ft_int16_t, ft_uint16_t, const ft_char8_t *);
ft_void_t Ft_Gpu_CoCmd_Number(Ft_Gpu_Hal_Context_t *, ft_int16_t, ft_int16_t, ft_int16_t, ft_uint16_t, ft_int32_t);

void Ft_Esd_PushButton_Render(Ft_Esd_PushButton *context)
{
	void *parent = context->Parent;
	ft_uint8_t alpha = 255;
	Ft_Esd_Dl_COLOR_A(alpha);
	ft_uint8_t s = Ft_Esd_TouchTag_Tag(&context->Touch_Tag);
	Ft_Esd_Dl_TAG(s);
	Ft_Gpu_Hal_Context_t * phost = Ft_Esd_GetHost();
	ft_bool_t if_1 = context->Primary(parent);
	ft_rgb32_t c;
	if (if_1)
	{
		Ft_Esd_Theme * theme = context->Theme(parent);
		c = Ft_Esd_Theme_GetPrimaryColor(theme);
	}
	else
	{
		Ft_Esd_Theme * theme_1 = context->Theme(parent);
		c = Ft_Esd_Theme_GetCurrentColor(theme_1);
	}
	Ft_Gpu_CoCmd_FgColor(phost, c);
	Ft_Esd_Theme * theme_2 = context->Theme(parent);
	ft_rgb32_t c_1 = Ft_Esd_Theme_GetButtonTextColor(theme_2);
	Ft_Esd_Dl_COLOR_RGB(c_1);
	Ft_Gpu_Hal_Context_t * phost_1 = Ft_Esd_GetHost();
	ft_int16_t x = context->X(parent);
	ft_int16_t y = context->Y(parent);
	ft_int16_t width = context->Width(parent);
	ft_int16_t height = context->Height(parent);
	ft_int16_t font = context->Font(parent);
	ft_bool_t if_2 = Ft_Esd_TouchTag_Inside(&context->Touch_Tag);
	ft_uint16_t options;
	if (if_2)
	{
		options = OPT_FLAT;
	}
	else
	{
		options = 0;
	}
	const char * s_1 = context->Text(parent);
	Ft_Gpu_CoCmd_Button(phost_1, x, y, width, height, font, options, s_1);
	ft_uint8_t s_2 = 255;
	Ft_Esd_Dl_TAG(s_2);
}

void Ft_Esd_PushButton_Start(Ft_Esd_PushButton *context)
{
	void *parent = context->Parent;
	Ft_Esd_TouchTag_Start(&context->Touch_Tag);
}

void Ft_Esd_PushButton_Touch_Tag_Down__Signal(void *c)
{
	Ft_Esd_PushButton *context = (Ft_Esd_PushButton *)c;
	void *parent = context->Parent;
	context->Down(parent);
}

void Ft_Esd_PushButton_Touch_Tag_Up__Signal(void *c)
{
	Ft_Esd_PushButton *context = (Ft_Esd_PushButton *)c;
	void *parent = context->Parent;
	context->Up(parent);
}

void Ft_Esd_PushButton_Touch_Tag_Tap__Signal(void *c)
{
	Ft_Esd_PushButton *context = (Ft_Esd_PushButton *)c;
	void *parent = context->Parent;
	context->Pushed(parent);
}

void Ft_Esd_PushButton_Update(Ft_Esd_PushButton *context)
{
	void *parent = context->Parent;
	Ft_Esd_TouchTag_Update(&context->Touch_Tag);
}

ft_bool_t Ft_Esd_PushButton_Pushing(Ft_Esd_PushButton *context)
{
	void *parent = context->Parent;
	return Ft_Esd_TouchTag_Inside(&context->Touch_Tag);
}

void Ft_Esd_PushButton_End(Ft_Esd_PushButton *context)
{
	void *parent = context->Parent;
	Ft_Esd_TouchTag_End(&context->Touch_Tag);
}

#ifdef ESD_SIMULATION
#include <stdlib.h>

typedef struct
{
	Ft_Esd_PushButton Instance;
	Ft_Esd_Theme * Theme;
	ft_int16_t X;
	ft_int16_t Y;
	ft_int16_t Width;
	ft_int16_t Height;
	ft_int16_t Font;
	const char * Text;
	ft_bool_t Primary;
} Ft_Esd_PushButton__ESD;

Ft_Esd_Theme * Ft_Esd_PushButton__Get_Theme__ESD(void *context) { return ((Ft_Esd_PushButton__ESD *)context)->Theme; }
void Ft_Esd_PushButton__Set_Theme__ESD(void *context, Ft_Esd_Theme * value) { ((Ft_Esd_PushButton__ESD *)context)->Theme = value; }
ft_int16_t Ft_Esd_PushButton__Get_X__ESD(void *context) { return ((Ft_Esd_PushButton__ESD *)context)->X; }
void Ft_Esd_PushButton__Set_X__ESD(void *context, ft_int16_t value) { ((Ft_Esd_PushButton__ESD *)context)->X = value; }
ft_int16_t Ft_Esd_PushButton__Get_Y__ESD(void *context) { return ((Ft_Esd_PushButton__ESD *)context)->Y; }
void Ft_Esd_PushButton__Set_Y__ESD(void *context, ft_int16_t value) { ((Ft_Esd_PushButton__ESD *)context)->Y = value; }
ft_int16_t Ft_Esd_PushButton__Get_Width__ESD(void *context) { return ((Ft_Esd_PushButton__ESD *)context)->Width; }
void Ft_Esd_PushButton__Set_Width__ESD(void *context, ft_int16_t value) { ((Ft_Esd_PushButton__ESD *)context)->Width = value; }
ft_int16_t Ft_Esd_PushButton__Get_Height__ESD(void *context) { return ((Ft_Esd_PushButton__ESD *)context)->Height; }
void Ft_Esd_PushButton__Set_Height__ESD(void *context, ft_int16_t value) { ((Ft_Esd_PushButton__ESD *)context)->Height = value; }
ft_int16_t Ft_Esd_PushButton__Get_Font__ESD(void *context) { return ((Ft_Esd_PushButton__ESD *)context)->Font; }
void Ft_Esd_PushButton__Set_Font__ESD(void *context, ft_int16_t value) { ((Ft_Esd_PushButton__ESD *)context)->Font = value; }
const char * Ft_Esd_PushButton__Get_Text__ESD(void *context) { return ((Ft_Esd_PushButton__ESD *)context)->Text; }
void Ft_Esd_PushButton__Set_Text__ESD(void *context, const char * value) { ((Ft_Esd_PushButton__ESD *)context)->Text = value; }
ft_bool_t Ft_Esd_PushButton__Get_Primary__ESD(void *context) { return ((Ft_Esd_PushButton__ESD *)context)->Primary; }
void Ft_Esd_PushButton__Set_Primary__ESD(void *context, ft_bool_t value) { ((Ft_Esd_PushButton__ESD *)context)->Primary = value; }

void *Ft_Esd_PushButton__Create__ESD()
{
	Ft_Esd_PushButton__ESD *context = (Ft_Esd_PushButton__ESD *)malloc(sizeof(Ft_Esd_PushButton__ESD));
	Ft_Esd_PushButton__Initializer(&context->Instance);
	context->Instance.Parent = context;
	context->Theme = Ft_Esd_Theme_GetCurrent();
	context->Instance.Theme = Ft_Esd_PushButton__Get_Theme__ESD;
	context->X = 0;
	context->Instance.X = Ft_Esd_PushButton__Get_X__ESD;
	context->Y = 0;
	context->Instance.Y = Ft_Esd_PushButton__Get_Y__ESD;
	context->Width = 120;
	context->Instance.Width = Ft_Esd_PushButton__Get_Width__ESD;
	context->Height = 36;
	context->Instance.Height = Ft_Esd_PushButton__Get_Height__ESD;
	context->Font = 27;
	context->Instance.Font = Ft_Esd_PushButton__Get_Font__ESD;
	context->Text = "Button";
	context->Instance.Text = Ft_Esd_PushButton__Get_Text__ESD;
	context->Primary = 1;
	context->Instance.Primary = Ft_Esd_PushButton__Get_Primary__ESD;
	return context;
}

void Ft_Esd_PushButton__Destroy__ESD(void *context)
{
	free(context);
}


#endif /* ESD_SIMULATION */

/* end of file */
