/*
This file is automatically generated
LayoutSplit
C Source
*/

#include "LayoutSplit.h"

extern void Ft_Esd_Noop(void *context);
int LayoutSplit_Pos__Default(void *context) { return 0L; }
int LayoutSplit_Length__Default(void *context) { return 0L; }
int LayoutSplit_Numerator__Default(void *context) { return 50L; }
int LayoutSplit_Denominator__Default(void *context) { return 0L; }
int LayoutSplit_Margin__Default(void *context) { return 4L; }



void LayoutSplit__Initializer(LayoutSplit *context)
{
	context->Parent = 0;
	context->Pos = LayoutSplit_Pos__Default;
	context->Length = LayoutSplit_Length__Default;
	context->Numerator = LayoutSplit_Numerator__Default;
	context->Denominator = LayoutSplit_Denominator__Default;
	context->Margin = LayoutSplit_Margin__Default;
}

int LayoutSplit_FirstPos(LayoutSplit *context)
{
	void *parent = context->Parent;
	return context->Pos(parent);
}

int LayoutSplit_SecondPos(LayoutSplit *context)
{
	void *parent = context->Parent;
	int left_1 = context->Pos(parent);
	int left_3 = context->Length(parent);
	int right_1 = context->Numerator(parent);
	int left_2 = left_3 * right_1;
	int right_2 = context->Denominator(parent);
	int right = left_2 / right_2;
	int left = left_1 + right;
	int right_3 = context->Margin(parent);
	return left + right_3;
}

int LayoutSplit_FirstLength(LayoutSplit *context)
{
	void *parent = context->Parent;
	int left_6 = context->Length(parent);
	int right_4 = context->Numerator(parent);
	int left_5 = left_6 * right_4;
	int right_5 = context->Denominator(parent);
	int left_4 = left_5 / right_5;
	int left_7 = context->Margin(parent);
	int right_7 = 2L;
	int right_6 = left_7 / right_7;
	return left_4 - right_6;
}

int LayoutSplit_SecondLength(LayoutSplit *context)
{
	void *parent = context->Parent;
	int left_9 = context->Length(parent);
	int left_11 = context->Length(parent);
	int right_9 = context->Numerator(parent);
	int left_10 = left_11 * right_9;
	int right_10 = context->Denominator(parent);
	int right_8 = left_10 / right_10;
	int left_8 = left_9 - right_8;
	int left_12 = context->Margin(parent);
	int right_12 = 2L;
	int right_11 = left_12 / right_12;
	return left_8 - right_11;
}

#ifdef ESD_SIMULATION
#include <stdlib.h>

typedef struct
{
	LayoutSplit Instance;
	int Pos;
	int Length;
	int Numerator;
	int Denominator;
	int Margin;
} LayoutSplit__ESD;

int LayoutSplit__Get_Pos__ESD(void *context) { return ((LayoutSplit__ESD *)context)->Pos; }
void LayoutSplit__Set_Pos__ESD(void *context, int value) { ((LayoutSplit__ESD *)context)->Pos = value; }
int LayoutSplit__Get_Length__ESD(void *context) { return ((LayoutSplit__ESD *)context)->Length; }
void LayoutSplit__Set_Length__ESD(void *context, int value) { ((LayoutSplit__ESD *)context)->Length = value; }
int LayoutSplit__Get_Numerator__ESD(void *context) { return ((LayoutSplit__ESD *)context)->Numerator; }
void LayoutSplit__Set_Numerator__ESD(void *context, int value) { ((LayoutSplit__ESD *)context)->Numerator = value; }
int LayoutSplit__Get_Denominator__ESD(void *context) { return ((LayoutSplit__ESD *)context)->Denominator; }
void LayoutSplit__Set_Denominator__ESD(void *context, int value) { ((LayoutSplit__ESD *)context)->Denominator = value; }
int LayoutSplit__Get_Margin__ESD(void *context) { return ((LayoutSplit__ESD *)context)->Margin; }
void LayoutSplit__Set_Margin__ESD(void *context, int value) { ((LayoutSplit__ESD *)context)->Margin = value; }

void *LayoutSplit__Create__ESD()
{
	LayoutSplit__ESD *context = (LayoutSplit__ESD *)malloc(sizeof(LayoutSplit__ESD));
	LayoutSplit__Initializer(&context->Instance);
	context->Instance.Parent = context;
	context->Pos = 0L;
	context->Instance.Pos = LayoutSplit__Get_Pos__ESD;
	context->Length = 0L;
	context->Instance.Length = LayoutSplit__Get_Length__ESD;
	context->Numerator = 50L;
	context->Instance.Numerator = LayoutSplit__Get_Numerator__ESD;
	context->Denominator = 0L;
	context->Instance.Denominator = LayoutSplit__Get_Denominator__ESD;
	context->Margin = 4L;
	context->Instance.Margin = LayoutSplit__Get_Margin__ESD;
	return context;
}

void LayoutSplit__Destroy__ESD(void *context)
{
	free(context);
}


#endif /* ESD_SIMULATION */

/* end of file */
