/*
This file is automatically generated
Ft_Esd_ColorPicker
C Source
*/

#include "Ft_Esd_ColorPicker.h"

#include "FT_Esd_Dl.h"
#include "FT_Esd_Primitives.h"

extern void Ft_Esd_Noop(void *context);
int Ft_Esd_ColorPicker_X__Default(void *context) { return 0L; }
int Ft_Esd_ColorPicker_Y__Default(void *context) { return 0L; }



void Ft_Esd_ColorPicker__Initializer(Ft_Esd_ColorPicker *context)
{
	context->Parent = 0;
	context->Bitmap = 0;
	context->Radius = 125L;
	context->X = Ft_Esd_ColorPicker_X__Default;
	context->Y = Ft_Esd_ColorPicker_Y__Default;
	Ft_Esd_TouchTag__Initializer(&context->Touch_Tag);
	context->Touch_Tag.Parent = context;
	context->Color = 0xffffffffUL;
}

static double Ft_Esd_ColorPicker_getSat__return(Ft_Esd_ColorPicker *context);

double getHue(int, int, int, int);
double getSat(int, int, int, int, double);
ft_argb32_t hsvToRgb(double, double, double);
ft_void_t Ft_Esd_Render_Bitmap(ft_int16_t, ft_int16_t, Ft_Esd_BitmapCell *, ft_argb32_t);

void Ft_Esd_ColorPicker_Render(Ft_Esd_ColorPicker *context)
{
	void *parent = context->Parent;
	ft_uint8_t s = Ft_Esd_TouchTag_Tag(&context->Touch_Tag);
	Ft_Esd_Dl_TAG(s);
	int x = context->X(parent);
	int y = context->Y(parent);
	Ft_Esd_BitmapCell * bitmapCell = context->Bitmap;
	ft_argb32_t c = 0xffffffffUL;
	Ft_Esd_Render_Bitmap(x, y, bitmapCell, c);
	ft_uint8_t s_1 = 255;
	Ft_Esd_Dl_TAG(s_1);
}

double Ft_Esd_ColorPicker_getSat__return(Ft_Esd_ColorPicker *context)
{
	void *parent = context->Parent;
	int left = context->X(parent);
	int right = context->Radius;
	int x0 = left + right;
	int left_1 = context->Y(parent);
	int right_1 = context->Radius;
	int y0 = left_1 + right_1;
	ft_int16_t x1 = Ft_Esd_TouchTag_TouchX(&context->Touch_Tag);
	ft_int16_t y1 = Ft_Esd_TouchTag_TouchY(&context->Touch_Tag);
	int r = context->Radius;
	return getSat(x0, y0, x1, y1, r);
}

void Ft_Esd_ColorPicker_Start(Ft_Esd_ColorPicker *context)
{
	void *parent = context->Parent;
	Ft_Esd_TouchTag_Start(&context->Touch_Tag);
}

void Ft_Esd_ColorPicker_Update(Ft_Esd_ColorPicker *context)
{
	void *parent = context->Parent;
	Ft_Esd_TouchTag_Update(&context->Touch_Tag);
	double left_3 = Ft_Esd_ColorPicker_getSat__return(context);
	double right_2 = 1.0;
	int left_2 = left_3 <= right_2;
	ft_bool_t right_3 = Ft_Esd_TouchTag_Touching(&context->Touch_Tag);
	ft_bool_t if_1 = left_2 & right_3;
	ft_argb32_t set_variable;
	if (if_1)
	{
		int left_4 = context->X(parent);
		int right_4 = context->Radius;
		int x0_1 = left_4 + right_4;
		int left_5 = context->Y(parent);
		int right_5 = context->Radius;
		int y0_1 = left_5 + right_5;
		ft_int16_t x1_1 = Ft_Esd_TouchTag_TouchX(&context->Touch_Tag);
		ft_int16_t y1_1 = Ft_Esd_TouchTag_TouchY(&context->Touch_Tag);
		double h = getHue(x0_1, y0_1, x1_1, y1_1);
		double s_2 = Ft_Esd_ColorPicker_getSat__return(context);
		double v = 255.0;
		set_variable = hsvToRgb(h, s_2, v);
	}
	else
	{
		set_variable = context->Color;
	}
	context->Color = set_variable;
}

void Ft_Esd_ColorPicker_End(Ft_Esd_ColorPicker *context)
{
	void *parent = context->Parent;
	Ft_Esd_TouchTag_End(&context->Touch_Tag);
}

#ifdef ESD_SIMULATION
#include <stdlib.h>

typedef struct
{
	Ft_Esd_ColorPicker Instance;
	int X;
	int Y;
} Ft_Esd_ColorPicker__ESD;

int Ft_Esd_ColorPicker__Get_X__ESD(void *context) { return ((Ft_Esd_ColorPicker__ESD *)context)->X; }
void Ft_Esd_ColorPicker__Set_X__ESD(void *context, int value) { ((Ft_Esd_ColorPicker__ESD *)context)->X = value; }
int Ft_Esd_ColorPicker__Get_Y__ESD(void *context) { return ((Ft_Esd_ColorPicker__ESD *)context)->Y; }
void Ft_Esd_ColorPicker__Set_Y__ESD(void *context, int value) { ((Ft_Esd_ColorPicker__ESD *)context)->Y = value; }

void *Ft_Esd_ColorPicker__Create__ESD()
{
	Ft_Esd_ColorPicker__ESD *context = (Ft_Esd_ColorPicker__ESD *)malloc(sizeof(Ft_Esd_ColorPicker__ESD));
	Ft_Esd_ColorPicker__Initializer(&context->Instance);
	context->Instance.Parent = context;
	context->X = 0L;
	context->Instance.X = Ft_Esd_ColorPicker__Get_X__ESD;
	context->Y = 0L;
	context->Instance.Y = Ft_Esd_ColorPicker__Get_Y__ESD;
	return context;
}

void Ft_Esd_ColorPicker__Destroy__ESD(void *context)
{
	free(context);
}

void Ft_Esd_ColorPicker__Set_Bitmap__ESD(void *context, Ft_Esd_BitmapCell * value) { ((Ft_Esd_ColorPicker__ESD *)context)->Instance.Bitmap = value; }
void Ft_Esd_ColorPicker__Set_Radius__ESD(void *context, int value) { ((Ft_Esd_ColorPicker__ESD *)context)->Instance.Radius = value; }
void Ft_Esd_ColorPicker__Set_Color__ESD(void *context, ft_argb32_t value) { ((Ft_Esd_ColorPicker__ESD *)context)->Instance.Color = value; }

#endif /* ESD_SIMULATION */

/* end of file */
