/*
This file is automatically generated
MainPage
C Source
*/

#include "MainPage.h"

extern void Ft_Esd_Noop(void *context);

Ft_Esd_Theme * Ft_Esd_Theme_GetCurrent();
static ft_int16_t MainPage_ESD3_Label_Font__Property(void *context) { return 31; }
static const char * MainPage_ESD3_Label_Text__Property(void *context) { return "ESD3"; }
static ft_int16_t MainPage_ESD3_Label_X__Property(void *context) { return 6; }
static ft_int16_t MainPage_ESD_Push_Button_2_X__Property(void *context) { return 576; }
static ft_int16_t MainPage_ESD_Push_Button_2_Y__Property(void *context) { return 188; }
static const char * MainPage_ESD_Push_Button_2_Text__Property(void *context) { return "Halt"; }
static ft_int16_t MainPage_ESD_Push_Button_X__Property(void *context) { return 573; }
static ft_int16_t MainPage_ESD_Push_Button_Y__Property(void *context) { return 126; }
static const char * MainPage_ESD_Push_Button_Text__Property(void *context) { return "Run"; }
static ft_int16_t MainPage_ESD_SpinBox_X__Property(void *context) { return 18; }
static ft_int16_t MainPage_ESD_SpinBox_Y__Property(void *context) { return 258; }
static ft_int16_t MainPage_ESD_SpinBox_3_X__Property(void *context) { return 527; }
static ft_int16_t MainPage_ESD_SpinBox_3_Y__Property(void *context) { return 258; }
static ft_int16_t MainPage_ESD_SpinBox_2_X__Property(void *context) { return 272; }
static ft_int16_t MainPage_ESD_SpinBox_2_Y__Property(void *context) { return 258; }

static void MainPage_ESD_Timer_2_Fired__Signal(void *context);
static void MainPage_ESD_Timer_Fired__Signal(void *context);
static void MainPage_ESD_Timer_3_Fired__Signal(void *context);
static void MainPage_ESD_Push_Button_2_Pushed__Signal(void *context);
static void MainPage_ESD_Push_Button_Pushed__Signal(void *context);

void MainPage__Initializer(MainPage *context)
{
	context->Parent = 0;
	Ft_Esd_Timer__Initializer(&context->ESD_Timer_2);
	context->ESD_Timer_2.Parent = context;
	context->ESD_Timer_2.TimeoutMs = 300L;
	context->ESD_Timer_2.Repeat = 1;
	context->ESD_Timer_2.Fired = MainPage_ESD_Timer_2_Fired__Signal;
	Ft_Esd_Timer__Initializer(&context->ESD_Timer);
	context->ESD_Timer.Parent = context;
	context->ESD_Timer.Repeat = 1;
	context->ESD_Timer.Fired = MainPage_ESD_Timer_Fired__Signal;
	Ft_Esd_Timer__Initializer(&context->ESD_Timer_3);
	context->ESD_Timer_3.Parent = context;
	context->ESD_Timer_3.TimeoutMs = 90L;
	context->ESD_Timer_3.Repeat = 1;
	context->ESD_Timer_3.Fired = MainPage_ESD_Timer_3_Fired__Signal;
	Ft_Esd_Label__Initializer(&context->ESD3_Label);
	context->ESD3_Label.Parent = context;
	context->ESD3_Label.Font = MainPage_ESD3_Label_Font__Property;
	context->ESD3_Label.Text = MainPage_ESD3_Label_Text__Property;
	context->ESD3_Label.X = MainPage_ESD3_Label_X__Property;
	Ft_Esd_PushButton__Initializer(&context->ESD_Push_Button_2);
	context->ESD_Push_Button_2.Parent = context;
	context->ESD_Push_Button_2.X = MainPage_ESD_Push_Button_2_X__Property;
	context->ESD_Push_Button_2.Y = MainPage_ESD_Push_Button_2_Y__Property;
	context->ESD_Push_Button_2.Text = MainPage_ESD_Push_Button_2_Text__Property;
	context->ESD_Push_Button_2.Pushed = MainPage_ESD_Push_Button_2_Pushed__Signal;
	Ft_Esd_PushButton__Initializer(&context->ESD_Push_Button);
	context->ESD_Push_Button.Parent = context;
	context->ESD_Push_Button.X = MainPage_ESD_Push_Button_X__Property;
	context->ESD_Push_Button.Y = MainPage_ESD_Push_Button_Y__Property;
	context->ESD_Push_Button.Text = MainPage_ESD_Push_Button_Text__Property;
	context->ESD_Push_Button.Pushed = MainPage_ESD_Push_Button_Pushed__Signal;
	Ft_Esd_SpinBox__Initializer(&context->ESD_SpinBox);
	context->ESD_SpinBox.Parent = context;
	context->ESD_SpinBox.X = MainPage_ESD_SpinBox_X__Property;
	context->ESD_SpinBox.Y = MainPage_ESD_SpinBox_Y__Property;
	Ft_Esd_SpinBox__Initializer(&context->ESD_SpinBox_3);
	context->ESD_SpinBox_3.Parent = context;
	context->ESD_SpinBox_3.X = MainPage_ESD_SpinBox_3_X__Property;
	context->ESD_SpinBox_3.Y = MainPage_ESD_SpinBox_3_Y__Property;
	Ft_Esd_SpinBox__Initializer(&context->ESD_SpinBox_2);
	context->ESD_SpinBox_2.Parent = context;
	context->ESD_SpinBox_2.X = MainPage_ESD_SpinBox_2_X__Property;
	context->ESD_SpinBox_2.Y = MainPage_ESD_SpinBox_2_Y__Property;
}

void MainPage_Start(MainPage *context)
{
	void *parent = context->Parent;
	Ft_Esd_PushButton_Start(&context->ESD_Push_Button_2);
	Ft_Esd_PushButton_Start(&context->ESD_Push_Button);
	Ft_Esd_SpinBox_Start(&context->ESD_SpinBox);
	Ft_Esd_SpinBox_Start(&context->ESD_SpinBox_3);
	Ft_Esd_SpinBox_Start(&context->ESD_SpinBox_2);
}

void MainPage_Update(MainPage *context)
{
	void *parent = context->Parent;
	Ft_Esd_PushButton_Update(&context->ESD_Push_Button_2);
	Ft_Esd_PushButton_Update(&context->ESD_Push_Button);
	Ft_Esd_SpinBox_Update(&context->ESD_SpinBox);
	Ft_Esd_SpinBox_Update(&context->ESD_SpinBox_3);
	Ft_Esd_SpinBox_Update(&context->ESD_SpinBox_2);
}

void MainPage_Render(MainPage *context)
{
	void *parent = context->Parent;
	Ft_Esd_Label_Render(&context->ESD3_Label);
	Ft_Esd_PushButton_Render(&context->ESD_Push_Button_2);
	Ft_Esd_PushButton_Render(&context->ESD_Push_Button);
	Ft_Esd_SpinBox_Render(&context->ESD_SpinBox);
	Ft_Esd_SpinBox_Render(&context->ESD_SpinBox_3);
	Ft_Esd_SpinBox_Render(&context->ESD_SpinBox_2);
}

void MainPage_Idle(MainPage *context)
{
	void *parent = context->Parent;
}

void MainPage_End(MainPage *context)
{
	void *parent = context->Parent;
	Ft_Esd_Timer_End(&context->ESD_Timer_2);
	Ft_Esd_Timer_End(&context->ESD_Timer);
	Ft_Esd_Timer_End(&context->ESD_Timer_3);
	Ft_Esd_PushButton_End(&context->ESD_Push_Button_2);
	Ft_Esd_PushButton_End(&context->ESD_Push_Button);
	Ft_Esd_SpinBox_End(&context->ESD_SpinBox);
	Ft_Esd_SpinBox_End(&context->ESD_SpinBox_3);
	Ft_Esd_SpinBox_End(&context->ESD_SpinBox_2);
}

void MainPage_ESD_Timer_2_Fired__Signal(void *c)
{
	MainPage *context = (MainPage *)c;
	void *parent = context->Parent;
	Ft_Esd_SpinBox_Increase(&context->ESD_SpinBox_2);
}

void MainPage_ESD_Timer_Fired__Signal(void *c)
{
	MainPage *context = (MainPage *)c;
	void *parent = context->Parent;
	Ft_Esd_SpinBox_Increase(&context->ESD_SpinBox);
}

void MainPage_ESD_Timer_3_Fired__Signal(void *c)
{
	MainPage *context = (MainPage *)c;
	void *parent = context->Parent;
	Ft_Esd_SpinBox_Increase(&context->ESD_SpinBox_3);
}

void MainPage_ESD_Push_Button_2_Pushed__Signal(void *c)
{
	MainPage *context = (MainPage *)c;
	void *parent = context->Parent;
	Ft_Esd_Timer_Halt(&context->ESD_Timer_2);
	Ft_Esd_Timer_Halt(&context->ESD_Timer);
	Ft_Esd_Timer_Halt(&context->ESD_Timer_3);
}

void MainPage_ESD_Push_Button_Pushed__Signal(void *c)
{
	MainPage *context = (MainPage *)c;
	void *parent = context->Parent;
	Ft_Esd_Timer_Run(&context->ESD_Timer_2);
	Ft_Esd_Timer_Run(&context->ESD_Timer);
	Ft_Esd_Timer_Run(&context->ESD_Timer_3);
}

#ifdef ESD_SIMULATION
#include <stdlib.h>

typedef struct
{
	MainPage Instance;
} MainPage__ESD;


void *MainPage__Create__ESD()
{
	MainPage__ESD *context = (MainPage__ESD *)malloc(sizeof(MainPage__ESD));
	MainPage__Initializer(&context->Instance);
	context->Instance.Parent = context;
	return context;
}

void MainPage__Destroy__ESD(void *context)
{
	free(context);
}


#endif /* ESD_SIMULATION */

/* end of file */
