/*
This file is automatically generated
purdue
C Source
*/

#include "purdue.h"

static Ft_Esd_Theme purdue__Instance = {
	.ClearColor = 0x0,
	.BackColor = 0x0,
	.TextColor = 0xffffff,
	.ButtonTextColor = 0xffffff,
	.DefaultColor = 0x6b6b6b,
	.PrimaryColor = 0xc28e0e,
};

Ft_Esd_Theme *purdue()
{
	return &purdue__Instance;
}

/* end of file */
