/*
This file is automatically generated
Confirmation
Header
*/

#ifndef Confirmation__H
#define Confirmation__H

#include "Ft_Esd.h"
#include "Ft_Esd_Label.h"
#include "Ft_Esd_NumericLabel.h"
#include "Ft_Esd_Theme.h"
#include "Ft_Esd_Timer.h"

#ifndef ESD_LOGIC
#define ESD_LOGIC(name, ...)
#define ESD_ACTOR(name, ...)
#define ESD_WIDGET(name, ...)
#define ESD_PAGE(name, ...)
#define ESD_APPLICATION(name, ...)
#define ESD_INPUT(name, ...)
#define ESD_OUTPUT(name, ...)
#define ESD_SLOT(name, ...)
#define ESD_SIGNAL(name, ...)
#define ESD_VARIABLE(name, ...)
#define ESD_WRITER(name, ...)
#endif

ESD_PAGE(Confirmation, Include = "Confirmation.h", Callback)
typedef struct
{
	void *Parent;
	ESD_SIGNAL(CodeIncorrectTimeout)
	void(* CodeIncorrectTimeout)(void *context);
	ESD_SIGNAL(NoParkingSpotsFound)
	void(* NoParkingSpotsFound)(void *context);
	ESD_SIGNAL(ParkingSpotFound)
	void(* ParkingSpotFound)(void *context);
	ESD_VARIABLE(parkingSpotIDState, Type = int, Public)
	int parkingSpotIDState;
	ESD_VARIABLE(Variable, Type = ft_bool_t, Default = true, Private)
	ft_bool_t Variable;
	ESD_VARIABLE(Variable_2, Type = ft_bool_t, Default = true, Private)
	ft_bool_t Variable_2;
	ESD_VARIABLE(Variable_3, Type = ft_bool_t, Default = true, Private)
	ft_bool_t Variable_3;
	ESD_VARIABLE(parkingSpotNumber, Type = int, Private)
	int parkingSpotNumber;
	Ft_Esd_Timer ESD_Timer;
	Ft_Esd_Timer ESD_Timer_2;
	Ft_Esd_Timer ESD_Timer_3;
	Ft_Esd_Label ESD_Label;
	Ft_Esd_Label ParkingSpotFound_2;
	Ft_Esd_Label Error;
	Ft_Esd_NumericLabel ESD_Numeric_Label;
} Confirmation;

void Confirmation__Initializer(Confirmation *context);

ESD_SLOT(Start)
void Confirmation_Start(Confirmation *context);

ESD_SLOT(Update)
void Confirmation_Update(Confirmation *context);

ESD_SLOT(Render)
void Confirmation_Render(Confirmation *context);

ESD_SLOT(Idle)
void Confirmation_Idle(Confirmation *context);

ESD_SLOT(End)
void Confirmation_End(Confirmation *context);

ESD_SLOT(getParkingSpotID)
void Confirmation_getParkingSpotID(Confirmation *context);

#endif /* Confirmation__H */

/* end of file */
