/*
This file is automatically generated
Ft_Esd_ColorPicker
Header
*/

#ifndef Ft_Esd_ColorPicker__H
#define Ft_Esd_ColorPicker__H

#include "FT_DataTypes.h"
#include "Ft_Esd.h"
#include "Ft_Esd_BitmapInfo.h"
#include "Ft_Esd_TouchTag.h"

#ifndef ESD_LOGIC
#define ESD_LOGIC(name, ...)
#define ESD_ACTOR(name, ...)
#define ESD_WIDGET(name, ...)
#define ESD_PAGE(name, ...)
#define ESD_APPLICATION(name, ...)
#define ESD_INPUT(name, ...)
#define ESD_OUTPUT(name, ...)
#define ESD_SLOT(name, ...)
#define ESD_SIGNAL(name, ...)
#define ESD_VARIABLE(name, ...)
#define ESD_WRITER(name, ...)
#endif

/* Classic circular color picker */
ESD_WIDGET(Ft_Esd_ColorPicker, Include = "Ft_Esd_ColorPicker.h", Callback, DisplayName = "ESD Color Picker", Category = EsdWidgets)
typedef struct
{
	void *Parent;
	ESD_VARIABLE(Bitmap, Type = Ft_Esd_BitmapCell *, Public)
	Ft_Esd_BitmapCell * Bitmap;
	ESD_VARIABLE(Radius, Type = int, Default = 125, Public)
	int Radius;
	ESD_INPUT(X, Type = int)
	int(* X)(void *context);
	ESD_INPUT(Y, Type = int)
	int(* Y)(void *context);
	Ft_Esd_TouchTag Touch_Tag;
	ESD_VARIABLE(Color, Type = ft_argb32_t, Default = #ffffff, ReadOnly)
	ft_argb32_t Color;
} Ft_Esd_ColorPicker;

void Ft_Esd_ColorPicker__Initializer(Ft_Esd_ColorPicker *context);

ESD_SLOT(Render)
void Ft_Esd_ColorPicker_Render(Ft_Esd_ColorPicker *context);

ESD_SLOT(Start)
void Ft_Esd_ColorPicker_Start(Ft_Esd_ColorPicker *context);

ESD_SLOT(Update)
void Ft_Esd_ColorPicker_Update(Ft_Esd_ColorPicker *context);

ESD_SLOT(End)
void Ft_Esd_ColorPicker_End(Ft_Esd_ColorPicker *context);

#endif /* Ft_Esd_ColorPicker__H */

/* end of file */
