/*
This file is automatically generated
Ft_Esd_Gauge
C Source
*/

#include "Ft_Esd_Gauge.h"

#include "FT_Esd_CoPro_Cmds.h"
#include "FT_Esd_Dl.h"
#include "FT_Gpu.h"

extern void Ft_Esd_Noop(void *context);
Ft_Esd_Theme * Ft_Esd_Gauge_Theme__Default(void *context) { return Ft_Esd_Theme_GetCurrent(); }
ft_int16_t Ft_Esd_Gauge_X__Default(void *context) { return 0; }
ft_int16_t Ft_Esd_Gauge_Y__Default(void *context) { return 0; }
ft_int16_t Ft_Esd_Gauge_Width__Default(void *context) { return 144; }
ft_int16_t Ft_Esd_Gauge_Height__Default(void *context) { return 144; }
ft_uint8_t Ft_Esd_Gauge_Alpha__Default(void *context) { return 255; }
ft_uint16_t Ft_Esd_Gauge_Val__Default(void *context) { return 0U; }
ft_uint16_t Ft_Esd_Gauge_Range__Default(void *context) { return 0U; }
ft_uint16_t Ft_Esd_Gauge_Major__Default(void *context) { return 4U; }
ft_uint16_t Ft_Esd_Gauge_Minor__Default(void *context) { return 16U; }

Ft_Gpu_Hal_Context_t * Ft_Esd_GetHost();
Ft_Esd_Theme * Ft_Esd_Theme_GetCurrent();
static ft_int16_t Ft_Esd_Gauge_Ft_Esd_PosSizeToRadius_X__Property(void *context);
static ft_int16_t Ft_Esd_Gauge_Ft_Esd_PosSizeToRadius_Y__Property(void *context);
static ft_int16_t Ft_Esd_Gauge_Ft_Esd_PosSizeToRadius_Width__Property(void *context);
static ft_int16_t Ft_Esd_Gauge_Ft_Esd_PosSizeToRadius_Height__Property(void *context);


void Ft_Esd_Gauge__Initializer(Ft_Esd_Gauge *context)
{
	context->Parent = 0;
	context->Theme = Ft_Esd_Gauge_Theme__Default;
	context->X = Ft_Esd_Gauge_X__Default;
	context->Y = Ft_Esd_Gauge_Y__Default;
	context->Width = Ft_Esd_Gauge_Width__Default;
	context->Height = Ft_Esd_Gauge_Height__Default;
	Ft_Esd_PosSizeToRadius__Initializer(&context->Ft_Esd_PosSizeToRadius);
	context->Ft_Esd_PosSizeToRadius.Parent = context;
	context->Ft_Esd_PosSizeToRadius.X = Ft_Esd_Gauge_Ft_Esd_PosSizeToRadius_X__Property;
	context->Ft_Esd_PosSizeToRadius.Y = Ft_Esd_Gauge_Ft_Esd_PosSizeToRadius_Y__Property;
	context->Ft_Esd_PosSizeToRadius.Width = Ft_Esd_Gauge_Ft_Esd_PosSizeToRadius_Width__Property;
	context->Ft_Esd_PosSizeToRadius.Height = Ft_Esd_Gauge_Ft_Esd_PosSizeToRadius_Height__Property;
	context->Alpha = Ft_Esd_Gauge_Alpha__Default;
	context->Val = Ft_Esd_Gauge_Val__Default;
	context->Range = Ft_Esd_Gauge_Range__Default;
	context->Major = Ft_Esd_Gauge_Major__Default;
	context->Minor = Ft_Esd_Gauge_Minor__Default;
}

ft_void_t Ft_Gpu_CoCmd_BgColor(Ft_Gpu_Hal_Context_t *, ft_rgb32_t);
ft_void_t Ft_Gpu_CoCmd_Gauge(Ft_Gpu_Hal_Context_t *, ft_int16_t, ft_int16_t, ft_int16_t, ft_uint16_t, ft_uint16_t, ft_uint16_t, ft_uint16_t, ft_uint16_t);

void Ft_Esd_Gauge_Render(Ft_Esd_Gauge *context)
{
	void *parent = context->Parent;
	ft_uint8_t alpha = context->Alpha(parent);
	Ft_Esd_Dl_COLOR_A(alpha);
	Ft_Gpu_Hal_Context_t * phost = Ft_Esd_GetHost();
	Ft_Esd_Theme * theme = context->Theme(parent);
	ft_rgb32_t c = Ft_Esd_Theme_GetBackColor(theme);
	Ft_Gpu_CoCmd_BgColor(phost, c);
	Ft_Esd_Theme * theme_1 = context->Theme(parent);
	ft_rgb32_t c_1 = Ft_Esd_Theme_GetTextColor(theme_1);
	Ft_Esd_Dl_COLOR_RGB(c_1);
	Ft_Gpu_Hal_Context_t * phost_1 = Ft_Esd_GetHost();
	ft_int16_t x = Ft_Esd_PosSizeToRadius_CenterX(&context->Ft_Esd_PosSizeToRadius);
	ft_int16_t y = Ft_Esd_PosSizeToRadius_CenterY(&context->Ft_Esd_PosSizeToRadius);
	ft_int16_t r = Ft_Esd_PosSizeToRadius_Radius(&context->Ft_Esd_PosSizeToRadius);
	ft_uint16_t options = 0;
	ft_uint16_t major = context->Major(parent);
	ft_uint16_t minor = context->Minor(parent);
	ft_uint16_t val = context->Val(parent);
	ft_uint16_t range = context->Range(parent);
	Ft_Gpu_CoCmd_Gauge(phost_1, x, y, r, options, major, minor, val, range);
}

ft_int16_t Ft_Esd_Gauge_Ft_Esd_PosSizeToRadius_X__Property(void *c)
{
	Ft_Esd_Gauge *context = (Ft_Esd_Gauge *)c;
	void *parent = context->Parent;
	return context->X(parent);
}

ft_int16_t Ft_Esd_Gauge_Ft_Esd_PosSizeToRadius_Y__Property(void *c)
{
	Ft_Esd_Gauge *context = (Ft_Esd_Gauge *)c;
	void *parent = context->Parent;
	return context->Y(parent);
}

ft_int16_t Ft_Esd_Gauge_Ft_Esd_PosSizeToRadius_Width__Property(void *c)
{
	Ft_Esd_Gauge *context = (Ft_Esd_Gauge *)c;
	void *parent = context->Parent;
	return context->Width(parent);
}

ft_int16_t Ft_Esd_Gauge_Ft_Esd_PosSizeToRadius_Height__Property(void *c)
{
	Ft_Esd_Gauge *context = (Ft_Esd_Gauge *)c;
	void *parent = context->Parent;
	return context->Height(parent);
}

#ifdef ESD_SIMULATION
#include <stdlib.h>

typedef struct
{
	Ft_Esd_Gauge Instance;
	Ft_Esd_Theme * Theme;
	ft_int16_t X;
	ft_int16_t Y;
	ft_int16_t Width;
	ft_int16_t Height;
	ft_uint8_t Alpha;
	ft_uint16_t Val;
	ft_uint16_t Range;
	ft_uint16_t Major;
	ft_uint16_t Minor;
} Ft_Esd_Gauge__ESD;

Ft_Esd_Theme * Ft_Esd_Gauge__Get_Theme__ESD(void *context) { return ((Ft_Esd_Gauge__ESD *)context)->Theme; }
void Ft_Esd_Gauge__Set_Theme__ESD(void *context, Ft_Esd_Theme * value) { ((Ft_Esd_Gauge__ESD *)context)->Theme = value; }
ft_int16_t Ft_Esd_Gauge__Get_X__ESD(void *context) { return ((Ft_Esd_Gauge__ESD *)context)->X; }
void Ft_Esd_Gauge__Set_X__ESD(void *context, ft_int16_t value) { ((Ft_Esd_Gauge__ESD *)context)->X = value; }
ft_int16_t Ft_Esd_Gauge__Get_Y__ESD(void *context) { return ((Ft_Esd_Gauge__ESD *)context)->Y; }
void Ft_Esd_Gauge__Set_Y__ESD(void *context, ft_int16_t value) { ((Ft_Esd_Gauge__ESD *)context)->Y = value; }
ft_int16_t Ft_Esd_Gauge__Get_Width__ESD(void *context) { return ((Ft_Esd_Gauge__ESD *)context)->Width; }
void Ft_Esd_Gauge__Set_Width__ESD(void *context, ft_int16_t value) { ((Ft_Esd_Gauge__ESD *)context)->Width = value; }
ft_int16_t Ft_Esd_Gauge__Get_Height__ESD(void *context) { return ((Ft_Esd_Gauge__ESD *)context)->Height; }
void Ft_Esd_Gauge__Set_Height__ESD(void *context, ft_int16_t value) { ((Ft_Esd_Gauge__ESD *)context)->Height = value; }
ft_uint8_t Ft_Esd_Gauge__Get_Alpha__ESD(void *context) { return ((Ft_Esd_Gauge__ESD *)context)->Alpha; }
void Ft_Esd_Gauge__Set_Alpha__ESD(void *context, ft_uint8_t value) { ((Ft_Esd_Gauge__ESD *)context)->Alpha = value; }
ft_uint16_t Ft_Esd_Gauge__Get_Val__ESD(void *context) { return ((Ft_Esd_Gauge__ESD *)context)->Val; }
void Ft_Esd_Gauge__Set_Val__ESD(void *context, ft_uint16_t value) { ((Ft_Esd_Gauge__ESD *)context)->Val = value; }
ft_uint16_t Ft_Esd_Gauge__Get_Range__ESD(void *context) { return ((Ft_Esd_Gauge__ESD *)context)->Range; }
void Ft_Esd_Gauge__Set_Range__ESD(void *context, ft_uint16_t value) { ((Ft_Esd_Gauge__ESD *)context)->Range = value; }
ft_uint16_t Ft_Esd_Gauge__Get_Major__ESD(void *context) { return ((Ft_Esd_Gauge__ESD *)context)->Major; }
void Ft_Esd_Gauge__Set_Major__ESD(void *context, ft_uint16_t value) { ((Ft_Esd_Gauge__ESD *)context)->Major = value; }
ft_uint16_t Ft_Esd_Gauge__Get_Minor__ESD(void *context) { return ((Ft_Esd_Gauge__ESD *)context)->Minor; }
void Ft_Esd_Gauge__Set_Minor__ESD(void *context, ft_uint16_t value) { ((Ft_Esd_Gauge__ESD *)context)->Minor = value; }

void *Ft_Esd_Gauge__Create__ESD()
{
	Ft_Esd_Gauge__ESD *context = (Ft_Esd_Gauge__ESD *)malloc(sizeof(Ft_Esd_Gauge__ESD));
	Ft_Esd_Gauge__Initializer(&context->Instance);
	context->Instance.Parent = context;
	context->Theme = Ft_Esd_Theme_GetCurrent();
	context->Instance.Theme = Ft_Esd_Gauge__Get_Theme__ESD;
	context->X = 0;
	context->Instance.X = Ft_Esd_Gauge__Get_X__ESD;
	context->Y = 0;
	context->Instance.Y = Ft_Esd_Gauge__Get_Y__ESD;
	context->Width = 144;
	context->Instance.Width = Ft_Esd_Gauge__Get_Width__ESD;
	context->Height = 144;
	context->Instance.Height = Ft_Esd_Gauge__Get_Height__ESD;
	context->Alpha = 255;
	context->Instance.Alpha = Ft_Esd_Gauge__Get_Alpha__ESD;
	context->Val = 0U;
	context->Instance.Val = Ft_Esd_Gauge__Get_Val__ESD;
	context->Range = 0U;
	context->Instance.Range = Ft_Esd_Gauge__Get_Range__ESD;
	context->Major = 4U;
	context->Instance.Major = Ft_Esd_Gauge__Get_Major__ESD;
	context->Minor = 16U;
	context->Instance.Minor = Ft_Esd_Gauge__Get_Minor__ESD;
	return context;
}

void Ft_Esd_Gauge__Destroy__ESD(void *context)
{
	free(context);
}


#endif /* ESD_SIMULATION */

/* end of file */
