/*
This file is automatically generated
Ft_Esd_ImageButton
Header
*/

#ifndef Ft_Esd_ImageButton__H
#define Ft_Esd_ImageButton__H

#include "FT_DataTypes.h"
#include "Ft_Esd.h"
#include "Ft_Esd_BitmapInfo.h"
#include "Ft_Esd_DefaultTheme.h"
#include "Ft_Esd_Theme.h"
#include "Ft_Esd_TouchTag.h"

#ifndef ESD_LOGIC
#define ESD_LOGIC(name, ...)
#define ESD_ACTOR(name, ...)
#define ESD_WIDGET(name, ...)
#define ESD_PAGE(name, ...)
#define ESD_APPLICATION(name, ...)
#define ESD_INPUT(name, ...)
#define ESD_OUTPUT(name, ...)
#define ESD_SLOT(name, ...)
#define ESD_SIGNAL(name, ...)
#define ESD_VARIABLE(name, ...)
#define ESD_WRITER(name, ...)
#endif

/* Push button with image support */
ESD_WIDGET(Ft_Esd_ImageButton, Include = "Ft_Esd_ImageButton.h", Callback, DisplayName = "ESD Image Button", Category = EsdWidgets, DefaultSignal = Pushed, Icon = ":/icons/ui-button.png")
typedef struct
{
	void *Parent;
	ESD_INPUT(Theme, Type = Ft_Esd_Theme *, EditRole = Library, Default = Ft_Esd_Theme_GetCurrent)
	Ft_Esd_Theme *(* Theme)(void *context);
	ESD_INPUT(X, Type = ft_int16_t, Default = 0)
	ft_int16_t(* X)(void *context);
	ESD_INPUT(Y, Type = ft_int16_t, Default = 0)
	ft_int16_t(* Y)(void *context);
	ESD_INPUT(BitmapNormal, DisplayName = "Bitmap Normal", Type = Ft_Esd_BitmapCell *)
	Ft_Esd_BitmapCell *(* BitmapNormal)(void *context);
	ESD_INPUT(BitmapPressed, DisplayName = "Bitmap Pressed", Type = Ft_Esd_BitmapCell *)
	Ft_Esd_BitmapCell *(* BitmapPressed)(void *context);
	ESD_SIGNAL(Down)
	void(* Down)(void *context);
	ESD_SIGNAL(Up)
	void(* Up)(void *context);
	Ft_Esd_TouchTag Touch_Tag;
	ESD_SIGNAL(Pushed)
	void(* Pushed)(void *context);
} Ft_Esd_ImageButton;

void Ft_Esd_ImageButton__Initializer(Ft_Esd_ImageButton *context);

ESD_SLOT(Render)
void Ft_Esd_ImageButton_Render(Ft_Esd_ImageButton *context);

ESD_SLOT(Start)
void Ft_Esd_ImageButton_Start(Ft_Esd_ImageButton *context);

ESD_SLOT(Update)
void Ft_Esd_ImageButton_Update(Ft_Esd_ImageButton *context);

ESD_OUTPUT(Pushing, Type = ft_bool_t)
ft_bool_t Ft_Esd_ImageButton_Pushing(Ft_Esd_ImageButton *context);

ESD_SLOT(End)
void Ft_Esd_ImageButton_End(Ft_Esd_ImageButton *context);

#endif /* Ft_Esd_ImageButton__H */

/* end of file */
