/*
This file is automatically generated
Ft_Esd_Toggle
Header
*/

#ifndef Ft_Esd_Toggle__H
#define Ft_Esd_Toggle__H

#include "FT_DataTypes.h"
#include "Ft_Esd.h"
#include "Ft_Esd_DefaultTheme.h"
#include "Ft_Esd_Theme.h"
#include "Ft_Esd_TouchTag.h"

#ifndef ESD_LOGIC
#define ESD_LOGIC(name, ...)
#define ESD_ACTOR(name, ...)
#define ESD_WIDGET(name, ...)
#define ESD_PAGE(name, ...)
#define ESD_APPLICATION(name, ...)
#define ESD_INPUT(name, ...)
#define ESD_OUTPUT(name, ...)
#define ESD_SLOT(name, ...)
#define ESD_SIGNAL(name, ...)
#define ESD_VARIABLE(name, ...)
#define ESD_WRITER(name, ...)
#endif

/* EVE builtin toggle button */
ESD_WIDGET(Ft_Esd_Toggle, Include = "Ft_Esd_Toggle.h", Callback, DisplayName = "ESD Toggle", Category = EsdWidgets, Icon = ":/icons/ui-button-toggle.png")
typedef struct
{
	void *Parent;
	ESD_INPUT(Theme, Type = Ft_Esd_Theme *, Default = Ft_Esd_Theme_GetCurrent)
	Ft_Esd_Theme *(* Theme)(void *context);
	ESD_INPUT(X, Type = ft_int16_t, Default = 0)
	ft_int16_t(* X)(void *context);
	ESD_INPUT(Y, Type = ft_int16_t, Default = 0)
	ft_int16_t(* Y)(void *context);
	ESD_INPUT(Width, Type = ft_int16_t, Max = 4096, Default = 80)
	ft_int16_t(* Width)(void *context);
	ESD_INPUT(Height, Type = ft_int16_t, Max = 4096, Default = 36)
	ft_int16_t(* Height)(void *context);
	ESD_INPUT(Font, Type = ft_int16_t, Min = 0, Max = 31, Default = 27)
	ft_int16_t(* Font)(void *context);
	ESD_INPUT(Text, Type = const char *, Default = "Toggle")
	const char *(* Text)(void *context);
	Ft_Esd_TouchTag Touch_Tag;
	ESD_SIGNAL(Toggled)
	void(* Toggled)(void *context);
	ESD_VARIABLE(State, Type = ft_bool_t, Public)
	ft_bool_t State;
	ESD_WRITER(Changed, Type = ft_bool_t)
	void(* Changed)(void *context, ft_bool_t value);
} Ft_Esd_Toggle;

void Ft_Esd_Toggle__Initializer(Ft_Esd_Toggle *context);

ESD_SLOT(Render)
void Ft_Esd_Toggle_Render(Ft_Esd_Toggle *context);

ESD_SLOT(Start)
void Ft_Esd_Toggle_Start(Ft_Esd_Toggle *context);

ESD_SLOT(Update)
void Ft_Esd_Toggle_Update(Ft_Esd_Toggle *context);

ESD_SLOT(End)
void Ft_Esd_Toggle_End(Ft_Esd_Toggle *context);

ESD_SLOT(Toggle)
void Ft_Esd_Toggle_Toggle(Ft_Esd_Toggle *context);

#endif /* Ft_Esd_Toggle__H */

/* end of file */
