/*
This file is automatically generated
Ft_Esd_CheckBox
C Source
*/

#include "Ft_Esd_CheckBox.h"

#include "FT_Esd_Dl.h"
#include "FT_Esd_Primitives.h"
#include "Ft_Esd_Elements.h"

extern void Ft_Esd_Noop(void *context);
Ft_Esd_Theme * Ft_Esd_CheckBox_Theme__Default(void *context) { return Ft_Esd_Theme_GetCurrent(); }
ft_uint8_t Ft_Esd_CheckBox_Font__Default(void *context) { return 27; }
int Ft_Esd_CheckBox_X__Default(void *context) { return 0L; }
int Ft_Esd_CheckBox_Y__Default(void *context) { return 0L; }
int Ft_Esd_CheckBox_Width__Default(void *context) { return 20L; }
int Ft_Esd_CheckBox_Height__Default(void *context) { return 20L; }
ft_uint8_t Ft_Esd_CheckBox_Alpha__Default(void *context) { return 255; }
char * Ft_Esd_CheckBox_Text__Default(void *context) { return "Option"; }
void Ft_Esd_CheckBox_Changed__Noop(void *context, ft_bool_t value) { }

Ft_Esd_Theme * Ft_Esd_Theme_GetCurrent();
static Ft_Esd_Theme * Ft_Esd_CheckBox_ESD_Label_Theme__Property(void *context);
static ft_int16_t Ft_Esd_CheckBox_ESD_Label_Font__Property(void *context);
static const char * Ft_Esd_CheckBox_ESD_Label_Text__Property(void *context);
static ft_int16_t Ft_Esd_CheckBox_ESD_Label_X__Property(void *context);
static ft_int16_t Ft_Esd_CheckBox_ESD_Label_Y__Property(void *context);
static ft_int16_t Ft_Esd_CheckBox_ESD_Label_Width__Property(void *context);
static ft_int16_t Ft_Esd_CheckBox_ESD_Label_Height__Property(void *context);
static ft_uint16_t Ft_Esd_CheckBox_ESD_Label_AlignY__Property(void *context) { return 1; }

static void Ft_Esd_CheckBox_Touch_Tag_Tap__Signal(void *context);

void Ft_Esd_CheckBox__Initializer(Ft_Esd_CheckBox *context)
{
	context->Parent = 0;
	Ft_Esd_TouchTag__Initializer(&context->Touch_Tag);
	context->Touch_Tag.Parent = context;
	context->Touch_Tag.Tap = Ft_Esd_CheckBox_Touch_Tag_Tap__Signal;
	context->Theme = Ft_Esd_CheckBox_Theme__Default;
	context->Font = Ft_Esd_CheckBox_Font__Default;
	context->X = Ft_Esd_CheckBox_X__Default;
	context->Y = Ft_Esd_CheckBox_Y__Default;
	context->Width = Ft_Esd_CheckBox_Width__Default;
	context->Height = Ft_Esd_CheckBox_Height__Default;
	context->Alpha = Ft_Esd_CheckBox_Alpha__Default;
	context->Text = Ft_Esd_CheckBox_Text__Default;
	context->Value = 0;
	context->Toggled = Ft_Esd_Noop;
	context->Changed = Ft_Esd_CheckBox_Changed__Noop;
	Ft_Esd_Label__Initializer(&context->ESD_Label);
	context->ESD_Label.Parent = context;
	context->ESD_Label.Theme = Ft_Esd_CheckBox_ESD_Label_Theme__Property;
	context->ESD_Label.Font = Ft_Esd_CheckBox_ESD_Label_Font__Property;
	context->ESD_Label.Text = Ft_Esd_CheckBox_ESD_Label_Text__Property;
	context->ESD_Label.X = Ft_Esd_CheckBox_ESD_Label_X__Property;
	context->ESD_Label.Y = Ft_Esd_CheckBox_ESD_Label_Y__Property;
	context->ESD_Label.Width = Ft_Esd_CheckBox_ESD_Label_Width__Property;
	context->ESD_Label.Height = Ft_Esd_CheckBox_ESD_Label_Height__Property;
	context->ESD_Label.AlignY = Ft_Esd_CheckBox_ESD_Label_AlignY__Property;
}

static ft_argb32_t Ft_Esd_CheckBox_Color_A_RGB_Combine__return(Ft_Esd_CheckBox *context);

void Ft_Esd_Elements_PanelSunken(ft_rgb32_t, ft_int16_t, ft_int16_t, ft_int16_t, ft_int16_t, ft_int16_t);

void Ft_Esd_CheckBox_Render(Ft_Esd_CheckBox *context)
{
	void *parent = context->Parent;
	ft_uint8_t alpha = context->Alpha(parent);
	Ft_Esd_Dl_COLOR_A(alpha);
	ft_uint8_t s = Ft_Esd_TouchTag_Tag(&context->Touch_Tag);
	Ft_Esd_Dl_TAG(s);
	Ft_Esd_Theme * theme = context->Theme(parent);
	ft_rgb32_t color = Ft_Esd_Theme_GetBackColor(theme);
	int x = context->X(parent);
	int y = context->Y(parent);
	int left = context->Width(parent);
	int right = context->Height(parent);
	int if_1 = left <= right;
	int width;
	if (if_1)
	{
		width = context->Width(parent);
	}
	else
	{
		width = context->Height(parent);
	}
	int height = context->Height(parent);
	ft_int16_t radius = 4;
	Ft_Esd_Elements_PanelSunken(color, x, y, width, height, radius);
	ft_bool_t left_1 = context->Value;
	ft_bool_t right_1 = Ft_Esd_TouchTag_Inside(&context->Touch_Tag);
	int if_2 = left_1 || right_1;
	if (if_2)
	{
		int left_3 = context->X(parent);
		int left_5 = context->Width(parent);
		int right_3 = context->Height(parent);
		int if_3 = left_5 <= right_3;
		int left_4;
		if (if_3)
		{
			left_4 = context->Width(parent);
		}
		else
		{
			left_4 = context->Height(parent);
		}
		int right_4 = 10L;
		int right_2 = left_4 / right_4;
		int left_2 = left_3 + right_2;
		int left_7 = context->Width(parent);
		int right_6 = context->Height(parent);
		int if_4 = left_7 <= right_6;
		int left_6;
		if (if_4)
		{
			left_6 = context->Width(parent);
		}
		else
		{
			left_6 = context->Height(parent);
		}
		int right_7 = 10L;
		int right_5 = left_6 / right_7;
		int x0 = left_2 + right_5;
		int left_8 = context->Y(parent);
		int left_10 = context->Width(parent);
		int right_9 = context->Height(parent);
		int if_5 = left_10 <= right_9;
		int left_9;
		if (if_5)
		{
			left_9 = context->Width(parent);
		}
		else
		{
			left_9 = context->Height(parent);
		}
		int right_10 = 2L;
		int right_8 = left_9 / right_10;
		int y0 = left_8 + right_8;
		int left_11 = context->X(parent);
		int left_13 = context->Width(parent);
		int right_12 = context->Height(parent);
		int if_6 = left_13 <= right_12;
		int left_12;
		if (if_6)
		{
			left_12 = context->Width(parent);
		}
		else
		{
			left_12 = context->Height(parent);
		}
		int right_13 = 3L;
		int right_11 = left_12 / right_13;
		int x1 = left_11 + right_11;
		int left_16 = context->Y(parent);
		int left_17 = context->Width(parent);
		int right_15 = context->Height(parent);
		int if_7 = left_17 <= right_15;
		int right_14;
		if (if_7)
		{
			right_14 = context->Width(parent);
		}
		else
		{
			right_14 = context->Height(parent);
		}
		int left_15 = left_16 + right_14;
		int left_19 = context->Width(parent);
		int right_17 = context->Height(parent);
		int if_8 = left_19 <= right_17;
		int left_18;
		if (if_8)
		{
			left_18 = context->Width(parent);
		}
		else
		{
			left_18 = context->Height(parent);
		}
		int right_18 = 10L;
		int right_16 = left_18 / right_18;
		int left_14 = left_15 - right_16;
		int left_21 = context->Width(parent);
		int right_20 = context->Height(parent);
		int if_9 = left_21 <= right_20;
		int left_20;
		if (if_9)
		{
			left_20 = context->Width(parent);
		}
		else
		{
			left_20 = context->Height(parent);
		}
		int right_21 = 10L;
		int right_19 = left_20 / right_21;
		int y1 = left_14 - right_19;
		int left_24 = context->Width(parent);
		int right_22 = context->Height(parent);
		int if_10 = left_24 <= right_22;
		int left_23;
		if (if_10)
		{
			left_23 = context->Width(parent);
		}
		else
		{
			left_23 = context->Height(parent);
		}
		int right_23 = 10L;
		int left_22 = left_23 / right_23;
		int right_24 = 2L;
		int width_1 = left_22 * right_24;
		ft_argb32_t color_1 = Ft_Esd_CheckBox_Color_A_RGB_Combine__return(context);
		Ft_Esd_Render_Line(x0, y0, x1, y1, width_1, color_1);
		int left_25 = context->X(parent);
		int left_27 = context->Width(parent);
		int right_26 = context->Height(parent);
		int if_11 = left_27 <= right_26;
		int left_26;
		if (if_11)
		{
			left_26 = context->Width(parent);
		}
		else
		{
			left_26 = context->Height(parent);
		}
		int right_27 = 3L;
		int right_25 = left_26 / right_27;
		int x0_1 = left_25 + right_25;
		int left_30 = context->Y(parent);
		int left_31 = context->Width(parent);
		int right_29 = context->Height(parent);
		int if_12 = left_31 <= right_29;
		int right_28;
		if (if_12)
		{
			right_28 = context->Width(parent);
		}
		else
		{
			right_28 = context->Height(parent);
		}
		int left_29 = left_30 + right_28;
		int left_33 = context->Width(parent);
		int right_31 = context->Height(parent);
		int if_13 = left_33 <= right_31;
		int left_32;
		if (if_13)
		{
			left_32 = context->Width(parent);
		}
		else
		{
			left_32 = context->Height(parent);
		}
		int right_32 = 10L;
		int right_30 = left_32 / right_32;
		int left_28 = left_29 - right_30;
		int left_35 = context->Width(parent);
		int right_34 = context->Height(parent);
		int if_14 = left_35 <= right_34;
		int left_34;
		if (if_14)
		{
			left_34 = context->Width(parent);
		}
		else
		{
			left_34 = context->Height(parent);
		}
		int right_35 = 10L;
		int right_33 = left_34 / right_35;
		int y0_1 = left_28 - right_33;
		int left_38 = context->X(parent);
		int left_39 = context->Width(parent);
		int right_37 = context->Height(parent);
		int if_15 = left_39 <= right_37;
		int right_36;
		if (if_15)
		{
			right_36 = context->Width(parent);
		}
		else
		{
			right_36 = context->Height(parent);
		}
		int left_37 = left_38 + right_36;
		int left_41 = context->Width(parent);
		int right_39 = context->Height(parent);
		int if_16 = left_41 <= right_39;
		int left_40;
		if (if_16)
		{
			left_40 = context->Width(parent);
		}
		else
		{
			left_40 = context->Height(parent);
		}
		int right_40 = 10L;
		int right_38 = left_40 / right_40;
		int left_36 = left_37 - right_38;
		int left_43 = context->Width(parent);
		int right_42 = context->Height(parent);
		int if_17 = left_43 <= right_42;
		int left_42;
		if (if_17)
		{
			left_42 = context->Width(parent);
		}
		else
		{
			left_42 = context->Height(parent);
		}
		int right_43 = 10L;
		int right_41 = left_42 / right_43;
		int x1_1 = left_36 - right_41;
		int left_45 = context->Y(parent);
		int left_47 = context->Width(parent);
		int right_45 = context->Height(parent);
		int if_18 = left_47 <= right_45;
		int left_46;
		if (if_18)
		{
			left_46 = context->Width(parent);
		}
		else
		{
			left_46 = context->Height(parent);
		}
		int right_46 = 10L;
		int right_44 = left_46 / right_46;
		int left_44 = left_45 + right_44;
		int left_49 = context->Width(parent);
		int right_48 = context->Height(parent);
		int if_19 = left_49 <= right_48;
		int left_48;
		if (if_19)
		{
			left_48 = context->Width(parent);
		}
		else
		{
			left_48 = context->Height(parent);
		}
		int right_49 = 10L;
		int right_47 = left_48 / right_49;
		int y1_1 = left_44 + right_47;
		int left_52 = context->Width(parent);
		int right_50 = context->Height(parent);
		int if_20 = left_52 <= right_50;
		int left_51;
		if (if_20)
		{
			left_51 = context->Width(parent);
		}
		else
		{
			left_51 = context->Height(parent);
		}
		int right_51 = 10L;
		int left_50 = left_51 / right_51;
		int right_52 = 2L;
		int width_2 = left_50 * right_52;
		ft_argb32_t color_2 = Ft_Esd_CheckBox_Color_A_RGB_Combine__return(context);
		Ft_Esd_Render_Line(x0_1, y0_1, x1_1, y1_1, width_2, color_2);
	}
	else
	{
	}
	ft_uint8_t s_1 = 255;
	Ft_Esd_Dl_TAG(s_1);
	Ft_Esd_Label_Render(&context->ESD_Label);
}

void Ft_Esd_CheckBox_Touch_Tag_Tap__Signal(void *c)
{
	Ft_Esd_CheckBox *context = (Ft_Esd_CheckBox *)c;
	void *parent = context->Parent;
	ft_bool_t value = context->Value;
	int set_variable = !value;
	context->Value = set_variable;
	context->Changed(parent, set_variable);
	context->Toggled(parent);
}

void Ft_Esd_CheckBox_Start(Ft_Esd_CheckBox *context)
{
	void *parent = context->Parent;
	Ft_Esd_TouchTag_Start(&context->Touch_Tag);
}

void Ft_Esd_CheckBox_Update(Ft_Esd_CheckBox *context)
{
	void *parent = context->Parent;
	Ft_Esd_TouchTag_Update(&context->Touch_Tag);
}

void Ft_Esd_CheckBox_End(Ft_Esd_CheckBox *context)
{
	void *parent = context->Parent;
	Ft_Esd_TouchTag_End(&context->Touch_Tag);
}

ft_argb32_t Ft_Esd_CheckBox_Color_A_RGB_Combine__return(Ft_Esd_CheckBox *context)
{
	void *parent = context->Parent;
	ft_bool_t if_21 = Ft_Esd_TouchTag_Inside(&context->Touch_Tag);
	ft_rgb32_t rgb;
	if (if_21)
	{
		Ft_Esd_Theme * theme_1 = context->Theme(parent);
		rgb = Ft_Esd_Theme_GetTextColor(theme_1);
	}
	else
	{
		Ft_Esd_Theme * theme_2 = context->Theme(parent);
		rgb = Ft_Esd_Theme_GetPrimaryColor(theme_2);
	}
	ft_uint8_t a = context->Alpha(parent);
	return Ft_Esd_ColorARGB_Combine(rgb, a);
}

void Ft_Esd_CheckBox_Toggle(Ft_Esd_CheckBox *context)
{
	void *parent = context->Parent;
	ft_bool_t value_1 = context->Value;
	int set_variable_1 = !value_1;
	context->Value = set_variable_1;
	context->Changed(parent, set_variable_1);
	context->Toggled(parent);
}

Ft_Esd_Theme * Ft_Esd_CheckBox_ESD_Label_Theme__Property(void *c)
{
	Ft_Esd_CheckBox *context = (Ft_Esd_CheckBox *)c;
	void *parent = context->Parent;
	return context->Theme(parent);
}

ft_int16_t Ft_Esd_CheckBox_ESD_Label_Font__Property(void *c)
{
	Ft_Esd_CheckBox *context = (Ft_Esd_CheckBox *)c;
	void *parent = context->Parent;
	return context->Font(parent);
}

const char * Ft_Esd_CheckBox_ESD_Label_Text__Property(void *c)
{
	Ft_Esd_CheckBox *context = (Ft_Esd_CheckBox *)c;
	void *parent = context->Parent;
	return context->Text(parent);
}

ft_int16_t Ft_Esd_CheckBox_ESD_Label_X__Property(void *c)
{
	Ft_Esd_CheckBox *context = (Ft_Esd_CheckBox *)c;
	void *parent = context->Parent;
	int left_54 = context->X(parent);
	int left_55 = context->Width(parent);
	int right_54 = context->Height(parent);
	int if_22 = left_55 <= right_54;
	int right_53;
	if (if_22)
	{
		right_53 = context->Width(parent);
	}
	else
	{
		right_53 = context->Height(parent);
	}
	int left_53 = left_54 + right_53;
	int left_58 = context->Width(parent);
	int right_56 = context->Height(parent);
	int if_23 = left_58 <= right_56;
	int left_57;
	if (if_23)
	{
		left_57 = context->Width(parent);
	}
	else
	{
		left_57 = context->Height(parent);
	}
	ft_uint8_t i = context->Font(parent);
	ft_uint16_t right_57 = Ft_Esd_GetFontHeight(i);
	int left_56 = left_57 + right_57;
	int right_58 = 4L;
	int right_55 = left_56 / right_58;
	return left_53 + right_55;
}

ft_int16_t Ft_Esd_CheckBox_ESD_Label_Y__Property(void *c)
{
	Ft_Esd_CheckBox *context = (Ft_Esd_CheckBox *)c;
	void *parent = context->Parent;
	return context->Y(parent);
}

ft_int16_t Ft_Esd_CheckBox_ESD_Label_Width__Property(void *c)
{
	Ft_Esd_CheckBox *context = (Ft_Esd_CheckBox *)c;
	void *parent = context->Parent;
	return context->Width(parent);
}

ft_int16_t Ft_Esd_CheckBox_ESD_Label_Height__Property(void *c)
{
	Ft_Esd_CheckBox *context = (Ft_Esd_CheckBox *)c;
	void *parent = context->Parent;
	return context->Height(parent);
}

#ifdef ESD_SIMULATION
#include <stdlib.h>

typedef struct
{
	Ft_Esd_CheckBox Instance;
	Ft_Esd_Theme * Theme;
	ft_uint8_t Font;
	int X;
	int Y;
	int Width;
	int Height;
	ft_uint8_t Alpha;
	char * Text;
} Ft_Esd_CheckBox__ESD;

Ft_Esd_Theme * Ft_Esd_CheckBox__Get_Theme__ESD(void *context) { return ((Ft_Esd_CheckBox__ESD *)context)->Theme; }
void Ft_Esd_CheckBox__Set_Theme__ESD(void *context, Ft_Esd_Theme * value) { ((Ft_Esd_CheckBox__ESD *)context)->Theme = value; }
ft_uint8_t Ft_Esd_CheckBox__Get_Font__ESD(void *context) { return ((Ft_Esd_CheckBox__ESD *)context)->Font; }
void Ft_Esd_CheckBox__Set_Font__ESD(void *context, ft_uint8_t value) { ((Ft_Esd_CheckBox__ESD *)context)->Font = value; }
int Ft_Esd_CheckBox__Get_X__ESD(void *context) { return ((Ft_Esd_CheckBox__ESD *)context)->X; }
void Ft_Esd_CheckBox__Set_X__ESD(void *context, int value) { ((Ft_Esd_CheckBox__ESD *)context)->X = value; }
int Ft_Esd_CheckBox__Get_Y__ESD(void *context) { return ((Ft_Esd_CheckBox__ESD *)context)->Y; }
void Ft_Esd_CheckBox__Set_Y__ESD(void *context, int value) { ((Ft_Esd_CheckBox__ESD *)context)->Y = value; }
int Ft_Esd_CheckBox__Get_Width__ESD(void *context) { return ((Ft_Esd_CheckBox__ESD *)context)->Width; }
void Ft_Esd_CheckBox__Set_Width__ESD(void *context, int value) { ((Ft_Esd_CheckBox__ESD *)context)->Width = value; }
int Ft_Esd_CheckBox__Get_Height__ESD(void *context) { return ((Ft_Esd_CheckBox__ESD *)context)->Height; }
void Ft_Esd_CheckBox__Set_Height__ESD(void *context, int value) { ((Ft_Esd_CheckBox__ESD *)context)->Height = value; }
ft_uint8_t Ft_Esd_CheckBox__Get_Alpha__ESD(void *context) { return ((Ft_Esd_CheckBox__ESD *)context)->Alpha; }
void Ft_Esd_CheckBox__Set_Alpha__ESD(void *context, ft_uint8_t value) { ((Ft_Esd_CheckBox__ESD *)context)->Alpha = value; }
char * Ft_Esd_CheckBox__Get_Text__ESD(void *context) { return ((Ft_Esd_CheckBox__ESD *)context)->Text; }
void Ft_Esd_CheckBox__Set_Text__ESD(void *context, char * value) { ((Ft_Esd_CheckBox__ESD *)context)->Text = value; }

void *Ft_Esd_CheckBox__Create__ESD()
{
	Ft_Esd_CheckBox__ESD *context = (Ft_Esd_CheckBox__ESD *)malloc(sizeof(Ft_Esd_CheckBox__ESD));
	Ft_Esd_CheckBox__Initializer(&context->Instance);
	context->Instance.Parent = context;
	context->Theme = Ft_Esd_Theme_GetCurrent();
	context->Instance.Theme = Ft_Esd_CheckBox__Get_Theme__ESD;
	context->Font = 27;
	context->Instance.Font = Ft_Esd_CheckBox__Get_Font__ESD;
	context->X = 0L;
	context->Instance.X = Ft_Esd_CheckBox__Get_X__ESD;
	context->Y = 0L;
	context->Instance.Y = Ft_Esd_CheckBox__Get_Y__ESD;
	context->Width = 20L;
	context->Instance.Width = Ft_Esd_CheckBox__Get_Width__ESD;
	context->Height = 20L;
	context->Instance.Height = Ft_Esd_CheckBox__Get_Height__ESD;
	context->Alpha = 255;
	context->Instance.Alpha = Ft_Esd_CheckBox__Get_Alpha__ESD;
	context->Text = "Option";
	context->Instance.Text = Ft_Esd_CheckBox__Get_Text__ESD;
	return context;
}

void Ft_Esd_CheckBox__Destroy__ESD(void *context)
{
	free(context);
}

void Ft_Esd_CheckBox__Set_Value__ESD(void *context, ft_bool_t value) { ((Ft_Esd_CheckBox__ESD *)context)->Instance.Value = value; }

#endif /* ESD_SIMULATION */

/* end of file */
