/*
This file is automatically generated
Ft_Esd_ScrollPanel
Header
*/

#ifndef Ft_Esd_ScrollPanel__H
#define Ft_Esd_ScrollPanel__H

#include "Ft_Esd.h"
#include "Ft_Esd_Layout.h"
#include "Ft_Esd_Theme.h"
#include "Ft_Esd_TouchArea.h"

#ifndef ESD_LOGIC
#define ESD_LOGIC(name, ...)
#define ESD_ACTOR(name, ...)
#define ESD_WIDGET(name, ...)
#define ESD_PAGE(name, ...)
#define ESD_APPLICATION(name, ...)
#define ESD_INPUT(name, ...)
#define ESD_OUTPUT(name, ...)
#define ESD_SLOT(name, ...)
#define ESD_SIGNAL(name, ...)
#define ESD_VARIABLE(name, ...)
#define ESD_WRITER(name, ...)
#endif

/* Visible area handling scroll action */
ESD_WIDGET(Ft_Esd_ScrollPanel, Include = "Ft_Esd_ScrollPanel.h", Callback, DisplayName = "ESD Scroll Panel", Category = EsdWidgets)
typedef struct
{
	void *Parent;
	Ft_Esd_TouchArea TouchArea;
	ESD_INPUT(Theme, Type = Ft_Esd_Theme *, Default = Ft_Esd_Theme_GetCurrent)
	Ft_Esd_Theme *(* Theme)(void *context);
	ESD_INPUT(X, Type = ft_int16_t)
	ft_int16_t(* X)(void *context);
	ESD_INPUT(Y, Type = ft_int16_t)
	ft_int16_t(* Y)(void *context);
	ESD_INPUT(Width, Type = ft_int16_t, Default = 200)
	ft_int16_t(* Width)(void *context);
	ESD_INPUT(Height, Type = ft_int16_t, Default = 150)
	ft_int16_t(* Height)(void *context);
	ESD_INPUT(Columns, Type = int, Min = 1, Default = 1)
	int(* Columns)(void *context);
	ESD_VARIABLE(OffsetY, Type = int, Public)
	int OffsetY;
	ESD_INPUT(Margin, Type = int, Default = 4)
	int(* Margin)(void *context);
	ESD_VARIABLE(OffsetYRange, Type = int, ReadOnly)
	int OffsetYRange;
	ESD_VARIABLE(PreviousTouchY, Type = ft_int16_t, Private)
	ft_int16_t PreviousTouchY;
	ESD_WRITER(OffsetYChanged, Type = ft_int16_t)
	void(* OffsetYChanged)(void *context, ft_int16_t value);
	ESD_VARIABLE(CurrentX, Type = int, Private)
	int CurrentX;
	ESD_VARIABLE(CurrentY, Type = int, Private)
	int CurrentY;
	ESD_VARIABLE(PreviousOffsetY, Type = ft_int16_t, Private)
	ft_int16_t PreviousOffsetY;
	ESD_VARIABLE(First, DisplayName = "First Widget", Type = Ft_Esd_LayoutChild *, ReadOnly)
	Ft_Esd_LayoutChild * First;
	ESD_VARIABLE(Current, DisplayName = "Current Widget", Type = Ft_Esd_LayoutChild *, ReadOnly)
	Ft_Esd_LayoutChild * Current;
} Ft_Esd_ScrollPanel;

void Ft_Esd_ScrollPanel__Initializer(Ft_Esd_ScrollPanel *context);

ESD_SLOT(Render)
void Ft_Esd_ScrollPanel_Render(Ft_Esd_ScrollPanel *context);

ESD_SLOT(Update)
void Ft_Esd_ScrollPanel_Update(Ft_Esd_ScrollPanel *context);

#endif /* Ft_Esd_ScrollPanel__H */

/* end of file */
