/*
This file is automatically generated
Ft_Esd_ProgressBar
Header
*/

#ifndef Ft_Esd_ProgressBar__H
#define Ft_Esd_ProgressBar__H

#include "FT_DataTypes.h"
#include "Ft_Esd.h"
#include "Ft_Esd_DefaultTheme.h"
#include "Ft_Esd_Theme.h"

#ifndef ESD_LOGIC
#define ESD_LOGIC(name, ...)
#define ESD_ACTOR(name, ...)
#define ESD_WIDGET(name, ...)
#define ESD_PAGE(name, ...)
#define ESD_APPLICATION(name, ...)
#define ESD_INPUT(name, ...)
#define ESD_OUTPUT(name, ...)
#define ESD_SLOT(name, ...)
#define ESD_SIGNAL(name, ...)
#define ESD_VARIABLE(name, ...)
#define ESD_WRITER(name, ...)
#endif

/* EVE builtin progress bar widget */
ESD_WIDGET(Ft_Esd_ProgressBar, Include = "Ft_Esd_ProgressBar.h", Callback, DisplayName = "ESD Progress Bar", Category = EsdWidgets, Icon = ":/icons/ui-progress-bar.png")
typedef struct
{
	void *Parent;
	ESD_INPUT(Theme, Type = Ft_Esd_Theme *)
	Ft_Esd_Theme *(* Theme)(void *context);
	ESD_INPUT(X, Type = ft_int16_t, Default = 50)
	ft_int16_t(* X)(void *context);
	ESD_INPUT(Y, Type = ft_int16_t, Default = 50)
	ft_int16_t(* Y)(void *context);
	ESD_INPUT(Width, Type = ft_int16_t, Max = 4096, Default = 180)
	ft_int16_t(* Width)(void *context);
	ESD_INPUT(Height, Type = ft_int16_t, Max = 4096, Default = 24)
	ft_int16_t(* Height)(void *context);
	ESD_INPUT(Val, DisplayName = "Value", Type = ft_uint16_t, Max = 65535, Default = 0)
	ft_uint16_t(* Val)(void *context);
	ESD_INPUT(Range, DisplayName = "Range", Type = ft_uint16_t, Max = 65535, Default = 65535)
	ft_uint16_t(* Range)(void *context);
} Ft_Esd_ProgressBar;

void Ft_Esd_ProgressBar__Initializer(Ft_Esd_ProgressBar *context);

ESD_SLOT(Render)
void Ft_Esd_ProgressBar_Render(Ft_Esd_ProgressBar *context);

#endif /* Ft_Esd_ProgressBar__H */

/* end of file */
