/*
This file is automatically generated
Ft_Esd_RadioButton
C Source
*/

#include "Ft_Esd_RadioButton.h"

#include "FT_Esd_Dl.h"
#include "Ft_Esd_Elements.h"

extern void Ft_Esd_Noop(void *context);
Ft_Esd_Theme * Ft_Esd_RadioButton_Theme__Default(void *context) { return Ft_Esd_Theme_GetCurrent(); }
int Ft_Esd_RadioButton_X__Default(void *context) { return 0L; }
int Ft_Esd_RadioButton_Y__Default(void *context) { return 0L; }
int Ft_Esd_RadioButton_Width__Default(void *context) { return 20L; }
int Ft_Esd_RadioButton_Height__Default(void *context) { return 20L; }
Ft_Esd_RadioGroup * Ft_Esd_RadioButton_RadioGroup__Default(void *context) { return 0x0; }
void Ft_Esd_RadioButton_Changed__Noop(void *context, ft_bool_t value) { }
int Ft_Esd_RadioButton_Font__Default(void *context) { return 27L; }
char * Ft_Esd_RadioButton_Text__Default(void *context) { return "Option"; }

Ft_Esd_Theme * Ft_Esd_Theme_GetCurrent();
static Ft_Esd_Theme * Ft_Esd_RadioButton_ESD_Label_Theme__Property(void *context);
static ft_int16_t Ft_Esd_RadioButton_ESD_Label_Font__Property(void *context);
static const char * Ft_Esd_RadioButton_ESD_Label_Text__Property(void *context);
static ft_int16_t Ft_Esd_RadioButton_ESD_Label_X__Property(void *context);
static ft_int16_t Ft_Esd_RadioButton_ESD_Label_Y__Property(void *context);
static ft_int16_t Ft_Esd_RadioButton_ESD_Label_Width__Property(void *context);
static ft_int16_t Ft_Esd_RadioButton_ESD_Label_Height__Property(void *context);
static ft_uint16_t Ft_Esd_RadioButton_ESD_Label_AlignY__Property(void *context) { return 1; }

static void Ft_Esd_RadioButton_Touch_Tag_Tap__Signal(void *context);

void Ft_Esd_RadioButton__Initializer(Ft_Esd_RadioButton *context)
{
	context->Parent = 0;
	Ft_Esd_TouchTag__Initializer(&context->Touch_Tag);
	context->Touch_Tag.Parent = context;
	context->Touch_Tag.Tap = Ft_Esd_RadioButton_Touch_Tag_Tap__Signal;
	context->Theme = Ft_Esd_RadioButton_Theme__Default;
	context->X = Ft_Esd_RadioButton_X__Default;
	context->Y = Ft_Esd_RadioButton_Y__Default;
	context->Width = Ft_Esd_RadioButton_Width__Default;
	context->Height = Ft_Esd_RadioButton_Height__Default;
	context->RadioGroup = Ft_Esd_RadioButton_RadioGroup__Default;
	context->Checked = Ft_Esd_Noop;
	context->Changed = Ft_Esd_RadioButton_Changed__Noop;
	context->Font = Ft_Esd_RadioButton_Font__Default;
	context->Text = Ft_Esd_RadioButton_Text__Default;
	Ft_Esd_Label__Initializer(&context->ESD_Label);
	context->ESD_Label.Parent = context;
	context->ESD_Label.Theme = Ft_Esd_RadioButton_ESD_Label_Theme__Property;
	context->ESD_Label.Font = Ft_Esd_RadioButton_ESD_Label_Font__Property;
	context->ESD_Label.Text = Ft_Esd_RadioButton_ESD_Label_Text__Property;
	context->ESD_Label.X = Ft_Esd_RadioButton_ESD_Label_X__Property;
	context->ESD_Label.Y = Ft_Esd_RadioButton_ESD_Label_Y__Property;
	context->ESD_Label.Width = Ft_Esd_RadioButton_ESD_Label_Width__Property;
	context->ESD_Label.Height = Ft_Esd_RadioButton_ESD_Label_Height__Property;
	context->ESD_Label.AlignY = Ft_Esd_RadioButton_ESD_Label_AlignY__Property;
}

static ft_bool_t Ft_Esd_RadioButton_Is_Checked__return(Ft_Esd_RadioButton *context);

void Ft_Esd_RadioButton_Check_Signal(Ft_Esd_RadioButton *context);
ft_bool_t Ft_Esd_RadioButton_IsChecked(Ft_Esd_RadioButton *context);
void Ft_Esd_Elements_CircleSunken(ft_rgb32_t, ft_int16_t, ft_int16_t, ft_int16_t);
void Ft_Esd_Elements_CircleFlat(ft_rgb32_t, ft_int16_t, ft_int16_t, ft_int16_t);

void Ft_Esd_RadioButton_Render(Ft_Esd_RadioButton *context)
{
	void *parent = context->Parent;
	ft_uint8_t alpha = 255;
	Ft_Esd_Dl_COLOR_A(alpha);
	ft_uint8_t s = Ft_Esd_TouchTag_Tag(&context->Touch_Tag);
	Ft_Esd_Dl_TAG(s);
	Ft_Esd_Theme * theme = context->Theme(parent);
	ft_rgb32_t color = Ft_Esd_Theme_GetBackColor(theme);
	int left = context->X(parent);
	int left_2 = context->Width(parent);
	int right_1 = context->Height(parent);
	int if_1 = left_2 <= right_1;
	int left_1;
	if (if_1)
	{
		left_1 = context->Width(parent);
	}
	else
	{
		left_1 = context->Height(parent);
	}
	int right_2 = 2L;
	int right = left_1 / right_2;
	int x = left + right;
	int left_3 = context->Y(parent);
	int left_4 = context->Height(parent);
	int right_4 = 2L;
	int right_3 = left_4 / right_4;
	int y = left_3 + right_3;
	int left_6 = context->Width(parent);
	int right_5 = context->Height(parent);
	int if_2 = left_6 <= right_5;
	int left_5;
	if (if_2)
	{
		left_5 = context->Width(parent);
	}
	else
	{
		left_5 = context->Height(parent);
	}
	int right_6 = 2L;
	int radius = left_5 / right_6;
	Ft_Esd_Elements_CircleSunken(color, x, y, radius);
	Ft_Esd_Label_Render(&context->ESD_Label);
	ft_bool_t left_7 = Ft_Esd_RadioButton_Is_Checked__return(context);
	ft_bool_t right_7 = Ft_Esd_TouchTag_Inside(&context->Touch_Tag);
	int if_3 = left_7 || right_7;
	if (if_3)
	{
		ft_bool_t if_4 = Ft_Esd_TouchTag_Inside(&context->Touch_Tag);
		int color_1;
		if (if_4)
		{
			Ft_Esd_Theme * theme_1 = context->Theme(parent);
			color_1 = Ft_Esd_Theme_GetTextColor(theme_1);
		}
		else
		{
			Ft_Esd_Theme * theme_2 = context->Theme(parent);
			color_1 = Ft_Esd_Theme_GetPrimaryColor(theme_2);
		}
		int left_8 = context->X(parent);
		int left_10 = context->Width(parent);
		int right_9 = context->Height(parent);
		int if_5 = left_10 <= right_9;
		int left_9;
		if (if_5)
		{
			left_9 = context->Width(parent);
		}
		else
		{
			left_9 = context->Height(parent);
		}
		int right_10 = 2L;
		int right_8 = left_9 / right_10;
		int x_1 = left_8 + right_8;
		int left_11 = context->Y(parent);
		int left_12 = context->Height(parent);
		int right_12 = 2L;
		int right_11 = left_12 / right_12;
		int y_1 = left_11 + right_11;
		int left_14 = context->Width(parent);
		int right_13 = context->Height(parent);
		int if_6 = left_14 <= right_13;
		int left_13;
		if (if_6)
		{
			left_13 = context->Width(parent);
		}
		else
		{
			left_13 = context->Height(parent);
		}
		int right_14 = 3L;
		int radius_1 = left_13 / right_14;
		Ft_Esd_Elements_CircleFlat(color_1, x_1, y_1, radius_1);
		ft_uint8_t s_1 = 255;
		Ft_Esd_Dl_TAG(s_1);
	}
	else
	{
		ft_uint8_t s_2 = 255;
		Ft_Esd_Dl_TAG(s_2);
	}
}

void Ft_Esd_RadioButton_Touch_Tag_Tap__Signal(void *c)
{
	Ft_Esd_RadioButton *context = (Ft_Esd_RadioButton *)c;
	void *parent = context->Parent;
	Ft_Esd_RadioButton_Check_Signal(context);
	context->Checked(parent);
	ft_bool_t set_variable = Ft_Esd_RadioButton_Is_Checked__return(context);
	context->Changed(parent, set_variable);
}

void Ft_Esd_RadioButton_Start(Ft_Esd_RadioButton *context)
{
	void *parent = context->Parent;
	Ft_Esd_TouchTag_Start(&context->Touch_Tag);
}

void Ft_Esd_RadioButton_Update(Ft_Esd_RadioButton *context)
{
	void *parent = context->Parent;
	Ft_Esd_TouchTag_Update(&context->Touch_Tag);
}

void Ft_Esd_RadioButton_End(Ft_Esd_RadioButton *context)
{
	void *parent = context->Parent;
	Ft_Esd_TouchTag_End(&context->Touch_Tag);
}

void Ft_Esd_RadioButton_Check(Ft_Esd_RadioButton *context)
{
	void *parent = context->Parent;
	Ft_Esd_RadioButton_Check_Signal(context);
	context->Checked(parent);
	ft_bool_t set_variable_1 = Ft_Esd_RadioButton_Is_Checked__return(context);
	context->Changed(parent, set_variable_1);
}

ft_bool_t Ft_Esd_RadioButton_Is_Checked__return(Ft_Esd_RadioButton *context)
{
	void *parent = context->Parent;
	return Ft_Esd_RadioButton_IsChecked(context);
}

ft_bool_t Ft_Esd_RadioButton_Value(Ft_Esd_RadioButton *context)
{
	void *parent = context->Parent;
	return Ft_Esd_RadioButton_Is_Checked__return(context);
}

Ft_Esd_Theme * Ft_Esd_RadioButton_ESD_Label_Theme__Property(void *c)
{
	Ft_Esd_RadioButton *context = (Ft_Esd_RadioButton *)c;
	void *parent = context->Parent;
	return context->Theme(parent);
}

ft_int16_t Ft_Esd_RadioButton_ESD_Label_Font__Property(void *c)
{
	Ft_Esd_RadioButton *context = (Ft_Esd_RadioButton *)c;
	void *parent = context->Parent;
	return context->Font(parent);
}

const char * Ft_Esd_RadioButton_ESD_Label_Text__Property(void *c)
{
	Ft_Esd_RadioButton *context = (Ft_Esd_RadioButton *)c;
	void *parent = context->Parent;
	return context->Text(parent);
}

ft_int16_t Ft_Esd_RadioButton_ESD_Label_X__Property(void *c)
{
	Ft_Esd_RadioButton *context = (Ft_Esd_RadioButton *)c;
	void *parent = context->Parent;
	int left_16 = context->X(parent);
	int left_17 = context->Width(parent);
	int right_16 = context->Height(parent);
	int if_7 = left_17 <= right_16;
	int right_15;
	if (if_7)
	{
		right_15 = context->Width(parent);
	}
	else
	{
		right_15 = context->Height(parent);
	}
	int left_15 = left_16 + right_15;
	int i = context->Font(parent);
	ft_uint16_t left_19 = Ft_Esd_GetFontHeight(i);
	int left_20 = context->Width(parent);
	int right_19 = context->Height(parent);
	int if_8 = left_20 <= right_19;
	int right_18;
	if (if_8)
	{
		right_18 = context->Width(parent);
	}
	else
	{
		right_18 = context->Height(parent);
	}
	int left_18 = left_19 + right_18;
	int right_20 = 4L;
	int right_17 = left_18 / right_20;
	return left_15 + right_17;
}

ft_int16_t Ft_Esd_RadioButton_ESD_Label_Y__Property(void *c)
{
	Ft_Esd_RadioButton *context = (Ft_Esd_RadioButton *)c;
	void *parent = context->Parent;
	return context->Y(parent);
}

ft_int16_t Ft_Esd_RadioButton_ESD_Label_Width__Property(void *c)
{
	Ft_Esd_RadioButton *context = (Ft_Esd_RadioButton *)c;
	void *parent = context->Parent;
	return context->Width(parent);
}

ft_int16_t Ft_Esd_RadioButton_ESD_Label_Height__Property(void *c)
{
	Ft_Esd_RadioButton *context = (Ft_Esd_RadioButton *)c;
	void *parent = context->Parent;
	return context->Height(parent);
}

#ifdef ESD_SIMULATION
#include <stdlib.h>

typedef struct
{
	Ft_Esd_RadioButton Instance;
	Ft_Esd_Theme * Theme;
	int X;
	int Y;
	int Width;
	int Height;
	Ft_Esd_RadioGroup * RadioGroup;
	int Font;
	char * Text;
} Ft_Esd_RadioButton__ESD;

Ft_Esd_Theme * Ft_Esd_RadioButton__Get_Theme__ESD(void *context) { return ((Ft_Esd_RadioButton__ESD *)context)->Theme; }
void Ft_Esd_RadioButton__Set_Theme__ESD(void *context, Ft_Esd_Theme * value) { ((Ft_Esd_RadioButton__ESD *)context)->Theme = value; }
int Ft_Esd_RadioButton__Get_X__ESD(void *context) { return ((Ft_Esd_RadioButton__ESD *)context)->X; }
void Ft_Esd_RadioButton__Set_X__ESD(void *context, int value) { ((Ft_Esd_RadioButton__ESD *)context)->X = value; }
int Ft_Esd_RadioButton__Get_Y__ESD(void *context) { return ((Ft_Esd_RadioButton__ESD *)context)->Y; }
void Ft_Esd_RadioButton__Set_Y__ESD(void *context, int value) { ((Ft_Esd_RadioButton__ESD *)context)->Y = value; }
int Ft_Esd_RadioButton__Get_Width__ESD(void *context) { return ((Ft_Esd_RadioButton__ESD *)context)->Width; }
void Ft_Esd_RadioButton__Set_Width__ESD(void *context, int value) { ((Ft_Esd_RadioButton__ESD *)context)->Width = value; }
int Ft_Esd_RadioButton__Get_Height__ESD(void *context) { return ((Ft_Esd_RadioButton__ESD *)context)->Height; }
void Ft_Esd_RadioButton__Set_Height__ESD(void *context, int value) { ((Ft_Esd_RadioButton__ESD *)context)->Height = value; }
Ft_Esd_RadioGroup * Ft_Esd_RadioButton__Get_RadioGroup__ESD(void *context) { return ((Ft_Esd_RadioButton__ESD *)context)->RadioGroup; }
void Ft_Esd_RadioButton__Set_RadioGroup__ESD(void *context, Ft_Esd_RadioGroup * value) { ((Ft_Esd_RadioButton__ESD *)context)->RadioGroup = value; }
int Ft_Esd_RadioButton__Get_Font__ESD(void *context) { return ((Ft_Esd_RadioButton__ESD *)context)->Font; }
void Ft_Esd_RadioButton__Set_Font__ESD(void *context, int value) { ((Ft_Esd_RadioButton__ESD *)context)->Font = value; }
char * Ft_Esd_RadioButton__Get_Text__ESD(void *context) { return ((Ft_Esd_RadioButton__ESD *)context)->Text; }
void Ft_Esd_RadioButton__Set_Text__ESD(void *context, char * value) { ((Ft_Esd_RadioButton__ESD *)context)->Text = value; }

void *Ft_Esd_RadioButton__Create__ESD()
{
	Ft_Esd_RadioButton__ESD *context = (Ft_Esd_RadioButton__ESD *)malloc(sizeof(Ft_Esd_RadioButton__ESD));
	Ft_Esd_RadioButton__Initializer(&context->Instance);
	context->Instance.Parent = context;
	context->Theme = Ft_Esd_Theme_GetCurrent();
	context->Instance.Theme = Ft_Esd_RadioButton__Get_Theme__ESD;
	context->X = 0L;
	context->Instance.X = Ft_Esd_RadioButton__Get_X__ESD;
	context->Y = 0L;
	context->Instance.Y = Ft_Esd_RadioButton__Get_Y__ESD;
	context->Width = 20L;
	context->Instance.Width = Ft_Esd_RadioButton__Get_Width__ESD;
	context->Height = 20L;
	context->Instance.Height = Ft_Esd_RadioButton__Get_Height__ESD;
	context->RadioGroup = 0x0;
	context->Instance.RadioGroup = Ft_Esd_RadioButton__Get_RadioGroup__ESD;
	context->Font = 27L;
	context->Instance.Font = Ft_Esd_RadioButton__Get_Font__ESD;
	context->Text = "Option";
	context->Instance.Text = Ft_Esd_RadioButton__Get_Text__ESD;
	return context;
}

void Ft_Esd_RadioButton__Destroy__ESD(void *context)
{
	free(context);
}


#endif /* ESD_SIMULATION */

/* end of file */
