/*
This file is automatically generated
Ft_Esd_Clock
C Source
*/

#include "Ft_Esd_Clock.h"

#include "FT_Esd_CoPro_Cmds.h"
#include "FT_Esd_Dl.h"
#include "FT_Gpu.h"

extern void Ft_Esd_Noop(void *context);
Ft_Esd_Theme * Ft_Esd_Clock_Theme__Default(void *context) { return Ft_Esd_Theme_GetCurrent(); }
ft_int16_t Ft_Esd_Clock_X__Default(void *context) { return 0; }
ft_int16_t Ft_Esd_Clock_Y__Default(void *context) { return 0; }
ft_int16_t Ft_Esd_Clock_Width__Default(void *context) { return 144; }
ft_int16_t Ft_Esd_Clock_Height__Default(void *context) { return 144; }
uint8_t Ft_Esd_Clock_Alpha__Default(void *context) { return 255; }
ft_uint16_t Ft_Esd_Clock_H__Default(void *context) { return 0U; }
ft_uint16_t Ft_Esd_Clock_M__Default(void *context) { return 0U; }
ft_uint16_t Ft_Esd_Clock_S__Default(void *context) { return 0U; }
ft_uint32_t Ft_Esd_Clock_Ms__Default(void *context) { return 0UL; }
ft_bool_t Ft_Esd_Clock_Interactive__Default(void *context) { return 0; }

Ft_Esd_Theme * Ft_Esd_Theme_GetCurrent();
Ft_Gpu_Hal_Context_t * Ft_Esd_GetHost();
static ft_int16_t Ft_Esd_Clock_Ft_Esd_PosSizeToRadius_X__Property(void *context);
static ft_int16_t Ft_Esd_Clock_Ft_Esd_PosSizeToRadius_Y__Property(void *context);
static ft_int16_t Ft_Esd_Clock_Ft_Esd_PosSizeToRadius_Width__Property(void *context);
static ft_int16_t Ft_Esd_Clock_Ft_Esd_PosSizeToRadius_Height__Property(void *context);


void Ft_Esd_Clock__Initializer(Ft_Esd_Clock *context)
{
	context->Parent = 0;
	context->Theme = Ft_Esd_Clock_Theme__Default;
	context->X = Ft_Esd_Clock_X__Default;
	context->Y = Ft_Esd_Clock_Y__Default;
	Ft_Esd_PosSizeToRadius__Initializer(&context->Ft_Esd_PosSizeToRadius);
	context->Ft_Esd_PosSizeToRadius.Parent = context;
	context->Ft_Esd_PosSizeToRadius.X = Ft_Esd_Clock_Ft_Esd_PosSizeToRadius_X__Property;
	context->Ft_Esd_PosSizeToRadius.Y = Ft_Esd_Clock_Ft_Esd_PosSizeToRadius_Y__Property;
	context->Ft_Esd_PosSizeToRadius.Width = Ft_Esd_Clock_Ft_Esd_PosSizeToRadius_Width__Property;
	context->Ft_Esd_PosSizeToRadius.Height = Ft_Esd_Clock_Ft_Esd_PosSizeToRadius_Height__Property;
	context->Width = Ft_Esd_Clock_Width__Default;
	context->Height = Ft_Esd_Clock_Height__Default;
	context->Alpha = Ft_Esd_Clock_Alpha__Default;
	context->H = Ft_Esd_Clock_H__Default;
	context->M = Ft_Esd_Clock_M__Default;
	context->S = Ft_Esd_Clock_S__Default;
	context->Ms = Ft_Esd_Clock_Ms__Default;
	Ft_Esd_TouchTag__Initializer(&context->Touch_Tag);
	context->Touch_Tag.Parent = context;
	context->Interactive = Ft_Esd_Clock_Interactive__Default;
}

ft_void_t Ft_Gpu_CoCmd_BgColor(Ft_Gpu_Hal_Context_t *, ft_rgb32_t);
ft_void_t Ft_Gpu_CoCmd_Clock(Ft_Gpu_Hal_Context_t *, ft_int16_t, ft_int16_t, ft_int16_t, ft_uint16_t, ft_uint16_t, ft_uint16_t, ft_uint16_t, ft_uint16_t);

void Ft_Esd_Clock_Render(Ft_Esd_Clock *context)
{
	void *parent = context->Parent;
	uint8_t alpha = context->Alpha(parent);
	Ft_Esd_Dl_COLOR_A(alpha);
	Ft_Gpu_Hal_Context_t * phost = Ft_Esd_GetHost();
	Ft_Esd_Theme * theme = context->Theme(parent);
	ft_rgb32_t c = Ft_Esd_Theme_GetBackColor(theme);
	Ft_Gpu_CoCmd_BgColor(phost, c);
	ft_bool_t if_1 = Ft_Esd_TouchTag_Touching(&context->Touch_Tag);
	ft_uint32_t c_1;
	if (if_1)
	{
		Ft_Esd_Theme * theme_1 = context->Theme(parent);
		c_1 = Ft_Esd_Theme_GetPrimaryColor(theme_1);
	}
	else
	{
		Ft_Esd_Theme * theme_2 = context->Theme(parent);
		c_1 = Ft_Esd_Theme_GetTextColor(theme_2);
	}
	Ft_Esd_Dl_COLOR_RGB(c_1);
	ft_uint8_t s = Ft_Esd_TouchTag_Tag(&context->Touch_Tag);
	Ft_Esd_Dl_TAG(s);
	Ft_Gpu_Hal_Context_t * phost_1 = Ft_Esd_GetHost();
	ft_int16_t x = Ft_Esd_PosSizeToRadius_CenterX(&context->Ft_Esd_PosSizeToRadius);
	ft_int16_t y = Ft_Esd_PosSizeToRadius_CenterY(&context->Ft_Esd_PosSizeToRadius);
	ft_int16_t r = Ft_Esd_PosSizeToRadius_Radius(&context->Ft_Esd_PosSizeToRadius);
	ft_uint16_t options = 0;
	ft_uint16_t height = context->H(parent);
	ft_uint16_t m = context->M(parent);
	ft_uint16_t left = context->S(parent);
	ft_uint32_t left_1 = context->Ms(parent);
	ft_uint32_t right_1 = 1000UL;
	ft_uint32_t right = left_1 / right_1;
	ft_uint32_t s_1 = left + right;
	ft_uint32_t left_2 = context->Ms(parent);
	ft_uint32_t right_2 = 1000UL;
	ft_uint32_t ms = left_2 % right_2;
	Ft_Gpu_CoCmd_Clock(phost_1, x, y, r, options, height, m, s_1, ms);
	ft_uint8_t s_2 = 255;
	Ft_Esd_Dl_TAG(s_2);
}

ft_int16_t Ft_Esd_Clock_Ft_Esd_PosSizeToRadius_X__Property(void *c)
{
	Ft_Esd_Clock *context = (Ft_Esd_Clock *)c;
	void *parent = context->Parent;
	return context->X(parent);
}

ft_int16_t Ft_Esd_Clock_Ft_Esd_PosSizeToRadius_Y__Property(void *c)
{
	Ft_Esd_Clock *context = (Ft_Esd_Clock *)c;
	void *parent = context->Parent;
	return context->Y(parent);
}

ft_int16_t Ft_Esd_Clock_Ft_Esd_PosSizeToRadius_Width__Property(void *c)
{
	Ft_Esd_Clock *context = (Ft_Esd_Clock *)c;
	void *parent = context->Parent;
	return context->Width(parent);
}

ft_int16_t Ft_Esd_Clock_Ft_Esd_PosSizeToRadius_Height__Property(void *c)
{
	Ft_Esd_Clock *context = (Ft_Esd_Clock *)c;
	void *parent = context->Parent;
	return context->Height(parent);
}

void Ft_Esd_Clock_Start(Ft_Esd_Clock *context)
{
	void *parent = context->Parent;
	Ft_Esd_TouchTag_Start(&context->Touch_Tag);
}

void Ft_Esd_Clock_Update(Ft_Esd_Clock *context)
{
	void *parent = context->Parent;
	ft_bool_t if_2 = context->Interactive(parent);
	if (if_2)
	{
		Ft_Esd_TouchTag_Update(&context->Touch_Tag);
	}
	else
	{
	}
}

void Ft_Esd_Clock_End(Ft_Esd_Clock *context)
{
	void *parent = context->Parent;
	Ft_Esd_TouchTag_End(&context->Touch_Tag);
}

#ifdef ESD_SIMULATION
#include <stdlib.h>

typedef struct
{
	Ft_Esd_Clock Instance;
	Ft_Esd_Theme * Theme;
	ft_int16_t X;
	ft_int16_t Y;
	ft_int16_t Width;
	ft_int16_t Height;
	uint8_t Alpha;
	ft_uint16_t H;
	ft_uint16_t M;
	ft_uint16_t S;
	ft_uint32_t Ms;
	ft_bool_t Interactive;
} Ft_Esd_Clock__ESD;

Ft_Esd_Theme * Ft_Esd_Clock__Get_Theme__ESD(void *context) { return ((Ft_Esd_Clock__ESD *)context)->Theme; }
void Ft_Esd_Clock__Set_Theme__ESD(void *context, Ft_Esd_Theme * value) { ((Ft_Esd_Clock__ESD *)context)->Theme = value; }
ft_int16_t Ft_Esd_Clock__Get_X__ESD(void *context) { return ((Ft_Esd_Clock__ESD *)context)->X; }
void Ft_Esd_Clock__Set_X__ESD(void *context, ft_int16_t value) { ((Ft_Esd_Clock__ESD *)context)->X = value; }
ft_int16_t Ft_Esd_Clock__Get_Y__ESD(void *context) { return ((Ft_Esd_Clock__ESD *)context)->Y; }
void Ft_Esd_Clock__Set_Y__ESD(void *context, ft_int16_t value) { ((Ft_Esd_Clock__ESD *)context)->Y = value; }
ft_int16_t Ft_Esd_Clock__Get_Width__ESD(void *context) { return ((Ft_Esd_Clock__ESD *)context)->Width; }
void Ft_Esd_Clock__Set_Width__ESD(void *context, ft_int16_t value) { ((Ft_Esd_Clock__ESD *)context)->Width = value; }
ft_int16_t Ft_Esd_Clock__Get_Height__ESD(void *context) { return ((Ft_Esd_Clock__ESD *)context)->Height; }
void Ft_Esd_Clock__Set_Height__ESD(void *context, ft_int16_t value) { ((Ft_Esd_Clock__ESD *)context)->Height = value; }
uint8_t Ft_Esd_Clock__Get_Alpha__ESD(void *context) { return ((Ft_Esd_Clock__ESD *)context)->Alpha; }
void Ft_Esd_Clock__Set_Alpha__ESD(void *context, uint8_t value) { ((Ft_Esd_Clock__ESD *)context)->Alpha = value; }
ft_uint16_t Ft_Esd_Clock__Get_H__ESD(void *context) { return ((Ft_Esd_Clock__ESD *)context)->H; }
void Ft_Esd_Clock__Set_H__ESD(void *context, ft_uint16_t value) { ((Ft_Esd_Clock__ESD *)context)->H = value; }
ft_uint16_t Ft_Esd_Clock__Get_M__ESD(void *context) { return ((Ft_Esd_Clock__ESD *)context)->M; }
void Ft_Esd_Clock__Set_M__ESD(void *context, ft_uint16_t value) { ((Ft_Esd_Clock__ESD *)context)->M = value; }
ft_uint16_t Ft_Esd_Clock__Get_S__ESD(void *context) { return ((Ft_Esd_Clock__ESD *)context)->S; }
void Ft_Esd_Clock__Set_S__ESD(void *context, ft_uint16_t value) { ((Ft_Esd_Clock__ESD *)context)->S = value; }
ft_uint32_t Ft_Esd_Clock__Get_Ms__ESD(void *context) { return ((Ft_Esd_Clock__ESD *)context)->Ms; }
void Ft_Esd_Clock__Set_Ms__ESD(void *context, ft_uint32_t value) { ((Ft_Esd_Clock__ESD *)context)->Ms = value; }
ft_bool_t Ft_Esd_Clock__Get_Interactive__ESD(void *context) { return ((Ft_Esd_Clock__ESD *)context)->Interactive; }
void Ft_Esd_Clock__Set_Interactive__ESD(void *context, ft_bool_t value) { ((Ft_Esd_Clock__ESD *)context)->Interactive = value; }

void *Ft_Esd_Clock__Create__ESD()
{
	Ft_Esd_Clock__ESD *context = (Ft_Esd_Clock__ESD *)malloc(sizeof(Ft_Esd_Clock__ESD));
	Ft_Esd_Clock__Initializer(&context->Instance);
	context->Instance.Parent = context;
	context->Theme = Ft_Esd_Theme_GetCurrent();
	context->Instance.Theme = Ft_Esd_Clock__Get_Theme__ESD;
	context->X = 0;
	context->Instance.X = Ft_Esd_Clock__Get_X__ESD;
	context->Y = 0;
	context->Instance.Y = Ft_Esd_Clock__Get_Y__ESD;
	context->Width = 144;
	context->Instance.Width = Ft_Esd_Clock__Get_Width__ESD;
	context->Height = 144;
	context->Instance.Height = Ft_Esd_Clock__Get_Height__ESD;
	context->Alpha = 255;
	context->Instance.Alpha = Ft_Esd_Clock__Get_Alpha__ESD;
	context->H = 0U;
	context->Instance.H = Ft_Esd_Clock__Get_H__ESD;
	context->M = 0U;
	context->Instance.M = Ft_Esd_Clock__Get_M__ESD;
	context->S = 0U;
	context->Instance.S = Ft_Esd_Clock__Get_S__ESD;
	context->Ms = 0UL;
	context->Instance.Ms = Ft_Esd_Clock__Get_Ms__ESD;
	context->Interactive = 0;
	context->Instance.Interactive = Ft_Esd_Clock__Get_Interactive__ESD;
	return context;
}

void Ft_Esd_Clock__Destroy__ESD(void *context)
{
	free(context);
}


#endif /* ESD_SIMULATION */

/* end of file */
