/*
This file is automatically generated
Ft_Esd_DemoPage
Header
*/

#ifndef Ft_Esd_DemoPage__H
#define Ft_Esd_DemoPage__H

#include "Ft_Esd.h"
#include "Ft_Esd_Clock.h"
#include "Ft_Esd_Gauge.h"
#include "Ft_Esd_Label.h"
#include "Ft_Esd_LabelButton.h"
#include "Ft_Esd_NumericLabel.h"
#include "Ft_Esd_ProgressBar.h"
#include "Ft_Esd_PushButton.h"
#include "Ft_Esd_Rectangle.h"
#include "Ft_Esd_SpinBox.h"
#include "Ft_Esd_Theme.h"
#include "Ft_Esd_Toggle.h"
#include "Ft_Esd_TouchTag.h"
#include "SwitchBool.h"

#ifndef ESD_LOGIC
#define ESD_LOGIC(name, ...)
#define ESD_ACTOR(name, ...)
#define ESD_WIDGET(name, ...)
#define ESD_PAGE(name, ...)
#define ESD_APPLICATION(name, ...)
#define ESD_INPUT(name, ...)
#define ESD_OUTPUT(name, ...)
#define ESD_SLOT(name, ...)
#define ESD_SIGNAL(name, ...)
#define ESD_VARIABLE(name, ...)
#define ESD_WRITER(name, ...)
#endif

ESD_PAGE(Ft_Esd_DemoPage, Include = "Ft_Esd_DemoPage.h", Callback, DisplayName = "ESD Widget Demo Page", Category = EsdWidgets)
typedef struct
{
	void *Parent;
	SwitchBool SwitchBool;
	Ft_Esd_TouchTag Touch_Tag;
	Ft_Esd_ProgressBar ESD_ProgressBar;
	Ft_Esd_Gauge ESD_Gauge;
	Ft_Esd_Clock ESD_Clock;
	Ft_Esd_PushButton ESD_PushButton;
	Ft_Esd_Rectangle ESD_Rectangle;
	Ft_Esd_PushButton ESD_PushButton_1;
	Ft_Esd_Toggle ESD_Toggle;
	Ft_Esd_PushButton ESD_PushButton_2;
	Ft_Esd_Label ESD_Label;
	Ft_Esd_PushButton ESD_PushButton_3;
	Ft_Esd_Toggle ESD_Toggle_1;
	Ft_Esd_SpinBox ESD_SpinBox;
	Ft_Esd_NumericLabel ESD_NumericLabel;
	Ft_Esd_LabelButton ESD_Label_Button;
	Ft_Esd_NumericLabel ESD_NumericLabel_1;
	Ft_Esd_SpinBox ESD_SpinBox_1;
	Ft_Esd_NumericLabel ESD_NumericLabel_2;
	Ft_Esd_SpinBox ESD_SpinBox_2;
} Ft_Esd_DemoPage;

void Ft_Esd_DemoPage__Initializer(Ft_Esd_DemoPage *context);

ESD_SLOT(Update)
void Ft_Esd_DemoPage_Update(Ft_Esd_DemoPage *context);

ESD_SLOT(Render)
void Ft_Esd_DemoPage_Render(Ft_Esd_DemoPage *context);

ESD_SLOT(Idle)
void Ft_Esd_DemoPage_Idle(Ft_Esd_DemoPage *context);

ESD_SLOT(End)
void Ft_Esd_DemoPage_End(Ft_Esd_DemoPage *context);

ESD_SLOT(Start)
void Ft_Esd_DemoPage_Start(Ft_Esd_DemoPage *context);

#endif /* Ft_Esd_DemoPage__H */

/* end of file */
