/*
This file is automatically generated
Ft_Esd_ProgressBar
C Source
*/

#include "Ft_Esd_ProgressBar.h"

#include "FT_Esd_CoPro_Cmds.h"
#include "FT_Esd_Dl.h"
#include "FT_Gpu.h"

extern void Ft_Esd_Noop(void *context);
Ft_Esd_Theme * Ft_Esd_ProgressBar_Theme__Default(void *context) { return 0; }
ft_int16_t Ft_Esd_ProgressBar_X__Default(void *context) { return 50; }
ft_int16_t Ft_Esd_ProgressBar_Y__Default(void *context) { return 50; }
ft_int16_t Ft_Esd_ProgressBar_Width__Default(void *context) { return 180; }
ft_int16_t Ft_Esd_ProgressBar_Height__Default(void *context) { return 24; }
ft_uint16_t Ft_Esd_ProgressBar_Val__Default(void *context) { return 0U; }
ft_uint16_t Ft_Esd_ProgressBar_Range__Default(void *context) { return 65535U; }

Ft_Esd_Theme * Ft_Esd_Theme_GetCurrent();
Ft_Gpu_Hal_Context_t * Ft_Esd_GetHost();


void Ft_Esd_ProgressBar__Initializer(Ft_Esd_ProgressBar *context)
{
	context->Parent = 0;
	context->Theme = Ft_Esd_ProgressBar_Theme__Default;
	context->X = Ft_Esd_ProgressBar_X__Default;
	context->Y = Ft_Esd_ProgressBar_Y__Default;
	context->Width = Ft_Esd_ProgressBar_Width__Default;
	context->Height = Ft_Esd_ProgressBar_Height__Default;
	context->Val = Ft_Esd_ProgressBar_Val__Default;
	context->Range = Ft_Esd_ProgressBar_Range__Default;
}

ft_void_t Ft_Gpu_CoCmd_BgColor(Ft_Gpu_Hal_Context_t *, ft_rgb32_t);
ft_void_t Ft_Gpu_CoCmd_Progress(Ft_Gpu_Hal_Context_t *, ft_int16_t, ft_int16_t, ft_int16_t, ft_int16_t, ft_uint16_t, ft_uint16_t, ft_uint16_t);

void Ft_Esd_ProgressBar_Render(Ft_Esd_ProgressBar *context)
{
	void *parent = context->Parent;
	ft_uint8_t alpha = 255;
	Ft_Esd_Dl_COLOR_A(alpha);
	Ft_Gpu_Hal_Context_t * phost = Ft_Esd_GetHost();
	Ft_Esd_Theme * theme = context->Theme(parent);
	ft_rgb32_t c = Ft_Esd_Theme_GetBackColor(theme);
	Ft_Gpu_CoCmd_BgColor(phost, c);
	Ft_Esd_Theme * theme_1 = context->Theme(parent);
	ft_rgb32_t c_1 = Ft_Esd_Theme_GetPrimaryColor(theme_1);
	Ft_Esd_Dl_COLOR_RGB(c_1);
	Ft_Gpu_Hal_Context_t * phost_1 = Ft_Esd_GetHost();
	ft_int16_t left = context->X(parent);
	ft_int16_t left_1 = context->Height(parent);
	ft_int16_t right_1 = 2;
	ft_int16_t right = left_1 / right_1;
	ft_int16_t x = left + right;
	ft_int16_t y = context->Y(parent);
	ft_int16_t left_2 = context->Width(parent);
	ft_int16_t right_2 = context->Height(parent);
	ft_int16_t width = left_2 - right_2;
	ft_int16_t height = context->Height(parent);
	ft_uint16_t options = 0;
	ft_uint16_t val = context->Val(parent);
	ft_uint16_t range = context->Range(parent);
	Ft_Gpu_CoCmd_Progress(phost_1, x, y, width, height, options, val, range);
}

#ifdef ESD_SIMULATION
#include <stdlib.h>

typedef struct
{
	Ft_Esd_ProgressBar Instance;
	Ft_Esd_Theme * Theme;
	ft_int16_t X;
	ft_int16_t Y;
	ft_int16_t Width;
	ft_int16_t Height;
	ft_uint16_t Val;
	ft_uint16_t Range;
} Ft_Esd_ProgressBar__ESD;

Ft_Esd_Theme * Ft_Esd_ProgressBar__Get_Theme__ESD(void *context) { return ((Ft_Esd_ProgressBar__ESD *)context)->Theme; }
void Ft_Esd_ProgressBar__Set_Theme__ESD(void *context, Ft_Esd_Theme * value) { ((Ft_Esd_ProgressBar__ESD *)context)->Theme = value; }
ft_int16_t Ft_Esd_ProgressBar__Get_X__ESD(void *context) { return ((Ft_Esd_ProgressBar__ESD *)context)->X; }
void Ft_Esd_ProgressBar__Set_X__ESD(void *context, ft_int16_t value) { ((Ft_Esd_ProgressBar__ESD *)context)->X = value; }
ft_int16_t Ft_Esd_ProgressBar__Get_Y__ESD(void *context) { return ((Ft_Esd_ProgressBar__ESD *)context)->Y; }
void Ft_Esd_ProgressBar__Set_Y__ESD(void *context, ft_int16_t value) { ((Ft_Esd_ProgressBar__ESD *)context)->Y = value; }
ft_int16_t Ft_Esd_ProgressBar__Get_Width__ESD(void *context) { return ((Ft_Esd_ProgressBar__ESD *)context)->Width; }
void Ft_Esd_ProgressBar__Set_Width__ESD(void *context, ft_int16_t value) { ((Ft_Esd_ProgressBar__ESD *)context)->Width = value; }
ft_int16_t Ft_Esd_ProgressBar__Get_Height__ESD(void *context) { return ((Ft_Esd_ProgressBar__ESD *)context)->Height; }
void Ft_Esd_ProgressBar__Set_Height__ESD(void *context, ft_int16_t value) { ((Ft_Esd_ProgressBar__ESD *)context)->Height = value; }
ft_uint16_t Ft_Esd_ProgressBar__Get_Val__ESD(void *context) { return ((Ft_Esd_ProgressBar__ESD *)context)->Val; }
void Ft_Esd_ProgressBar__Set_Val__ESD(void *context, ft_uint16_t value) { ((Ft_Esd_ProgressBar__ESD *)context)->Val = value; }
ft_uint16_t Ft_Esd_ProgressBar__Get_Range__ESD(void *context) { return ((Ft_Esd_ProgressBar__ESD *)context)->Range; }
void Ft_Esd_ProgressBar__Set_Range__ESD(void *context, ft_uint16_t value) { ((Ft_Esd_ProgressBar__ESD *)context)->Range = value; }

void *Ft_Esd_ProgressBar__Create__ESD()
{
	Ft_Esd_ProgressBar__ESD *context = (Ft_Esd_ProgressBar__ESD *)malloc(sizeof(Ft_Esd_ProgressBar__ESD));
	Ft_Esd_ProgressBar__Initializer(&context->Instance);
	context->Instance.Parent = context;
	context->Theme = 0;
	context->Instance.Theme = Ft_Esd_ProgressBar__Get_Theme__ESD;
	context->X = 50;
	context->Instance.X = Ft_Esd_ProgressBar__Get_X__ESD;
	context->Y = 50;
	context->Instance.Y = Ft_Esd_ProgressBar__Get_Y__ESD;
	context->Width = 180;
	context->Instance.Width = Ft_Esd_ProgressBar__Get_Width__ESD;
	context->Height = 24;
	context->Instance.Height = Ft_Esd_ProgressBar__Get_Height__ESD;
	context->Val = 0U;
	context->Instance.Val = Ft_Esd_ProgressBar__Get_Val__ESD;
	context->Range = 65535U;
	context->Instance.Range = Ft_Esd_ProgressBar__Get_Range__ESD;
	return context;
}

void Ft_Esd_ProgressBar__Destroy__ESD(void *context)
{
	free(context);
}


#endif /* ESD_SIMULATION */

/* end of file */
