/*
This file is automatically generated
LayoutSplit
Header
*/

#ifndef LayoutSplit__H
#define LayoutSplit__H

#include "Ft_Esd.h"

#ifndef ESD_LOGIC
#define ESD_LOGIC(name, ...)
#define ESD_ACTOR(name, ...)
#define ESD_WIDGET(name, ...)
#define ESD_PAGE(name, ...)
#define ESD_APPLICATION(name, ...)
#define ESD_INPUT(name, ...)
#define ESD_OUTPUT(name, ...)
#define ESD_SLOT(name, ...)
#define ESD_SIGNAL(name, ...)
#define ESD_VARIABLE(name, ...)
#define ESD_WRITER(name, ...)
#endif

ESD_LOGIC(LayoutSplit, Include = "LayoutSplit.h", Callback, Category = _GroupHidden)
typedef struct
{
	void *Parent;
	ESD_INPUT(Pos, Type = int)
	int(* Pos)(void *context);
	ESD_INPUT(Length, Type = int)
	int(* Length)(void *context);
	ESD_INPUT(Numerator, Type = int, Default = 50)
	int(* Numerator)(void *context);
	ESD_INPUT(Denominator, Type = int)
	int(* Denominator)(void *context);
	ESD_INPUT(Margin, Type = int, Default = 4)
	int(* Margin)(void *context);
} LayoutSplit;

void LayoutSplit__Initializer(LayoutSplit *context);

ESD_OUTPUT(FirstPos, Type = int)
int LayoutSplit_FirstPos(LayoutSplit *context);

ESD_OUTPUT(SecondPos, Type = int)
int LayoutSplit_SecondPos(LayoutSplit *context);

ESD_OUTPUT(FirstLength, Type = int)
int LayoutSplit_FirstLength(LayoutSplit *context);

ESD_OUTPUT(SecondLength, Type = int)
int LayoutSplit_SecondLength(LayoutSplit *context);

#endif /* LayoutSplit__H */

/* end of file */
