/*
This file is automatically generated
SwitchBool
Header
*/

#ifndef SwitchBool__H
#define SwitchBool__H

#include "FT_DataTypes.h"
#include "Ft_Esd.h"

#ifndef ESD_LOGIC
#define ESD_LOGIC(name, ...)
#define ESD_ACTOR(name, ...)
#define ESD_WIDGET(name, ...)
#define ESD_PAGE(name, ...)
#define ESD_APPLICATION(name, ...)
#define ESD_INPUT(name, ...)
#define ESD_OUTPUT(name, ...)
#define ESD_SLOT(name, ...)
#define ESD_SIGNAL(name, ...)
#define ESD_VARIABLE(name, ...)
#define ESD_WRITER(name, ...)
#endif

ESD_LOGIC(SwitchBool, Include = "SwitchBool.h", Callback, Category = _GroupHidden)
typedef struct
{
	void *Parent;
	ESD_VARIABLE(Boolean, Type = ft_bool_t, Private)
	ft_bool_t Boolean;
} SwitchBool;

void SwitchBool__Initializer(SwitchBool *context);

ESD_SLOT(SetTrue)
void SwitchBool_SetTrue(SwitchBool *context);

ESD_OUTPUT(Value, Type = ft_bool_t)
ft_bool_t SwitchBool_Value(SwitchBool *context);

ESD_SLOT(SetFalse)
void SwitchBool_SetFalse(SwitchBool *context);

ESD_SLOT(Switch)
void SwitchBool_Switch(SwitchBool *context);

#endif /* SwitchBool__H */

/* end of file */
