/*
This file is automatically generated
App
Header
*/

#ifndef App__H
#define App__H

#include "Confirmation.h"
#include "Ft_Esd.h"
#include "MainPage.h"
#include "YesPage.h"

#ifndef ESD_LOGIC
#define ESD_LOGIC(name, ...)
#define ESD_ACTOR(name, ...)
#define ESD_WIDGET(name, ...)
#define ESD_PAGE(name, ...)
#define ESD_APPLICATION(name, ...)
#define ESD_INPUT(name, ...)
#define ESD_OUTPUT(name, ...)
#define ESD_SLOT(name, ...)
#define ESD_SIGNAL(name, ...)
#define ESD_VARIABLE(name, ...)
#define ESD_WRITER(name, ...)
#endif

ESD_APPLICATION(App, Include = "App.h", Callback)
typedef struct
{
	void *Parent;
	int _ActivePage;
	MainPage *MainPage;
	int MainPage__Active;
	YesPage *YesPage;
	int YesPage__Active;
	Confirmation *Confirmation;
	int Confirmation__Active;
} App;

void App__Initializer(App *context);

ESD_SLOT(Update)
void App_Update(App *context);

ESD_SLOT(Render)
void App_Render(App *context);

ESD_SLOT(Idle)
void App_Idle(App *context);

ESD_SLOT(End)
void App_End(App *context);

ESD_SLOT(Start)
void App_Start(App *context);

#endif /* App__H */

/* end of file */
