/*
This file is automatically generated
Confirmation
C Source
*/

#include "Confirmation.h"


extern void Ft_Esd_Noop(void *context);

Ft_Esd_Theme * Ft_Esd_Theme_GetCurrent();
static ft_int16_t Confirmation_ParkingSpotFound_Font__Property(void *context) { return 30; }
static const char * Confirmation_ParkingSpotFound_Text__Property(void *context) { return "Thank you, the nearest spot is no."; }
static ft_int16_t Confirmation_ParkingSpotFound_X__Property(void *context) { return 100; }
static ft_int16_t Confirmation_ParkingSpotFound_Y__Property(void *context) { return 150; }
static ft_int16_t Confirmation_ParkingSpotFound_Width__Property(void *context) { return 400; }
static ft_int16_t Confirmation_ParkingSpotFound_Height__Property(void *context) { return 40; }
static ft_uint16_t Confirmation_ParkingSpotFound_AlignX__Property(void *context) { return OPT_ALIGN_CENTER; }
static ft_uint16_t Confirmation_ParkingSpotFound_AlignY__Property(void *context) { return OPT_ALIGN_CENTER; }
static ft_int16_t Confirmation_ESD_Numeric_Label_X__Property(void *context) { return 609; }
static ft_int16_t Confirmation_ESD_Numeric_Label_Y__Property(void *context) { return 150; }
static ft_int16_t Confirmation_ESD_Numeric_Label_Height__Property(void *context) { return 40; }
static ft_int16_t Confirmation_ESD_Numeric_Label_Font__Property(void *context) { return 31; }
static ft_int32_t Confirmation_ESD_Numeric_Label_Value__Property(void *context);
static ft_int16_t Confirmation_ESD_Label_Font__Property(void *context) { return 30; }
static const char * Confirmation_ESD_Label_Text__Property(void *context) { return "There are no available spots"; }
static ft_int16_t Confirmation_ESD_Label_X__Property(void *context) { return 181; }
static ft_int16_t Confirmation_ESD_Label_Y__Property(void *context) { return 225; }
static ft_int16_t Confirmation_ESD_Label_Width__Property(void *context) { return 400; }
static ft_int16_t Confirmation_ESD_Label_Height__Property(void *context) { return 40; }
static ft_uint16_t Confirmation_ESD_Label_AlignX__Property(void *context) { return OPT_ALIGN_CENTER; }
static ft_uint16_t Confirmation_ESD_Label_AlignY__Property(void *context) { return OPT_ALIGN_CENTER; }


void Confirmation__Initializer(Confirmation *context)
{
	context->Parent = 0;
	context->SpotAvailability = 0;
	context->ParkingSpotNumber = 0L;
	Ft_Esd_Label__Initializer(&context->ParkingSpotFound);
	context->ParkingSpotFound.Parent = context;
	context->ParkingSpotFound.Font = Confirmation_ParkingSpotFound_Font__Property;
	context->ParkingSpotFound.Text = Confirmation_ParkingSpotFound_Text__Property;
	context->ParkingSpotFound.X = Confirmation_ParkingSpotFound_X__Property;
	context->ParkingSpotFound.Y = Confirmation_ParkingSpotFound_Y__Property;
	context->ParkingSpotFound.Width = Confirmation_ParkingSpotFound_Width__Property;
	context->ParkingSpotFound.Height = Confirmation_ParkingSpotFound_Height__Property;
	context->ParkingSpotFound.AlignX = Confirmation_ParkingSpotFound_AlignX__Property;
	context->ParkingSpotFound.AlignY = Confirmation_ParkingSpotFound_AlignY__Property;
	Ft_Esd_NumericLabel__Initializer(&context->ESD_Numeric_Label);
	context->ESD_Numeric_Label.Parent = context;
	context->ESD_Numeric_Label.X = Confirmation_ESD_Numeric_Label_X__Property;
	context->ESD_Numeric_Label.Y = Confirmation_ESD_Numeric_Label_Y__Property;
	context->ESD_Numeric_Label.Height = Confirmation_ESD_Numeric_Label_Height__Property;
	context->ESD_Numeric_Label.Font = Confirmation_ESD_Numeric_Label_Font__Property;
	context->ESD_Numeric_Label.Value = Confirmation_ESD_Numeric_Label_Value__Property;
	Ft_Esd_Label__Initializer(&context->ESD_Label);
	context->ESD_Label.Parent = context;
	context->ESD_Label.Font = Confirmation_ESD_Label_Font__Property;
	context->ESD_Label.Text = Confirmation_ESD_Label_Text__Property;
	context->ESD_Label.X = Confirmation_ESD_Label_X__Property;
	context->ESD_Label.Y = Confirmation_ESD_Label_Y__Property;
	context->ESD_Label.Width = Confirmation_ESD_Label_Width__Property;
	context->ESD_Label.Height = Confirmation_ESD_Label_Height__Property;
	context->ESD_Label.AlignX = Confirmation_ESD_Label_AlignX__Property;
	context->ESD_Label.AlignY = Confirmation_ESD_Label_AlignY__Property;
}

static int Confirmation_ParkingSpotFound__active(Confirmation *context);
static int Confirmation_ESD_Numeric_Label__active(Confirmation *context);
static int Confirmation_ESD_Label__active(Confirmation *context);

void Confirmation_getParkingSpotID_Signal(Confirmation *context);

void Confirmation_Start(Confirmation *context)
{
	void *parent = context->Parent;
}

void Confirmation_Update(Confirmation *context)
{
	void *parent = context->Parent;
}

void Confirmation_Render(Confirmation *context)
{
	void *parent = context->Parent;
	if (Confirmation_ParkingSpotFound__active(context))
		Ft_Esd_Label_Render(&context->ParkingSpotFound);
	if (Confirmation_ESD_Numeric_Label__active(context))
		Ft_Esd_NumericLabel_Render(&context->ESD_Numeric_Label);
	if (Confirmation_ESD_Label__active(context))
		Ft_Esd_Label_Render(&context->ESD_Label);
}

void Confirmation_Idle(Confirmation *context)
{
	void *parent = context->Parent;
}

void Confirmation_End(Confirmation *context)
{
	void *parent = context->Parent;
}

void Confirmation_getParkingSpotID(Confirmation *context)
{
	void *parent = context->Parent;
	ft_bool_t set_variable_2 = 1;
	context->SpotAvailability = set_variable_2;
	Confirmation_getParkingSpotID_Signal(context);
}

int Confirmation_ParkingSpotFound__active(Confirmation *context)
{
	void *parent = context->Parent;
	return context->SpotAvailability;
}

ft_int32_t Confirmation_ESD_Numeric_Label_Value__Property(void *c)
{
	Confirmation *context = (Confirmation *)c;
	void *parent = context->Parent;
	return context->ParkingSpotNumber;
}

int Confirmation_ESD_Numeric_Label__active(Confirmation *context)
{
	void *parent = context->Parent;
	return context->SpotAvailability;
}

int Confirmation_ESD_Label__active(Confirmation *context)
{
	void *parent = context->Parent;
	ft_bool_t value = context->SpotAvailability;
	return !value;
}

#ifdef ESD_SIMULATION
#include <stdlib.h>

typedef struct
{
	Confirmation Instance;
} Confirmation__ESD;


void *Confirmation__Create__ESD()
{
	Confirmation__ESD *context = (Confirmation__ESD *)malloc(sizeof(Confirmation__ESD));
	Confirmation__Initializer(&context->Instance);
	context->Instance.Parent = context;
	return context;
}

void Confirmation__Destroy__ESD(void *context)
{
	free(context);
}

void Confirmation__Set_SpotAvailability__ESD(void *context, ft_bool_t value) { ((Confirmation__ESD *)context)->Instance.SpotAvailability = value; }
void Confirmation__Set_ParkingSpotNumber__ESD(void *context, int value) { ((Confirmation__ESD *)context)->Instance.ParkingSpotNumber = value; }

#endif /* ESD_SIMULATION */

/* end of file */
