/*
This file is automatically generated
Confirmation
Header
*/

#ifndef Confirmation__H
#define Confirmation__H

#include "Ft_Esd.h"
#include "Ft_Esd_Label.h"
#include "Ft_Esd_NumericLabel.h"
#include "Ft_Esd_Theme.h"

#ifndef ESD_LOGIC
#define ESD_LOGIC(name, ...)
#define ESD_ACTOR(name, ...)
#define ESD_WIDGET(name, ...)
#define ESD_PAGE(name, ...)
#define ESD_APPLICATION(name, ...)
#define ESD_INPUT(name, ...)
#define ESD_OUTPUT(name, ...)
#define ESD_SLOT(name, ...)
#define ESD_SIGNAL(name, ...)
#define ESD_VARIABLE(name, ...)
#define ESD_WRITER(name, ...)
#endif

ESD_PAGE(Confirmation, Include = "Confirmation.h", Callback)
typedef struct
{
	void *Parent;
	ESD_VARIABLE(SpotAvailability, Type = ft_bool_t, Private)
	ft_bool_t SpotAvailability;
	ESD_VARIABLE(ParkingSpotNumber, Type = int, Private)
	int ParkingSpotNumber;
	Ft_Esd_Label ParkingSpotFound;
	Ft_Esd_NumericLabel ESD_Numeric_Label;
	Ft_Esd_Label ESD_Label;
} Confirmation;

void Confirmation__Initializer(Confirmation *context);

ESD_SLOT(Start)
void Confirmation_Start(Confirmation *context);

ESD_SLOT(Update)
void Confirmation_Update(Confirmation *context);

ESD_SLOT(Render)
void Confirmation_Render(Confirmation *context);

ESD_SLOT(Idle)
void Confirmation_Idle(Confirmation *context);

ESD_SLOT(End)
void Confirmation_End(Confirmation *context);

ESD_SLOT(getParkingSpotID)
void Confirmation_getParkingSpotID(Confirmation *context);

#endif /* Confirmation__H */

/* end of file */
