/*
This file is automatically generated
MainPage
C Source
*/

#include "MainPage.h"

extern void Ft_Esd_Noop(void *context);

Ft_Esd_Theme * Ft_Esd_Theme_GetCurrent();
static ft_int16_t MainPage_Parking_Spot_Finder_Font__Property(void *context) { return 31; }
static const char * MainPage_Parking_Spot_Finder_Text__Property(void *context) { return "Parking Spot Finder"; }
static ft_int16_t MainPage_Parking_Spot_Finder_X__Property(void *context) { return 6; }
static ft_int16_t MainPage_Parking_Spot_Finder_Width__Property(void *context) { return 297; }
static ft_int16_t MainPage_No_Push_Button_X__Property(void *context) { return 468; }
static ft_int16_t MainPage_No_Push_Button_Y__Property(void *context) { return 269; }
static ft_int16_t MainPage_No_Push_Button_Width__Property(void *context) { return 193; }
static ft_int16_t MainPage_No_Push_Button_Height__Property(void *context) { return 31; }
static const char * MainPage_No_Push_Button_Text__Property(void *context) { return "No"; }
static const char * MainPage_ESD_Label_Text__Property(void *context) { return "Parking ID :"; }
static ft_int16_t MainPage_ESD_Label_X__Property(void *context) { return 236; }
static ft_int16_t MainPage_ESD_Label_Y__Property(void *context) { return 201; }
static ft_int16_t MainPage_ESD_Numeric_Label_X__Property(void *context) { return 479; }
static ft_int16_t MainPage_ESD_Numeric_Label_Y__Property(void *context) { return 203; }
static ft_int16_t MainPage_Yes_Push_Button__X__Property(void *context) { return 191; }
static ft_int16_t MainPage_Yes_Push_Button__Y__Property(void *context) { return 269; }
static ft_int16_t MainPage_Yes_Push_Button__Width__Property(void *context) { return 193; }
static ft_int16_t MainPage_Yes_Push_Button__Height__Property(void *context) { return 31; }
static const char * MainPage_Yes_Push_Button__Text__Property(void *context) { return "Yes"; }
static ft_int16_t MainPage_ESD_Label_2_Font__Property(void *context) { return 29; }
static const char * MainPage_ESD_Label_2_Text__Property(void *context) { return "Have you reserved a spot at ParkMe.com?"; }
static ft_int16_t MainPage_ESD_Label_2_X__Property(void *context) { return 178; }
static ft_int16_t MainPage_ESD_Label_2_Y__Property(void *context) { return 129; }
static ft_int16_t MainPage_ESD_Label_2_Width__Property(void *context) { return 456; }
static ft_int16_t MainPage_ESD_Label_2_Height__Property(void *context) { return 45; }

static void MainPage_No_Push_Button_Pushed__Signal(void *context);

void MainPage__Initializer(MainPage *context)
{
	context->Parent = 0;
	context->ShowParkingID_b = 0L;
	Ft_Esd_Label__Initializer(&context->Parking_Spot_Finder);
	context->Parking_Spot_Finder.Parent = context;
	context->Parking_Spot_Finder.Font = MainPage_Parking_Spot_Finder_Font__Property;
	context->Parking_Spot_Finder.Text = MainPage_Parking_Spot_Finder_Text__Property;
	context->Parking_Spot_Finder.X = MainPage_Parking_Spot_Finder_X__Property;
	context->Parking_Spot_Finder.Width = MainPage_Parking_Spot_Finder_Width__Property;
	Ft_Esd_PushButton__Initializer(&context->No_Push_Button);
	context->No_Push_Button.Parent = context;
	context->No_Push_Button.X = MainPage_No_Push_Button_X__Property;
	context->No_Push_Button.Y = MainPage_No_Push_Button_Y__Property;
	context->No_Push_Button.Width = MainPage_No_Push_Button_Width__Property;
	context->No_Push_Button.Height = MainPage_No_Push_Button_Height__Property;
	context->No_Push_Button.Text = MainPage_No_Push_Button_Text__Property;
	context->No_Push_Button.Pushed = MainPage_No_Push_Button_Pushed__Signal;
	Ft_Esd_Label__Initializer(&context->ESD_Label);
	context->ESD_Label.Parent = context;
	context->ESD_Label.Text = MainPage_ESD_Label_Text__Property;
	context->ESD_Label.X = MainPage_ESD_Label_X__Property;
	context->ESD_Label.Y = MainPage_ESD_Label_Y__Property;
	Ft_Esd_NumericLabel__Initializer(&context->ESD_Numeric_Label);
	context->ESD_Numeric_Label.Parent = context;
	context->ESD_Numeric_Label.X = MainPage_ESD_Numeric_Label_X__Property;
	context->ESD_Numeric_Label.Y = MainPage_ESD_Numeric_Label_Y__Property;
	Ft_Esd_PushButton__Initializer(&context->Yes_Push_Button_);
	context->Yes_Push_Button_.Parent = context;
	context->Yes_Push_Button_.X = MainPage_Yes_Push_Button__X__Property;
	context->Yes_Push_Button_.Y = MainPage_Yes_Push_Button__Y__Property;
	context->Yes_Push_Button_.Width = MainPage_Yes_Push_Button__Width__Property;
	context->Yes_Push_Button_.Height = MainPage_Yes_Push_Button__Height__Property;
	context->Yes_Push_Button_.Text = MainPage_Yes_Push_Button__Text__Property;
	Ft_Esd_Label__Initializer(&context->ESD_Label_2);
	context->ESD_Label_2.Parent = context;
	context->ESD_Label_2.Font = MainPage_ESD_Label_2_Font__Property;
	context->ESD_Label_2.Text = MainPage_ESD_Label_2_Text__Property;
	context->ESD_Label_2.X = MainPage_ESD_Label_2_X__Property;
	context->ESD_Label_2.Y = MainPage_ESD_Label_2_Y__Property;
	context->ESD_Label_2.Width = MainPage_ESD_Label_2_Width__Property;
	context->ESD_Label_2.Height = MainPage_ESD_Label_2_Height__Property;
}

static int MainPage_ESD_Numeric_Label__active(MainPage *context);

void MainPage_Start(MainPage *context)
{
	void *parent = context->Parent;
	Ft_Esd_PushButton_Start(&context->No_Push_Button);
	Ft_Esd_PushButton_Start(&context->Yes_Push_Button_);
}

void MainPage_Update(MainPage *context)
{
	void *parent = context->Parent;
	Ft_Esd_PushButton_Update(&context->No_Push_Button);
	Ft_Esd_PushButton_Update(&context->Yes_Push_Button_);
}

void MainPage_Render(MainPage *context)
{
	void *parent = context->Parent;
	Ft_Esd_Label_Render(&context->Parking_Spot_Finder);
	Ft_Esd_PushButton_Render(&context->No_Push_Button);
	if (MainPage_ESD_Numeric_Label__active(context))
		Ft_Esd_NumericLabel_Render(&context->ESD_Numeric_Label);
	Ft_Esd_PushButton_Render(&context->Yes_Push_Button_);
	Ft_Esd_Label_Render(&context->ESD_Label_2);
}

void MainPage_Idle(MainPage *context)
{
	void *parent = context->Parent;
}

void MainPage_End(MainPage *context)
{
	void *parent = context->Parent;
	Ft_Esd_PushButton_End(&context->No_Push_Button);
	Ft_Esd_PushButton_End(&context->Yes_Push_Button_);
}

void MainPage_No_Push_Button_Pushed__Signal(void *c)
{
	MainPage *context = (MainPage *)c;
	void *parent = context->Parent;
	ft_bool_t set_variable = 1;
	context->ShowParkingID_b = (ft_bool_t)set_variable;
}

int MainPage_ESD_Numeric_Label__active(MainPage *context)
{
	void *parent = context->Parent;
	return context->ShowParkingID_b;
}

#ifdef ESD_SIMULATION
#include <stdlib.h>

typedef struct
{
	MainPage Instance;
} MainPage__ESD;


void *MainPage__Create__ESD()
{
	MainPage__ESD *context = (MainPage__ESD *)malloc(sizeof(MainPage__ESD));
	MainPage__Initializer(&context->Instance);
	context->Instance.Parent = context;
	return context;
}

void MainPage__Destroy__ESD(void *context)
{
	free(context);
}

void MainPage__Set_ShowParkingID_b__ESD(void *context, int value) { ((MainPage__ESD *)context)->Instance.ShowParkingID_b = value; }

#endif /* ESD_SIMULATION */

/* end of file */
