/*
This file is automatically generated
MainPage
C Source
*/

#include "MainPage.h"

extern void Ft_Esd_Noop(void *context);

Ft_Esd_Theme * Ft_Esd_Theme_GetCurrent();
static ft_int16_t MainPage_ESD3_Label_Font__Property(void *context) { return 31; }
static const char * MainPage_ESD3_Label_Text__Property(void *context) { return "Parking Spot Finder"; }
static ft_int16_t MainPage_ESD3_Label_X__Property(void *context) { return 6; }
static ft_int16_t MainPage_ESD_Label_Font__Property(void *context) { return 29; }
static const char * MainPage_ESD_Label_Text__Property(void *context) { return "Have you booked a spot at ParkMe.com ?"; }
static ft_int16_t MainPage_ESD_Label_X__Property(void *context) { return 139; }
static ft_int16_t MainPage_ESD_Label_Y__Property(void *context) { return 141; }
static ft_int16_t MainPage_ESD_Push_Button_X__Property(void *context) { return 150; }
static ft_int16_t MainPage_ESD_Push_Button_Y__Property(void *context) { return 264; }
static const char * MainPage_ESD_Push_Button_Text__Property(void *context) { return "Yes"; }
static ft_int16_t MainPage_ESD_Push_Button_2_X__Property(void *context) { return 475; }
static ft_int16_t MainPage_ESD_Push_Button_2_Y__Property(void *context) { return 265; }
static const char * MainPage_ESD_Push_Button_2_Text__Property(void *context) { return "No"; }


void MainPage__Initializer(MainPage *context)
{
	context->Parent = 0;
	Ft_Esd_Label__Initializer(&context->ESD3_Label);
	context->ESD3_Label.Parent = context;
	context->ESD3_Label.Font = MainPage_ESD3_Label_Font__Property;
	context->ESD3_Label.Text = MainPage_ESD3_Label_Text__Property;
	context->ESD3_Label.X = MainPage_ESD3_Label_X__Property;
	Ft_Esd_Label__Initializer(&context->ESD_Label);
	context->ESD_Label.Parent = context;
	context->ESD_Label.Font = MainPage_ESD_Label_Font__Property;
	context->ESD_Label.Text = MainPage_ESD_Label_Text__Property;
	context->ESD_Label.X = MainPage_ESD_Label_X__Property;
	context->ESD_Label.Y = MainPage_ESD_Label_Y__Property;
	Ft_Esd_PushButton__Initializer(&context->ESD_Push_Button);
	context->ESD_Push_Button.Parent = context;
	context->ESD_Push_Button.X = MainPage_ESD_Push_Button_X__Property;
	context->ESD_Push_Button.Y = MainPage_ESD_Push_Button_Y__Property;
	context->ESD_Push_Button.Text = MainPage_ESD_Push_Button_Text__Property;
	Ft_Esd_PushButton__Initializer(&context->ESD_Push_Button_2);
	context->ESD_Push_Button_2.Parent = context;
	context->ESD_Push_Button_2.X = MainPage_ESD_Push_Button_2_X__Property;
	context->ESD_Push_Button_2.Y = MainPage_ESD_Push_Button_2_Y__Property;
	context->ESD_Push_Button_2.Text = MainPage_ESD_Push_Button_2_Text__Property;
}

void MainPage_Start(MainPage *context)
{
	void *parent = context->Parent;
	Ft_Esd_PushButton_Start(&context->ESD_Push_Button);
	Ft_Esd_PushButton_Start(&context->ESD_Push_Button_2);
}

void MainPage_Update(MainPage *context)
{
	void *parent = context->Parent;
	Ft_Esd_PushButton_Update(&context->ESD_Push_Button);
	Ft_Esd_PushButton_Update(&context->ESD_Push_Button_2);
}

void MainPage_Render(MainPage *context)
{
	void *parent = context->Parent;
	Ft_Esd_Label_Render(&context->ESD3_Label);
	Ft_Esd_Label_Render(&context->ESD_Label);
	Ft_Esd_PushButton_Render(&context->ESD_Push_Button);
	Ft_Esd_PushButton_Render(&context->ESD_Push_Button_2);
}

void MainPage_Idle(MainPage *context)
{
	void *parent = context->Parent;
}

void MainPage_End(MainPage *context)
{
	void *parent = context->Parent;
	Ft_Esd_PushButton_End(&context->ESD_Push_Button);
	Ft_Esd_PushButton_End(&context->ESD_Push_Button_2);
}

#ifdef ESD_SIMULATION
#include <stdlib.h>

typedef struct
{
	MainPage Instance;
} MainPage__ESD;


void *MainPage__Create__ESD()
{
	MainPage__ESD *context = (MainPage__ESD *)malloc(sizeof(MainPage__ESD));
	MainPage__Initializer(&context->Instance);
	context->Instance.Parent = context;
	return context;
}

void MainPage__Destroy__ESD(void *context)
{
	free(context);
}


#endif /* ESD_SIMULATION */

/* end of file */
