/*
This file is automatically generated
YesPage
C Source
*/

#include "YesPage.h"

#include "FT_Esd_Primitives.h"

extern void Ft_Esd_Noop(void *context);

Ft_Esd_Theme * purdue();
Ft_Esd_Theme * Ft_Esd_Theme_GetCurrent();
static ft_int16_t YesPage_Num2_X__Property(void *context) { return 130; }
static ft_int16_t YesPage_Num2_Y__Property(void *context) { return 120; }
static ft_int16_t YesPage_Num2_Width__Property(void *context) { return 60; }
static ft_int16_t YesPage_Num2_Height__Property(void *context) { return 60; }
static ft_int16_t YesPage_Num2_Font__Property(void *context) { return 31; }
static const char * YesPage_Num2_Text__Property(void *context) { return "2"; }
static ft_int16_t YesPage_Num1_X__Property(void *context) { return 50; }
static ft_int16_t YesPage_Num1_Y__Property(void *context) { return 120; }
static ft_int16_t YesPage_Num1_Width__Property(void *context) { return 60; }
static ft_int16_t YesPage_Num1_Height__Property(void *context) { return 60; }
static ft_int16_t YesPage_Num1_Font__Property(void *context) { return 31; }
static const char * YesPage_Num1_Text__Property(void *context) { return "1"; }
static ft_int16_t YesPage_Num4_X__Property(void *context) { return 50; }
static ft_int16_t YesPage_Num4_Y__Property(void *context) { return 200; }
static ft_int16_t YesPage_Num4_Width__Property(void *context) { return 60; }
static ft_int16_t YesPage_Num4_Height__Property(void *context) { return 60; }
static ft_int16_t YesPage_Num4_Font__Property(void *context) { return 31; }
static const char * YesPage_Num4_Text__Property(void *context) { return "4"; }
static ft_int16_t YesPage_Num5_X__Property(void *context) { return 130; }
static ft_int16_t YesPage_Num5_Y__Property(void *context) { return 200; }
static ft_int16_t YesPage_Num5_Width__Property(void *context) { return 60; }
static ft_int16_t YesPage_Num5_Height__Property(void *context) { return 60; }
static ft_int16_t YesPage_Num5_Font__Property(void *context) { return 31; }
static const char * YesPage_Num5_Text__Property(void *context) { return "5"; }
static ft_int16_t YesPage_Num6_X__Property(void *context) { return 210; }
static ft_int16_t YesPage_Num6_Y__Property(void *context) { return 200; }
static ft_int16_t YesPage_Num6_Width__Property(void *context) { return 60; }
static ft_int16_t YesPage_Num6_Height__Property(void *context) { return 60; }
static ft_int16_t YesPage_Num6_Font__Property(void *context) { return 31; }
static const char * YesPage_Num6_Text__Property(void *context) { return "6"; }
static ft_int16_t YesPage_Num7_X__Property(void *context) { return 50; }
static ft_int16_t YesPage_Num7_Y__Property(void *context) { return 280; }
static ft_int16_t YesPage_Num7_Width__Property(void *context) { return 60; }
static ft_int16_t YesPage_Num7_Height__Property(void *context) { return 60; }
static ft_int16_t YesPage_Num7_Font__Property(void *context) { return 31; }
static const char * YesPage_Num7_Text__Property(void *context) { return "7"; }
static ft_int16_t YesPage_Num9_X__Property(void *context) { return 210; }
static ft_int16_t YesPage_Num9_Y__Property(void *context) { return 280; }
static ft_int16_t YesPage_Num9_Width__Property(void *context) { return 60; }
static ft_int16_t YesPage_Num9_Height__Property(void *context) { return 60; }
static ft_int16_t YesPage_Num9_Font__Property(void *context) { return 31; }
static const char * YesPage_Num9_Text__Property(void *context) { return "9"; }
static ft_int16_t YesPage_Num8_X__Property(void *context) { return 130; }
static ft_int16_t YesPage_Num8_Y__Property(void *context) { return 280; }
static ft_int16_t YesPage_Num8_Width__Property(void *context) { return 60; }
static ft_int16_t YesPage_Num8_Height__Property(void *context) { return 60; }
static ft_int16_t YesPage_Num8_Font__Property(void *context) { return 31; }
static const char * YesPage_Num8_Text__Property(void *context) { return "8"; }
static ft_int16_t YesPage_Back_X__Property(void *context) { return 559; }
static ft_int16_t YesPage_Back_Y__Property(void *context) { return 359; }
static ft_int16_t YesPage_Back_Width__Property(void *context) { return 140; }
static ft_int16_t YesPage_Back_Height__Property(void *context) { return 50; }
static ft_int16_t YesPage_Back_Font__Property(void *context) { return 31; }
static const char * YesPage_Back_Text__Property(void *context) { return "Back"; }
static ft_int16_t YesPage_Num0_X__Property(void *context) { return 130; }
static ft_int16_t YesPage_Num0_Y__Property(void *context) { return 360; }
static ft_int16_t YesPage_Num0_Width__Property(void *context) { return 60; }
static ft_int16_t YesPage_Num0_Height__Property(void *context) { return 60; }
static ft_int16_t YesPage_Num0_Font__Property(void *context) { return 31; }
static const char * YesPage_Num0_Text__Property(void *context) { return "0"; }
static ft_int16_t YesPage_ESD_Numeric_Label_X__Property(void *context) { return 565; }
static ft_int16_t YesPage_ESD_Numeric_Label_Y__Property(void *context) { return 225; }
static ft_int16_t YesPage_ESD_Numeric_Label_Width__Property(void *context) { return 140; }
static ft_int16_t YesPage_ESD_Numeric_Label_Height__Property(void *context) { return 60; }
static ft_int16_t YesPage_ESD_Numeric_Label_Font__Property(void *context) { return 31; }
static ft_int32_t YesPage_ESD_Numeric_Label_Value__Property(void *context);
static ft_int16_t YesPage_ESD_Label_Font__Property(void *context) { return 31; }
static const char * YesPage_ESD_Label_Text__Property(void *context) { return "Enter Confirmation Code"; }
static ft_int16_t YesPage_ESD_Label_X__Property(void *context) { return 200; }
static ft_int16_t YesPage_ESD_Label_Y__Property(void *context) { return 50; }
static ft_int16_t YesPage_ESD_Label_Width__Property(void *context) { return 400; }
static ft_int16_t YesPage_ESD_Label_Height__Property(void *context) { return 40; }
static ft_uint16_t YesPage_ESD_Label_AlignX__Property(void *context) { return OPT_ALIGN_CENTER; }
static ft_uint16_t YesPage_ESD_Label_AlignY__Property(void *context) { return OPT_ALIGN_CENTER; }
static ft_int16_t YesPage_Num3_X__Property(void *context) { return 210; }
static ft_int16_t YesPage_Num3_Y__Property(void *context) { return 120; }
static ft_int16_t YesPage_Num3_Width__Property(void *context) { return 60; }
static ft_int16_t YesPage_Num3_Height__Property(void *context) { return 60; }
static ft_int16_t YesPage_Num3_Font__Property(void *context) { return 31; }
static const char * YesPage_Num3_Text__Property(void *context) { return "3"; }
static ft_int16_t YesPage_Cancel_X__Property(void *context) { return 50; }
static ft_int16_t YesPage_Cancel_Y__Property(void *context) { return 360; }
static ft_int16_t YesPage_Cancel_Width__Property(void *context) { return 60; }
static ft_int16_t YesPage_Cancel_Height__Property(void *context) { return 60; }
static ft_int16_t YesPage_Cancel_Font__Property(void *context) { return 31; }
static const char * YesPage_Cancel_Text__Property(void *context) { return "C"; }
static ft_int16_t YesPage_OK_X__Property(void *context) { return 210; }
static ft_int16_t YesPage_OK_Y__Property(void *context) { return 360; }
static ft_int16_t YesPage_OK_Width__Property(void *context) { return 60; }
static ft_int16_t YesPage_OK_Height__Property(void *context) { return 60; }
static ft_int16_t YesPage_OK_Font__Property(void *context) { return 31; }
static const char * YesPage_OK_Text__Property(void *context) { return "OK"; }

static void YesPage_Num2_Pushed__Signal(void *context);
static void YesPage_Num1_Pushed__Signal(void *context);
static void YesPage_Num4_Pushed__Signal(void *context);
static void YesPage_Num5_Pushed__Signal(void *context);
static void YesPage_Num6_Pushed__Signal(void *context);
static void YesPage_Num7_Pushed__Signal(void *context);
static void YesPage_Num9_Pushed__Signal(void *context);
static void YesPage_Num8_Pushed__Signal(void *context);
static void YesPage_Back_Pushed__Signal(void *context);
static void YesPage_Num0_Pushed__Signal(void *context);
static void YesPage_Num3_Pushed__Signal(void *context);
static void YesPage_Cancel_Pushed__Signal(void *context);
static void YesPage_OK_Pushed__Signal(void *context);

void YesPage__Initializer(YesPage *context)
{
	context->Parent = 0;
	context->confCodeInt = 0L;
	context->Variable = 0L;
	context->KeyPadBack = Ft_Esd_Noop;
	context->Confirmation = Ft_Esd_Noop;
	Ft_Esd_PushButton__Initializer(&context->Num2);
	context->Num2.Parent = context;
	context->Num2.X = YesPage_Num2_X__Property;
	context->Num2.Y = YesPage_Num2_Y__Property;
	context->Num2.Width = YesPage_Num2_Width__Property;
	context->Num2.Height = YesPage_Num2_Height__Property;
	context->Num2.Font = YesPage_Num2_Font__Property;
	context->Num2.Text = YesPage_Num2_Text__Property;
	context->Num2.Pushed = YesPage_Num2_Pushed__Signal;
	Ft_Esd_PushButton__Initializer(&context->Num1);
	context->Num1.Parent = context;
	context->Num1.X = YesPage_Num1_X__Property;
	context->Num1.Y = YesPage_Num1_Y__Property;
	context->Num1.Width = YesPage_Num1_Width__Property;
	context->Num1.Height = YesPage_Num1_Height__Property;
	context->Num1.Font = YesPage_Num1_Font__Property;
	context->Num1.Text = YesPage_Num1_Text__Property;
	context->Num1.Pushed = YesPage_Num1_Pushed__Signal;
	Ft_Esd_PushButton__Initializer(&context->Num4);
	context->Num4.Parent = context;
	context->Num4.X = YesPage_Num4_X__Property;
	context->Num4.Y = YesPage_Num4_Y__Property;
	context->Num4.Width = YesPage_Num4_Width__Property;
	context->Num4.Height = YesPage_Num4_Height__Property;
	context->Num4.Font = YesPage_Num4_Font__Property;
	context->Num4.Text = YesPage_Num4_Text__Property;
	context->Num4.Pushed = YesPage_Num4_Pushed__Signal;
	Ft_Esd_PushButton__Initializer(&context->Num5);
	context->Num5.Parent = context;
	context->Num5.X = YesPage_Num5_X__Property;
	context->Num5.Y = YesPage_Num5_Y__Property;
	context->Num5.Width = YesPage_Num5_Width__Property;
	context->Num5.Height = YesPage_Num5_Height__Property;
	context->Num5.Font = YesPage_Num5_Font__Property;
	context->Num5.Text = YesPage_Num5_Text__Property;
	context->Num5.Pushed = YesPage_Num5_Pushed__Signal;
	Ft_Esd_PushButton__Initializer(&context->Num6);
	context->Num6.Parent = context;
	context->Num6.X = YesPage_Num6_X__Property;
	context->Num6.Y = YesPage_Num6_Y__Property;
	context->Num6.Width = YesPage_Num6_Width__Property;
	context->Num6.Height = YesPage_Num6_Height__Property;
	context->Num6.Font = YesPage_Num6_Font__Property;
	context->Num6.Text = YesPage_Num6_Text__Property;
	context->Num6.Pushed = YesPage_Num6_Pushed__Signal;
	Ft_Esd_PushButton__Initializer(&context->Num7);
	context->Num7.Parent = context;
	context->Num7.X = YesPage_Num7_X__Property;
	context->Num7.Y = YesPage_Num7_Y__Property;
	context->Num7.Width = YesPage_Num7_Width__Property;
	context->Num7.Height = YesPage_Num7_Height__Property;
	context->Num7.Font = YesPage_Num7_Font__Property;
	context->Num7.Text = YesPage_Num7_Text__Property;
	context->Num7.Pushed = YesPage_Num7_Pushed__Signal;
	Ft_Esd_PushButton__Initializer(&context->Num9);
	context->Num9.Parent = context;
	context->Num9.X = YesPage_Num9_X__Property;
	context->Num9.Y = YesPage_Num9_Y__Property;
	context->Num9.Width = YesPage_Num9_Width__Property;
	context->Num9.Height = YesPage_Num9_Height__Property;
	context->Num9.Font = YesPage_Num9_Font__Property;
	context->Num9.Text = YesPage_Num9_Text__Property;
	context->Num9.Pushed = YesPage_Num9_Pushed__Signal;
	Ft_Esd_PushButton__Initializer(&context->Num8);
	context->Num8.Parent = context;
	context->Num8.X = YesPage_Num8_X__Property;
	context->Num8.Y = YesPage_Num8_Y__Property;
	context->Num8.Width = YesPage_Num8_Width__Property;
	context->Num8.Height = YesPage_Num8_Height__Property;
	context->Num8.Font = YesPage_Num8_Font__Property;
	context->Num8.Text = YesPage_Num8_Text__Property;
	context->Num8.Pushed = YesPage_Num8_Pushed__Signal;
	Ft_Esd_PushButton__Initializer(&context->Back);
	context->Back.Parent = context;
	context->Back.X = YesPage_Back_X__Property;
	context->Back.Y = YesPage_Back_Y__Property;
	context->Back.Width = YesPage_Back_Width__Property;
	context->Back.Height = YesPage_Back_Height__Property;
	context->Back.Font = YesPage_Back_Font__Property;
	context->Back.Text = YesPage_Back_Text__Property;
	context->Back.Pushed = YesPage_Back_Pushed__Signal;
	Ft_Esd_PushButton__Initializer(&context->Num0);
	context->Num0.Parent = context;
	context->Num0.X = YesPage_Num0_X__Property;
	context->Num0.Y = YesPage_Num0_Y__Property;
	context->Num0.Width = YesPage_Num0_Width__Property;
	context->Num0.Height = YesPage_Num0_Height__Property;
	context->Num0.Font = YesPage_Num0_Font__Property;
	context->Num0.Text = YesPage_Num0_Text__Property;
	context->Num0.Pushed = YesPage_Num0_Pushed__Signal;
	Ft_Esd_NumericLabel__Initializer(&context->ESD_Numeric_Label);
	context->ESD_Numeric_Label.Parent = context;
	context->ESD_Numeric_Label.X = YesPage_ESD_Numeric_Label_X__Property;
	context->ESD_Numeric_Label.Y = YesPage_ESD_Numeric_Label_Y__Property;
	context->ESD_Numeric_Label.Width = YesPage_ESD_Numeric_Label_Width__Property;
	context->ESD_Numeric_Label.Height = YesPage_ESD_Numeric_Label_Height__Property;
	context->ESD_Numeric_Label.Font = YesPage_ESD_Numeric_Label_Font__Property;
	context->ESD_Numeric_Label.Value = YesPage_ESD_Numeric_Label_Value__Property;
	Ft_Esd_Label__Initializer(&context->ESD_Label);
	context->ESD_Label.Parent = context;
	context->ESD_Label.Font = YesPage_ESD_Label_Font__Property;
	context->ESD_Label.Text = YesPage_ESD_Label_Text__Property;
	context->ESD_Label.X = YesPage_ESD_Label_X__Property;
	context->ESD_Label.Y = YesPage_ESD_Label_Y__Property;
	context->ESD_Label.Width = YesPage_ESD_Label_Width__Property;
	context->ESD_Label.Height = YesPage_ESD_Label_Height__Property;
	context->ESD_Label.AlignX = YesPage_ESD_Label_AlignX__Property;
	context->ESD_Label.AlignY = YesPage_ESD_Label_AlignY__Property;
	Ft_Esd_PushButton__Initializer(&context->Num3);
	context->Num3.Parent = context;
	context->Num3.X = YesPage_Num3_X__Property;
	context->Num3.Y = YesPage_Num3_Y__Property;
	context->Num3.Width = YesPage_Num3_Width__Property;
	context->Num3.Height = YesPage_Num3_Height__Property;
	context->Num3.Font = YesPage_Num3_Font__Property;
	context->Num3.Text = YesPage_Num3_Text__Property;
	context->Num3.Pushed = YesPage_Num3_Pushed__Signal;
	Ft_Esd_PushButton__Initializer(&context->Cancel);
	context->Cancel.Parent = context;
	context->Cancel.X = YesPage_Cancel_X__Property;
	context->Cancel.Y = YesPage_Cancel_Y__Property;
	context->Cancel.Width = YesPage_Cancel_Width__Property;
	context->Cancel.Height = YesPage_Cancel_Height__Property;
	context->Cancel.Font = YesPage_Cancel_Font__Property;
	context->Cancel.Text = YesPage_Cancel_Text__Property;
	context->Cancel.Pushed = YesPage_Cancel_Pushed__Signal;
	Ft_Esd_PushButton__Initializer(&context->OK);
	context->OK.Parent = context;
	context->OK.X = YesPage_OK_X__Property;
	context->OK.Y = YesPage_OK_Y__Property;
	context->OK.Width = YesPage_OK_Width__Property;
	context->OK.Height = YesPage_OK_Height__Property;
	context->OK.Font = YesPage_OK_Font__Property;
	context->OK.Text = YesPage_OK_Text__Property;
	context->OK.Pushed = YesPage_OK_Pushed__Signal;
}

void YesPage_resetCCode_Signal(YesPage *context);
void YesPage_Num2_Pushed(YesPage *context);
void YesPage_Num3_Pushed(YesPage *context);
void YesPage_confirmationCode(YesPage *context);
void YesPage_Num1_Pushed(YesPage *context);
void YesPage_Num4_Pushed(YesPage *context);
void YesPage_Num5_Pushed(YesPage *context);
void YesPage_Num6_Pushed(YesPage *context);
void YesPage_Num7_Pushed(YesPage *context);
void YesPage_Num9_Pushed(YesPage *context);
void YesPage_Num8_Pushed(YesPage *context);
void YesPage_Back_Pushed(YesPage *context);
void YesPage_Cancel_Pushed(YesPage *context);
void YesPage_Num0_Pushed(YesPage *context);
void YesPage_OK_Pushed(YesPage *context);
ft_void_t Ft_Esd_Render_RectangleF(ft_int32_f4_t, ft_int32_f4_t, ft_int32_f4_t, ft_int32_f4_t, ft_int32_f4_t, ft_argb32_t);
void Ft_Esd_Theme_SetCurrent(Ft_Esd_Theme *);

void YesPage_Start(YesPage *context)
{
	void *parent = context->Parent;
	Ft_Esd_PushButton_Start(&context->Num2);
	Ft_Esd_PushButton_Start(&context->Num1);
	Ft_Esd_PushButton_Start(&context->Num4);
	Ft_Esd_PushButton_Start(&context->Num5);
	Ft_Esd_PushButton_Start(&context->Num6);
	Ft_Esd_PushButton_Start(&context->Num7);
	Ft_Esd_PushButton_Start(&context->Num9);
	Ft_Esd_PushButton_Start(&context->Num8);
	Ft_Esd_PushButton_Start(&context->Back);
	Ft_Esd_PushButton_Start(&context->Num0);
	Ft_Esd_PushButton_Start(&context->Num3);
	Ft_Esd_PushButton_Start(&context->Cancel);
	Ft_Esd_PushButton_Start(&context->OK);
}

void YesPage_Update(YesPage *context)
{
	void *parent = context->Parent;
	Ft_Esd_PushButton_Update(&context->Num2);
	Ft_Esd_PushButton_Update(&context->Num1);
	Ft_Esd_PushButton_Update(&context->Num4);
	Ft_Esd_PushButton_Update(&context->Num5);
	Ft_Esd_PushButton_Update(&context->Num6);
	Ft_Esd_PushButton_Update(&context->Num7);
	Ft_Esd_PushButton_Update(&context->Num9);
	Ft_Esd_PushButton_Update(&context->Num8);
	Ft_Esd_PushButton_Update(&context->Back);
	Ft_Esd_PushButton_Update(&context->Num0);
	Ft_Esd_PushButton_Update(&context->Num3);
	Ft_Esd_PushButton_Update(&context->Cancel);
	Ft_Esd_PushButton_Update(&context->OK);
}

void YesPage_Render(YesPage *context)
{
	void *parent = context->Parent;
	ft_int32_f4_t x = 0;
	ft_int32_f4_t y = 0;
	ft_int32_f4_t width = (800 * (1 << 4) + 0x0);
	ft_int32_f4_t height = (480 * (1 << 4) + 0x0);
	ft_int32_f4_t radius = (4 * (1 << 4) + 0x0);
	ft_argb32_t color = 0xff000000UL;
	Ft_Esd_Render_RectangleF(x, y, width, height, radius, color);
	Ft_Esd_Theme * theme = purdue();
	Ft_Esd_Theme_SetCurrent(theme);
	Ft_Esd_PushButton_Render(&context->Num2);
	Ft_Esd_PushButton_Render(&context->Num1);
	Ft_Esd_PushButton_Render(&context->Num4);
	Ft_Esd_PushButton_Render(&context->Num5);
	Ft_Esd_PushButton_Render(&context->Num6);
	ft_int32_t x_1 = 550L;
	ft_int32_t y_1 = 220L;
	ft_int32_t width_1 = 140L;
	ft_int32_t height_1 = 60L;
	ft_int32_t radius_1 = 4L;
	ft_argb32_t color_1 = 0xff000000UL;
	Ft_Esd_Render_Rectangle(x_1, y_1, width_1, height_1, radius_1, color_1);
	Ft_Esd_PushButton_Render(&context->Num7);
	Ft_Esd_PushButton_Render(&context->Num9);
	Ft_Esd_PushButton_Render(&context->Num8);
	Ft_Esd_PushButton_Render(&context->Back);
	Ft_Esd_PushButton_Render(&context->Num0);
	Ft_Esd_NumericLabel_Render(&context->ESD_Numeric_Label);
	Ft_Esd_Label_Render(&context->ESD_Label);
	Ft_Esd_PushButton_Render(&context->Num3);
	Ft_Esd_PushButton_Render(&context->Cancel);
	Ft_Esd_PushButton_Render(&context->OK);
}

void YesPage_Idle(YesPage *context)
{
	void *parent = context->Parent;
}

void YesPage_End(YesPage *context)
{
	void *parent = context->Parent;
	Ft_Esd_PushButton_End(&context->Num2);
	Ft_Esd_PushButton_End(&context->Num1);
	Ft_Esd_PushButton_End(&context->Num4);
	Ft_Esd_PushButton_End(&context->Num5);
	Ft_Esd_PushButton_End(&context->Num6);
	Ft_Esd_PushButton_End(&context->Num7);
	Ft_Esd_PushButton_End(&context->Num9);
	Ft_Esd_PushButton_End(&context->Num8);
	Ft_Esd_PushButton_End(&context->Back);
	Ft_Esd_PushButton_End(&context->Num0);
	Ft_Esd_PushButton_End(&context->Num3);
	Ft_Esd_PushButton_End(&context->Cancel);
	Ft_Esd_PushButton_End(&context->OK);
}

void YesPage_resetCCode(YesPage *context)
{
	void *parent = context->Parent;
	YesPage_resetCCode_Signal(context);
}

void YesPage_Num2_Pushed__Signal(void *c)
{
	YesPage *context = (YesPage *)c;
	void *parent = context->Parent;
	YesPage_Num2_Pushed(context);
	YesPage_confirmationCode(context);
	int set_variable = context->confCodeInt;
	context->Variable = set_variable;
}

void YesPage_Num1_Pushed__Signal(void *c)
{
	YesPage *context = (YesPage *)c;
	void *parent = context->Parent;
	YesPage_Num1_Pushed(context);
	YesPage_confirmationCode(context);
	int set_variable_1 = context->confCodeInt;
	context->Variable = set_variable_1;
}

void YesPage_Num4_Pushed__Signal(void *c)
{
	YesPage *context = (YesPage *)c;
	void *parent = context->Parent;
	YesPage_Num4_Pushed(context);
	YesPage_confirmationCode(context);
	int set_variable_2 = context->confCodeInt;
	context->Variable = set_variable_2;
}

void YesPage_Num5_Pushed__Signal(void *c)
{
	YesPage *context = (YesPage *)c;
	void *parent = context->Parent;
	YesPage_Num5_Pushed(context);
	YesPage_confirmationCode(context);
	int set_variable_3 = context->confCodeInt;
	context->Variable = set_variable_3;
}

void YesPage_Num6_Pushed__Signal(void *c)
{
	YesPage *context = (YesPage *)c;
	void *parent = context->Parent;
	YesPage_Num6_Pushed(context);
	YesPage_confirmationCode(context);
	int set_variable_4 = context->confCodeInt;
	context->Variable = set_variable_4;
}

void YesPage_Num7_Pushed__Signal(void *c)
{
	YesPage *context = (YesPage *)c;
	void *parent = context->Parent;
	YesPage_Num7_Pushed(context);
	YesPage_confirmationCode(context);
	int set_variable_5 = context->confCodeInt;
	context->Variable = set_variable_5;
}

void YesPage_Num9_Pushed__Signal(void *c)
{
	YesPage *context = (YesPage *)c;
	void *parent = context->Parent;
	YesPage_Num9_Pushed(context);
	YesPage_confirmationCode(context);
	int set_variable_6 = context->confCodeInt;
	context->Variable = set_variable_6;
}

void YesPage_Num8_Pushed__Signal(void *c)
{
	YesPage *context = (YesPage *)c;
	void *parent = context->Parent;
	YesPage_Num8_Pushed(context);
	YesPage_confirmationCode(context);
	int set_variable_7 = context->confCodeInt;
	context->Variable = set_variable_7;
}

void YesPage_Back_Pushed__Signal(void *c)
{
	YesPage *context = (YesPage *)c;
	void *parent = context->Parent;
	YesPage_Back_Pushed(context);
	context->KeyPadBack(parent);
}

void YesPage_Num0_Pushed__Signal(void *c)
{
	YesPage *context = (YesPage *)c;
	void *parent = context->Parent;
	YesPage_confirmationCode(context);
	int set_variable_8 = context->confCodeInt;
	context->Variable = set_variable_8;
	YesPage_Num0_Pushed(context);
}

ft_int32_t YesPage_ESD_Numeric_Label_Value__Property(void *c)
{
	YesPage *context = (YesPage *)c;
	void *parent = context->Parent;
	return context->Variable;
}

void YesPage_Num3_Pushed__Signal(void *c)
{
	YesPage *context = (YesPage *)c;
	void *parent = context->Parent;
	YesPage_Num3_Pushed(context);
	YesPage_confirmationCode(context);
	int set_variable_9 = context->confCodeInt;
	context->Variable = set_variable_9;
}

void YesPage_Cancel_Pushed__Signal(void *c)
{
	YesPage *context = (YesPage *)c;
	void *parent = context->Parent;
	YesPage_Cancel_Pushed(context);
	YesPage_confirmationCode(context);
	int set_variable_10 = context->confCodeInt;
	context->Variable = set_variable_10;
}

void YesPage_OK_Pushed__Signal(void *c)
{
	YesPage *context = (YesPage *)c;
	void *parent = context->Parent;
	YesPage_OK_Pushed(context);
	context->Confirmation(parent);
}

#ifdef ESD_SIMULATION
#include <stdlib.h>

typedef struct
{
	YesPage Instance;
} YesPage__ESD;


void *YesPage__Create__ESD()
{
	YesPage__ESD *context = (YesPage__ESD *)malloc(sizeof(YesPage__ESD));
	YesPage__Initializer(&context->Instance);
	context->Instance.Parent = context;
	return context;
}

void YesPage__Destroy__ESD(void *context)
{
	free(context);
}

void YesPage__Set_confCodeInt__ESD(void *context, int value) { ((YesPage__ESD *)context)->Instance.confCodeInt = value; }
void YesPage__Set_Variable__ESD(void *context, int value) { ((YesPage__ESD *)context)->Instance.Variable = value; }

#endif /* ESD_SIMULATION */

/* end of file */
