/*
This file is automatically generated
DO NOT MODIFY BY HAND
Ft_Esd_LabelButton
C Source
*/

#include "Ft_Esd_LabelButton.h"

#include "FT_Esd_Dl.h"
#include "FT_Gpu.h"
#include "Ft_Esd_CoCmd.h"

extern void Ft_Esd_Noop(void *context);
Ft_Esd_Theme * Ft_Esd_LabelButton_Theme__Default(void *context) { return Ft_Esd_Theme_GetCurrent(); }
ft_int16_t Ft_Esd_LabelButton_Font__Default(void *context) { return 27; }
const char * Ft_Esd_LabelButton_Text__Default(void *context) { return "Label Button"; }
ft_bool_t Ft_Esd_LabelButton_Primary__Default(void *context) { return 1; }
ft_uint16_t Ft_Esd_LabelButton_AlignX__Default(void *context) { return OPT_ALIGN_LEFT; }
ft_uint16_t Ft_Esd_LabelButton_AlignY__Default(void *context) { return OPT_ALIGN_CENTER; }
ft_uint8_t Ft_Esd_LabelButton_AutoResize__Default(void *context) { return ESD_AUTORESIZE_HEIGHT; }


static Ft_Esd_WidgetSlots s_Ft_Esd_LabelButton__Slots = {
	(void(*)(void *))Ft_Esd_Widget_Initialize,
	(void(*)(void *))Ft_Esd_LabelButton_Start,
	(void(*)(void *))Ft_Esd_Widget_Enable,
	(void(*)(void *))Ft_Esd_LabelButton_Update,
	(void(*)(void *))Ft_Esd_LabelButton_Render,
	(void(*)(void *))Ft_Esd_Widget_Idle,
	(void(*)(void *))Ft_Esd_Widget_Disable,
	(void(*)(void *))Ft_Esd_LabelButton_End,
};

static void Ft_Esd_LabelButton_Touch_Tag_Tap__Signal(void *context);

void Ft_Esd_LabelButton__Touch_Tag__Initializer(Ft_Esd_LabelButton *context)
{
	Ft_Esd_TouchTag *object = &context->Touch_Tag;
	Ft_Esd_TouchTag__Initializer(object);
	object->Owner = context;
	object->Tap = Ft_Esd_LabelButton_Touch_Tag_Tap__Signal;
}

void Ft_Esd_LabelButton__Initializer(Ft_Esd_LabelButton *context)
{
	Ft_Esd_Widget__Initializer((Ft_Esd_Widget *)context);
	context->Widget.ClassId = Ft_Esd_LabelButton_CLASSID;
	context->Widget.Slots = &s_Ft_Esd_LabelButton__Slots;
	context->Widget.LocalX = 0;
	context->Widget.LocalY = 0;
	context->Widget.LocalWidth = 120;
	context->Widget.LocalHeight = 36;
	context->Pushed = Ft_Esd_Noop;
	context->Theme = Ft_Esd_LabelButton_Theme__Default;
	context->X = 0L;
	context->Y = 0L;
	context->Font = Ft_Esd_LabelButton_Font__Default;
	context->Text = Ft_Esd_LabelButton_Text__Default;
	context->Primary = Ft_Esd_LabelButton_Primary__Default;
	context->AlignX = Ft_Esd_LabelButton_AlignX__Default;
	context->FontHeight = 0;
	context->AlignY = Ft_Esd_LabelButton_AlignY__Default;
	context->AutoResize = Ft_Esd_LabelButton_AutoResize__Default;
	Ft_Esd_LabelButton__Touch_Tag__Initializer(context);
}

ft_void_t Ft_Gpu_CoCmd_Text(Ft_Gpu_Hal_Context_t *, ft_int16_t, ft_int16_t, ft_int16_t, ft_uint16_t, const ft_char8_t *);
ft_uint8_t Ft_Esd_Dl_RomFont_Setup(ft_uint8_t);
ft_uint16_t Ft_Esd_LabelButton_GetOptionUpdatePosition(Ft_Esd_LabelButton *context);

void Ft_Esd_LabelButton_Start__Builtin(Ft_Esd_LabelButton *context)
{
	void *owner = context->Owner;
	Ft_Esd_Widget_Start((Ft_Esd_Widget *)context);
	Ft_Esd_TouchTag_Start(&context->Touch_Tag);
}

void Ft_Esd_LabelButton_End__Builtin(Ft_Esd_LabelButton *context)
{
	void *owner = context->Owner;
	Ft_Esd_TouchTag_End(&context->Touch_Tag);
	Ft_Esd_Widget_End((Ft_Esd_Widget *)context);
}

void Ft_Esd_LabelButton_Update(Ft_Esd_LabelButton *context)
{
	void *owner = context->Owner;
	Ft_Esd_TouchTag_Update(&context->Touch_Tag);
	ft_uint8_t left = context->AutoResize(owner);
	ft_uint8_t right = ESD_AUTORESIZE_HEIGHT;
	int if_1 = left == right;
	if (if_1)
	{
		ft_int16_t set_fontheight_to_local = context->FontHeight;
		Ft_Esd_Widget_SetHeight((Ft_Esd_Widget *)context, set_fontheight_to_local);
	}
	else
	{
	}
	Ft_Esd_Widget_Update((Ft_Esd_Widget *)context); 
}

void Ft_Esd_LabelButton_End(Ft_Esd_LabelButton *context)
{
	void *owner = context->Owner;
	Ft_Esd_LabelButton_End__Builtin(context);
}

void Ft_Esd_LabelButton_Render(Ft_Esd_LabelButton *context)
{
	void *owner = context->Owner;
	ft_uint8_t alpha = 255;
	Ft_Esd_Dl_COLOR_A(alpha);
	ft_uint8_t s = Ft_Esd_TouchTag_Tag(&context->Touch_Tag);
	Ft_Esd_Dl_TAG(s);
	ft_bool_t if_2 = Ft_Esd_TouchTag_Inside(&context->Touch_Tag);
	ft_rgb32_t c_1;
	if (if_2)
	{
		Ft_Esd_Theme * theme = context->Theme(owner);
		c_1 = Ft_Esd_Theme_GetTextColor(theme);
	}
	else
	{
		ft_bool_t if_3 = context->Primary(owner);
		if (if_3)
		{
			Ft_Esd_Theme * theme_1 = context->Theme(owner);
			c_1 = Ft_Esd_Theme_GetPrimaryColor(theme_1);
		}
		else
		{
			Ft_Esd_Theme * theme_2 = context->Theme(owner);
			c_1 = Ft_Esd_Theme_GetCurrentColor(theme_2);
		}
	}
	Ft_Esd_Dl_COLOR_RGB(c_1);
	Ft_Gpu_Hal_Context_t * phost = Ft_Esd_GetHost();
	int x = context->X;
	int y = context->Y;
	ft_int16_t font_1 = context->Font(owner);
	ft_uint8_t font = Ft_Esd_Dl_RomFont_Setup(font_1);
	ft_uint16_t options = Ft_Esd_LabelButton_GetOptionUpdatePosition(context);
	const char * s_1 = context->Text(owner);
	Ft_Gpu_CoCmd_Text(phost, x, y, font, options, s_1);
	ft_uint8_t s_2 = 255;
	Ft_Esd_Dl_TAG(s_2);
	Ft_Esd_Widget_Render((Ft_Esd_Widget *)context); 
}

void Ft_Esd_LabelButton_Start(Ft_Esd_LabelButton *context)
{
	void *owner = context->Owner;
	Ft_Esd_LabelButton_Start__Builtin(context);
	ft_int16_t i = context->Font(owner);
	ft_uint16_t set_variable = Ft_Esd_GetFontHeight(i);
	context->FontHeight = (int)set_variable;
}

void Ft_Esd_LabelButton_Touch_Tag_Tap__Signal(void *c)
{
	Ft_Esd_LabelButton *context = (Ft_Esd_LabelButton *)c;
	void *owner = context->Owner;
	context->Pushed(owner);
}

#ifdef ESD_SIMULATION
#include <stdlib.h>

typedef struct
{
	Ft_Esd_LabelButton Instance;
	Ft_Esd_Theme * Theme;
	ft_int16_t Font;
	const char * Text;
	ft_bool_t Primary;
	ft_uint16_t AlignX;
	ft_uint16_t AlignY;
	ft_uint8_t AutoResize;
} Ft_Esd_LabelButton__ESD;

Ft_Esd_Theme * Ft_Esd_LabelButton__Get_Theme__ESD(void *context) { return ((Ft_Esd_LabelButton__ESD *)context)->Theme; }
void Ft_Esd_LabelButton__Set_Theme__ESD(void *context, Ft_Esd_Theme * value) { ((Ft_Esd_LabelButton__ESD *)context)->Theme = value; }
ft_int16_t Ft_Esd_LabelButton__Get_Font__ESD(void *context) { return ((Ft_Esd_LabelButton__ESD *)context)->Font; }
void Ft_Esd_LabelButton__Set_Font__ESD(void *context, ft_int16_t value) { ((Ft_Esd_LabelButton__ESD *)context)->Font = value; }
const char * Ft_Esd_LabelButton__Get_Text__ESD(void *context) { return ((Ft_Esd_LabelButton__ESD *)context)->Text; }
void Ft_Esd_LabelButton__Set_Text__ESD(void *context, const char * value) { ((Ft_Esd_LabelButton__ESD *)context)->Text = value; }
ft_bool_t Ft_Esd_LabelButton__Get_Primary__ESD(void *context) { return ((Ft_Esd_LabelButton__ESD *)context)->Primary; }
void Ft_Esd_LabelButton__Set_Primary__ESD(void *context, ft_bool_t value) { ((Ft_Esd_LabelButton__ESD *)context)->Primary = value; }
ft_uint16_t Ft_Esd_LabelButton__Get_AlignX__ESD(void *context) { return ((Ft_Esd_LabelButton__ESD *)context)->AlignX; }
void Ft_Esd_LabelButton__Set_AlignX__ESD(void *context, ft_uint16_t value) { ((Ft_Esd_LabelButton__ESD *)context)->AlignX = value; }
ft_uint16_t Ft_Esd_LabelButton__Get_AlignY__ESD(void *context) { return ((Ft_Esd_LabelButton__ESD *)context)->AlignY; }
void Ft_Esd_LabelButton__Set_AlignY__ESD(void *context, ft_uint16_t value) { ((Ft_Esd_LabelButton__ESD *)context)->AlignY = value; }
ft_uint8_t Ft_Esd_LabelButton__Get_AutoResize__ESD(void *context) { return ((Ft_Esd_LabelButton__ESD *)context)->AutoResize; }
void Ft_Esd_LabelButton__Set_AutoResize__ESD(void *context, ft_uint8_t value) { ((Ft_Esd_LabelButton__ESD *)context)->AutoResize = value; }

void *Ft_Esd_LabelButton__Create__ESD()
{
	Ft_Esd_LabelButton__ESD *context = (Ft_Esd_LabelButton__ESD *)malloc(sizeof(Ft_Esd_LabelButton__ESD));
	Ft_Esd_LabelButton__Initializer(&context->Instance);
	context->Instance.Owner = context;
	context->Theme = Ft_Esd_Theme_GetCurrent();
	context->Instance.Theme = Ft_Esd_LabelButton__Get_Theme__ESD;
	context->Font = 27;
	context->Instance.Font = Ft_Esd_LabelButton__Get_Font__ESD;
	context->Text = "Label Button";
	context->Instance.Text = Ft_Esd_LabelButton__Get_Text__ESD;
	context->Primary = 1;
	context->Instance.Primary = Ft_Esd_LabelButton__Get_Primary__ESD;
	context->AlignX = OPT_ALIGN_LEFT;
	context->Instance.AlignX = Ft_Esd_LabelButton__Get_AlignX__ESD;
	context->AlignY = OPT_ALIGN_CENTER;
	context->Instance.AlignY = Ft_Esd_LabelButton__Get_AlignY__ESD;
	context->AutoResize = ESD_AUTORESIZE_HEIGHT;
	context->Instance.AutoResize = Ft_Esd_LabelButton__Get_AutoResize__ESD;
	return context;
}

void Ft_Esd_LabelButton__Destroy__ESD(void *context)
{
	free(context);
}

void Ft_Esd_LabelButton__Set_X__ESD(void *context, int value) { ((Ft_Esd_LabelButton__ESD *)context)->Instance.X = value; }
void Ft_Esd_LabelButton__Set_Y__ESD(void *context, int value) { ((Ft_Esd_LabelButton__ESD *)context)->Instance.Y = value; }
void Ft_Esd_LabelButton__Set_FontHeight__ESD(void *context, ft_int16_t value) { ((Ft_Esd_LabelButton__ESD *)context)->Instance.FontHeight = value; }

#endif /* ESD_SIMULATION */

/* end of file */
