/*
This file is automatically generated
DO NOT MODIFY BY HAND
MainPage
Header
*/

#ifndef MainPage__H
#define MainPage__H

#include "Ft_Esd.h"
#include "Ft_Esd_Label.h"
#include "Ft_Esd_Layout_Fill.h"
#include "Ft_Esd_Layout_Fixed.h"
#include "Ft_Esd_PushButton.h"
#include "Ft_Esd_Theme.h"
#include "Ft_Esd_Widget.h"

#ifndef ESD_LOGIC
#define ESD_LOGIC(name, ...)
#define ESD_ACTOR(name, ...)
#define ESD_WIDGET(name, ...)
#define ESD_UI(name, ...)
#define ESD_PAGE(name, ...)
#define ESD_APPLICATION(name, ...)
#define ESD_INPUT(name, ...)
#define ESD_OUTPUT(name, ...)
#define ESD_SLOT(name, ...)
#define ESD_SIGNAL(name, ...)
#define ESD_VARIABLE(name, ...)
#define ESD_WRITER(name, ...)
#endif

#define MainPage_CLASSID 0x26757037
ESD_SYMBOL(MainPage_CLASSID, Type = esd_classid_t)

ESD_WIDGET(MainPage, Include = "MainPage.h", Callback, X = 0, Y = 0, Width = 400, Height = 300, Page)
typedef struct
{
	union
	{
		void *Owner;
		Ft_Esd_Widget Widget;
	};
	Ft_Esd_Layout_Fill Fill_Layout;
	Ft_Esd_Layout_Fixed Fixed_Position;
	Ft_Esd_PushButton ESD_Push_Button_4;
	Ft_Esd_PushButton ESD_Push_Button_3;
	Ft_Esd_PushButton ESD_Push_Button_2;
	Ft_Esd_PushButton ESD_Push_Button;
	Ft_Esd_Label ESD_Label;
} MainPage;

void MainPage__Initializer(MainPage *context);

ESD_SLOT(End)
void MainPage_End(MainPage *context);

#endif /* MainPage__H */

/* end of file */
